### ISSUE TITLE
Recorder: Not able to record login scenario using Gatling 2.0.0-M3a

### ISSUE THREAD

**Issue by swapnil-kotwal-sp** [gatling/gatling#1792]
Hi,

I have tried to record some website login scenario but recorder throws exceptions.

I have landed on login page but when I entered valid creadentials, it won't works for me.

I have win 7, 64 bit machine and Java 8 installed.

Also, I have a problem to render paged with HTTPS protocol and I'm not able to login as login pages mostly supports to HTTPS protocol.

```
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:913) ~[netty-3.6.6.Final.jar:n
a]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3
.6.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[ne
tty-3.6.6.Final.jar:na]
        at io.gatling.recorder.http.ssl.FirstEventIsUnsecuredConnectSslHandler.handleUpstream(FirstEven
tIsUnsecuredConnectSslHandler.scala:31) ~[gatling-recorder-2.0.0-M3a.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar
:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-
3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar
:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20-ea]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_20-ea]
17:38:22.884 [ERROR] i.g.r.h.h.BrowserHttpsRequestHandler - Exception caught
javax.net.ssl.SSLException: Received fatal alert: bad_certificate
        at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.recvAlert(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.readRecord(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[na:1.8.0_20-ea]
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[na:1.8.0_20-ea]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1225) ~[netty-3.6.6.Final.jar:
na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:913) ~[netty-3.6.6.Final.jar:n
a]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3
.6.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[ne
tty-3.6.6.Final.jar:na]
        at io.gatling.recorder.http.ssl.FirstEventIsUnsecuredConnectSslHandler.handleUpstream(FirstEven
tIsUnsecuredConnectSslHandler.scala:31) ~[gatling-recorder-2.0.0-M3a.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar
:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-
3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar
:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20-ea]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_20-ea]
17:38:23.033 [WARN ] i.g.r.h.h.BrowserHttpsRequestHandler - Trying to connect to https://api.abc.com
:443, make sure you've accepted the recorder certificate for this site
17:38:23.063 [ERROR] i.g.r.h.h.BrowserHttpsRequestHandler - Exception caught
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_20-ea]
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(Socket
SendBufferPool.java:203) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:202) ~[ne
tty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.jav
a:147) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServe
rSocketPipelineSink.java:99) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipe
lineSink.java:36) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:725) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:686) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:1153) ~[netty-3.6.6.Fi
nal.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1246) ~[netty-3.6.6.Final.jar:
na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:913) ~[netty-3.6.6.Final.jar:n
a]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3
.6.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[ne
tty-3.6.6.Final.jar:na]
        at io.gatling.recorder.http.ssl.FirstEventIsUnsecuredConnectSslHandler.handleUpstream(FirstEven
tIsUnsecuredConnectSslHandler.scala:31) ~[gatling-recorder-2.0.0-M3a.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar
:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-
3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar
:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20-ea]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_20-ea]
17:38:23.224 [WARN ] i.g.r.h.h.BrowserHttpsRequestHandler - Trying to connect to https://api.abc.com
:443, make sure you've accepted the recorder certificate for this site
17:38:23.260 [ERROR] i.g.r.h.h.BrowserHttpsRequestHandler - Exception caught
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_20-ea]
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(Socket
SendBufferPool.java:203) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:202) ~[ne
tty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.jav
a:147) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServe
rSocketPipelineSink.java:99) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipe
lineSink.java:36) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:725) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:686) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:1153) ~[netty-3.6.6.Fi
nal.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1246) ~[netty-3.6.6.Final.jar:
na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:913) ~[netty-3.6.6.Final.jar:n
a]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3
.6.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[ne
tty-3.6.6.Final.jar:na]
        at io.gatling.recorder.http.ssl.FirstEventIsUnsecuredConnectSslHandler.handleUpstream(FirstEven
tIsUnsecuredConnectSslHandler.scala:31) ~[gatling-recorder-2.0.0-M3a.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar
:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-
3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar
:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20-ea]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_20-ea]
17:38:23.272 [ERROR] i.g.r.h.h.BrowserHttpsRequestHandler - Exception caught
javax.net.ssl.SSLException: Received fatal alert: bad_certificate
        at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.recvAlert(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.readRecord(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[na:1.8.0_20-ea]
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[na:1.8.0_20-ea]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1225) ~[netty-3.6.6.Final.jar:
na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:913) ~[netty-3.6.6.Final.jar:n
a]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3
.6.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[ne
tty-3.6.6.Final.jar:na]
        at io.gatling.recorder.http.ssl.FirstEventIsUnsecuredConnectSslHandler.handleUpstream(FirstEven
tIsUnsecuredConnectSslHandler.scala:31) ~[gatling-recorder-2.0.0-M3a.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar
:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-
3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar
:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20-ea]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_20-ea]
17:38:23.377 [WARN ] i.g.r.h.h.BrowserHttpsRequestHandler - Trying to connect to https://api.abc.com
:443, make sure you've accepted the recorder certificate for this site
17:38:23.407 [ERROR] i.g.r.h.h.BrowserHttpsRequestHandler - Exception caught
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_20-ea]
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(Socket
SendBufferPool.java:203) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:202) ~[ne
tty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.jav
a:147) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServe
rSocketPipelineSink.java:99) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipe
lineSink.java:36) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:725) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:686) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:1153) ~[netty-3.6.6.Fi
nal.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1246) ~[netty-3.6.6.Final.jar:
na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:913) ~[netty-3.6.6.Final.jar:n
a]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3
.6.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[ne
tty-3.6.6.Final.jar:na]
        at io.gatling.recorder.http.ssl.FirstEventIsUnsecuredConnectSslHandler.handleUpstream(FirstEven
tIsUnsecuredConnectSslHandler.scala:31) ~[gatling-recorder-2.0.0-M3a.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar
:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-
3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar
:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20-ea]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_20-ea]
17:38:23.536 [WARN ] i.g.r.h.h.BrowserHttpsRequestHandler - Trying to connect to https://api.abc.com
:443, make sure you've accepted the recorder certificate for this site
17:38:23.563 [ERROR] i.g.r.h.h.BrowserHttpsRequestHandler - Exception caught
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_20-ea]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_20-ea]
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(Socket
SendBufferPool.java:203) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:202) ~[ne
tty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.jav
a:147) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServe
rSocketPipelineSink.java:99) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipe
lineSink.java:36) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:725) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:686) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:1153) ~[netty-3.6.6.Fi
nal.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1246) ~[netty-3.6.6.Final.jar:
na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:913) ~[netty-3.6.6.Final.jar:n
a]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3
.6.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[ne
tty-3.6.6.Final.jar:na]
        at io.gatling.recorder.http.ssl.FirstEventIsUnsecuredConnectSslHandler.handleUpstream(FirstEven
tIsUnsecuredConnectSslHandler.scala:31) ~[gatling-recorder-2.0.0-M3a.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.
jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar
:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[n
etty-3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-
3.6.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar
:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20-ea]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_20-ea]
```

**Comment by manthri11** [comment]
Hey Swapnil i am still having an issue with Gatling recorder i am not able to record the script from VPN connection.
I am able to record the scripts from home network using FF browser only.
Can you please let me know if you come across the same issue
