### ISSUE TITLE
Core: Upgrade to Scala 2.11

### ISSUE THREAD

**Issue by OlegYch** [gatling/gatling#2248]
Just wondering if this planned. Would be super neat.

**Comment by davividal** [comment]
Any updates on this? I just installed Scala 2.12.1 and tried to install gatling 2.2.3, but I'm getting Conflicting cross-version suffixes, and I'm wondering if this is the cause.

```
$ sbt update
[info] Loading project definition from /home/davi.vidal/tmp/teste/megaton-hammer/project
[info] Set current project to Api (in build file:/home/davi.vidal/tmp/teste/megaton-hammer/)
[info] Updating {file:/home/davi.vidal/tmp/teste/megaton-hammer/}root...
[info] Resolving jline#jline;2.14.1 ...
[info] Done updating.
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/davi.vidal/tmp/teste/megaton-hammer/}root:
[error]    org.scala-lang.modules:scala-xml _2.11, _2.12
[error]    org.scala-lang.modules:scala-parser-combinators _2.11, _2.12
java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-xml, org.scala-lang.modules:scala-parser-combinators
	at scala.sys.package$.error(package.scala:27)
	at sbt.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:46)
	at sbt.ConflictWarning$.apply(ConflictWarning.scala:32)
	at sbt.Classpaths$$anonfun$100.apply(Defaults.scala:1253)
	at sbt.Classpaths$$anonfun$100.apply(Defaults.scala:1250)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) Conflicting cross-version suffixes in: org.scala-lang.modules:scala-xml, org.scala-lang.modules:scala-parser-combinators
[error] Total time: 12 s, completed Feb 28, 2017 10:24:53 AM
```

**Comment by slandelle** [comment]
@davividal Please don't hijack unrelated issues. Gatling 2.2 is Scala 2.11 and you're trying to run Scala 2.12.

**Comment by davividal** [comment]
@slandelle sorry, I'm not trying to hijack issues. I'm just trying to understand if the issue I'm having is somewhat related to this.
I only asked it there was any update on this because it is nearly a 3 years old issue.

**Comment by slandelle** [comment]
@davividal Read again issue title, then read again the Scala version you're trying to use...

**Comment by davividal** [comment]
@slandelle sorry for asking. Feel free to delete my comments.
