### ISSUE TITLE
Core: Error log during shutdown when using maxDuration

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2351]
```
ERROR] [10/31/2014 16:36:50.944] [GatlingSystem-akka.actor.default-dispatcher-8] [ActorSystem(GatlingSystem)] exception while executing timer task
java.lang.IllegalStateException: cannot enqueue after timer shutdown
    at akka.actor.LightArrayRevolverScheduler.scheduleOnce(Scheduler.scala:277)
    at akka.actor.Scheduler$class.scheduleOnce(Scheduler.scala:117)
    at akka.actor.LightArrayRevolverScheduler.scheduleOnce(Scheduler.scala:182)
    at io.gatling.core.scenario.Scenario.io$gatling$core$scenario$Scenario$$batchSchedule$1(Scenario.scala:70)
    at io.gatling.core.scenario.Scenario$$anonfun$io$gatling$core$scenario$Scenario$$batchSchedule$1$2.apply$mcV$sp(Scenario.scala:78)
```

**Comment by DomingoExabeam** [comment]
I am having the same shutdown problem in version 0.4.0 using default settings. This is a blocker for me. Can you please take a look. 
My stack trace:
[INFO] [06/04/2015 08:16:47.028] [kamon-akka.actor.default-dispatcher-6] [akka://kamon/user/metrics] Message [akka.dispatch.sysmsg.DeathWatchNotification] from Actor[akka://kamon/user/metrics#1322890589] to Actor[akka://kamon/user/metrics#1322890589] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[ERROR] [06/04/2015 08:16:47.048] [kamon-akka.actor.default-dispatcher-6] [ActorSystem(kamon)] exception while executing timer task
java.lang.RuntimeException: Kamon has not been started yet.
	at scala.sys.package$.error(package.scala:27)
	at kamon.Kamon$.ifStarted(Kamon.scala:82)
	at kamon.Kamon$.metrics(Kamon.scala:65)
	at akka.kamon.instrumentation.DispatcherInstrumentation.afterLazyExecutorShutdown(DispatcherInstrumentation.scala:135)
	at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.shutdown(Dispatcher.scala:43)
	at akka.dispatch.Dispatcher.shutdown(Dispatcher.scala:106)
	at akka.dispatch.MessageDispatcher$$anon$2.run(AbstractDispatcher.scala:212)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(Scheduler.scala:476)
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:282)
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:281)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280)
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:688)
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:641)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:808)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:811)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:804)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:804)
	at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15)
	at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:804)
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:638)
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:638)
	at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:32)
	at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:44)
	at kamon.trace.Tracer$.withContext(TracerModule.scala:57)
	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:43)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:31)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by slandelle** [comment]
@DomingoExabeam Your issue is about Kamon and has nothing to do with Gatling :unamused:
