### ISSUE TITLE
 when I try to run [ Recorder.scala ] through eclipse i get folowing error

### ISSUE THREAD

**Issue by shahab-et** [gatling/gatling#2474]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.gatling.recorder.controller.RecorderController$.apply(RecorderController.scala:45)
	at io.gatling.recorder.GatlingRecorder$.fromMap(GatlingRecorder.scala:55)
	at Recorder$.delayedEndpoint$Recorder$1(Recorder.scala:9)
	at Recorder$delayedInit$body.apply(Recorder.scala:4)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Recorder$.main(Recorder.scala:4)
	at Recorder.main(Recorder.scala)
Caused by: com.typesafe.config.ConfigException$WrongType: gatling.conf: 14: Cannot concatenate object or list with a non-object-or-list, ConfigString("extract") and SimpleConfigObject({"css":{},"jsonPath":{},"regex":{},"xpath":{}}) are not compatible
	at com.typesafe.config.impl.ConfigConcatenation.join(ConfigConcatenation.java:116)
	at com.typesafe.config.impl.ConfigConcatenation.consolidate(ConfigConcatenation.java:153)
	at com.typesafe.config.impl.ConfigConcatenation.concatenate(ConfigConcatenation.java:161)
	at com.typesafe.config.impl.Parser$ParseContext.consolidateValueTokens(Parser.java:421)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:796)
	at com.typesafe.config.impl.Parser$ParseContext.parseValue(Parser.java:520)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:803)
	at com.typesafe.config.impl.Parser$ParseContext.parseValue(Parser.java:520)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:803)
	at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
	at com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:602)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:554)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:794)
	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:747)
	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:751)
	at io.gatling.core.config.GatlingConfiguration$.setUp(GatlingConfiguration.scala:88)
	at io.gatling.recorder.config.RecorderConfiguration$.<init>(RecorderConfiguration.scala:53)
	at io.gatling.recorder.config.RecorderConfiguration$.<clinit>(RecorderConfiguration.scala)
	... 13 more

**Comment by slandelle** [comment]
I'd say you've tried to manually migrate/upgrade a maven project generated with the archetype, and failed in the process. The Recorder uses a config file named `recorder.conf`, not `gatling.conf` (this is the one for the load test engine): https://github.com/gatling/gatling-maven/blob/master/gatling-highcharts-maven-archetype/src/main/scala/Recorder.scala#L11

**Comment by shahab-et** [comment]
I've Compared my version of Recorder.scala with the one you mentioned.
they are exactly the same.
Actually you are right,I might have changed some files manually.
Since I couldn't find a sample project to start with.
so if there is any template working project out there I'd appreciate if you give me the link.

Thanks for your time :)

**Comment by slandelle** [comment]
I told you you're loading `gatling.conf` while you should be loading `recorder.conf`! See https://github.com/gatling/gatling-maven/blob/master/gatling-highcharts-maven-archetype/src/main/scala/IDEPathHelper.scala#L21

**Comment by shahab-et** [comment]
The IDEPathHelper.scala  is calling recorder.conf
anywhere else should I check ?

**Comment by pdalpra** [comment]
Still, this part :

```
Caused by: com.typesafe.config.ConfigException$WrongType: gatling.conf: 14: Cannot concatenate object or list with a non-object-or-list, ConfigString("extract") and SimpleConfigObject({"css":{},"jsonPath":{},"regex":{},"xpath":{}}) are not compatible
```

states that the Recorder is trying to load `gatling.conf`.
If you created a new project using the Maven archetype, there is no chance this could happen…

**Comment by shahab-et** [comment]
Thanks pdalpra
I used this archType :
http://repository.excilys.com/content/groups/public/archetype-catalog.xml
to create my project, I'm not sure if that was the correct one!

**Comment by pdalpra** [comment]
Well, this means you're using 2.0.0-M3a at best, which is very outdated.
Please read the documentation, which describes how to create projects from archetype for newer versions.

**Comment by shahab-et** [comment]
Do you have any Maven Archetype Catalog URL containing  latest versions of gatling ?
I searched but didn't find.
I need a clean, working template project to start with (with the latest versions of gatling),if you could also help me on that , I would appreciate .

Thank you again

**Comment by pdalpra** [comment]
Latest versions are published on Central, which means no need for a specific catalog.
About the templates : you'll need to be a bit more specific than that. Maven Archetype, Maven Plugin, etc… ?
Also please switch to the mailing list, since Github's issue tracker is only for feature requests or bug reports.

**Comment by shahab-et** [comment]
Oops my Bad!
I promise not to do this again...
I'm new to (gatling,maven,scala,eclipse...also gitHub :-p) so please accept my apology. these days I'm having hard times !!!

- where is mailing list ?
- where should I ask questions about gatling ?
- I need a sample (working) project to start recording scenarios (I'm an ADF Developer with java background)

Thank you
