### ISSUE TITLE
Graphite: TcpSender shouldn't crash on unsupported message CommandFailed

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2490]
```
java.lang.IllegalArgumentException: Actor io.gatling.metrics.sender.TcpSender@5b715bc doesn't support message CommandFailed(Write(ByteString(103, 97, 116, 108, 105, 110, 103, 50, 46, 99, 105, 115, 46, 80, 114, 111, 118, 105, 100, 101, 80, 97, 115, 115, 101, 110, 103, 101, 114, 72, 97, 110, 100, 108, 105, 110, 103, 73, 110, 102, 111, 114, 109, 97, 116, 105, 111, 110, 95, 49, 65, 95, 118, 52, 95, 51, 46, 111, 107, 46, 112, 101, 114, 99, 101, 110, 116, 105, 108, 101, 115, 57, 53, 45, 48, 32, 52, 51, 32, 49, 52, 50, 48, 55, 50, 51, 57, 52, 50, 10),NoAck(null)))
        at io.gatling.core.akka.BaseActor.unhandled(BaseActor.scala:32)
        at akka.actor.Actor$$anonfun$aroundReceive$1.apply(Actor.scala:465)
        at akka.actor.Actor$$anonfun$aroundReceive$1.apply(Actor.scala:465)
        at io.gatling.metrics.sender.MetricsSender$$anonfun$connected$1.applyOrElse(MetricsSender.scala:41)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:22)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

We need an exception to trigger reconnection, but crashing on unsupported message and logging the full stracktrace looks wrong to me.

@pdalpra WDYT?

**Comment by pdalpra** [comment]
@slandelle Indeed.
TcpSender should throw an exception on `CommandFailed`, but this exception should not expose all those details…
Maybe we should use `scala.util.control.NoStacktrace` to hide the stacktrace ?

**Comment by slandelle** [comment]
Or maybe just not crash as you have the event. You could just become another "reconnecting" state.
Maybe also try FSM.

**Comment by pdalpra** [comment]
This would indeed be preferable :)
