### ISSUE TITLE
Recorder: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2492]
Reported on SOF: http://stackoverflow.com/questions/27780586/gatling-recorder-an-existing-connection-was-forcibly-closed-by-the-remote-host

```
C:\Users\Asheesh\Downloads\gatling-charts-highcharts-2.0.3\bin>Recorder.bat
GATLING_HOME is set to "C:\Users\Asheesh\Downloads\gatling-charts-highcharts-2.0.3"
Jan 05, 2015 6:48:49 PM org.jboss.netty.channel.SimpleChannelHandler
WARNING: EXCEPTION, please implement io.gatling.recorder.http.handler.remote.RemoteHandler.exceptionCaught() for proper handling.
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

* java version "1.7.0_72" Java(TM) SE Runtime Environment (build 1.7.0_72-b14) Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
* Gatling 2.1.2
* Windows 8.1
* Symantec Endpoint Protection enabled and disabled

**Comment by slandelle** [comment]
Could not reproduce.
