### ISSUE TITLE
Recorder: stacktrace when generating from HAR file

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2506]
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: No validator registered for component : scala.swing wrapper scala.swing.TextField$$anon$1[,0,0,734x29,invalid,layout=javax.swing.plaf.basic.BasicTextUI$UpdateHandler,alignmentX=0.0,alignmentY=0.0,border=com.apple.laf.AquaTextFieldBorder@3df313c5,flags=288,maximumSize=,minimumSize=,preferredSize=,caretColor=javax.swing.plaf.ColorUIResource[r=0,g=0,b=0],disabledTextColor=javax.swing.plaf.ColorUIResource[r=128,g=128,b=128],editable=true,margin=javax.swing.plaf.InsetsUIResource[top=0,left=0,bottom=0,right=0],selectedTextColor=com.apple.laf.AquaImageFactory$SystemColorProxy[r=0,g=0,b=0],selectionColor=com.apple.laf.AquaImageFactory$SystemColorProxy[r=164,g=205,b=255],columns=60,columnWidth=12,command=,horizontalAlignment=LEADING]
	at io.gatling.recorder.ui.swing.frame.ValidationHelper$.updateValidationStatus(ValidationHelper.scala:73)
	at io.gatling.recorder.ui.swing.frame.ConfigurationFrame$$anonfun$11.applyOrElse(ConfigurationFrame.scala:443)
	at io.gatling.recorder.ui.swing.frame.ConfigurationFrame$$anonfun$11.applyOrElse(ConfigurationFrame.scala:441)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.swing.Reactions$Impl$$anonfun$apply$1.apply(Reactions.scala:23)
	at scala.swing.Reactions$Impl$$anonfun$apply$1.apply(Reactions.scala:23)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.swing.Reactions$Impl.apply(Reactions.scala:23)
	at scala.swing.Reactions$Impl.apply(Reactions.scala:17)
	at scala.swing.Publisher$$anonfun$publish$1.apply(Publisher.scala:47)
	at scala.swing.Publisher$$anonfun$publish$1.apply(Publisher.scala:47)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.swing.SingleRefCollection$$anon$4.foreach(Publisher.scala:108)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.swing.RefSet.foreach(Publisher.scala:165)
	at scala.swing.Publisher$class.publish(Publisher.scala:47)
	at scala.swing.Window.publish(Window.scala:22)
	at io.gatling.recorder.ui.swing.component.DisplayedSelectionFileChooser.io$gatling$recorder$ui$swing$component$DisplayedSelectionFileChooser$$setAndPublish(DisplayedSelectionFileChooser.scala:65)
	at io.gatling.recorder.ui.swing.component.DisplayedSelectionFileChooser$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(DisplayedSelectionFileChooser.scala:47)
	at io.gatling.recorder.ui.swing.component.DisplayedSelectionFileChooser$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(DisplayedSelectionFileChooser.scala:47)
	at scala.Option.foreach(Option.scala:256)
	at io.gatling.recorder.ui.swing.component.DisplayedSelectionFileChooser$$anonfun$1.apply$mcV$sp(DisplayedSelectionFileChooser.scala:47)
	at scala.swing.Action$$anon$2.apply(Action.scala:60)
	at scala.swing.Action$$anon$1.actionPerformed(Action.scala:78)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by slandelle** [comment]
Nice!

**Comment by pdalpra** [comment]
This, in the process, add validation for the har file path, which should at least have a value when on "HAR Converter" mode ;)
