### ISSUE TITLE
HTTP: Empty domain in the response headers: String index out of range

### ISSUE THREAD

**Issue by FVANtom** [gatling/gatling#2520]
We have encountered a bug with Gatling seemingly to do with an empty domain in the response headers.

Below is an example of the expected result (cookie being set) when requesting the following page
GET http://domainname.com/rest/auth/product/oauthLogin?code=98334ceb2e1f3e98aad3382b1fe71e33

```
Redirect
To:http://domainname.com/#/dashboard with status: 302 Show explanation HTTP/1.1 302 Found
Redirection information has not been cached.
Via: 1.1 MLMSCHISA1 
Connection: Keep-Alive
Proxy-Connection: Keep-Alive
Content-Length: 0 
Date: Mon, 19 Jan 2015 16:56:57 GMT 
Location: /#/dashboard 
Server: nginx/1.4.6 (Ubuntu) 
Set-Cookie: sessionid=OTY4ZDllNTgtYjU3OC00MWRjLTkzMWMtNGUwNzk4MTY0MTUw;Domain=;Path=/
Set-Cookie: xsrf-token=MTc0NjA5NWExMmE3ZjlhYjExOTc4YzhmYjU3MDdiMTU2MzJhMDVjYw==;Domain=;Path=/
Set-Cookie: userrole=c3R1ZGVudA==;Domain=;Path=/ 
x-powered-by: yoke

Status
200 OK Show explanation Loading time: 194

Request headers 
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Content-Type: text/plain; charset=utf-8 
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,nl;q=0.6
Cookie: _ga=GA1.2.1343374485.1416404057; sessionid=OTY4ZDllNTgtYjU3OC00MWRjLTkzMWMtNGUwNzk4MTY0MTUw; xsrf-token=MTc0NjA5NWExMmE3ZjlhYjExOTc4YzhmYjU3MDdiMTU2MzJhMDVjYw==; userrole=c3R1ZGVudA==

Response headers 
Via: 1.1 MLMSCHISA1 
Content-Length: 645 
Date: Mon, 19 Jan 2015 16:50:15 GMT 
Content-Type: text/html 
ETag: "54bd03ce-285" 
Server: nginx/1.4.6 (Ubuntu) 
Accept-Ranges: bytes 
Last-Modified: Mon, 19 Jan 2015 13:17:02 GMT 
```

However when I try to do this in Gatling via this code:
```
import io.gatling.core.Predef._
import io.gatling.http.Predef._

class LoginSimulation extends Simulation {

	val httpProtocol = http
		.baseURL("http://domainname.com")
		.acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-GB,en;q=0.5")
		.connection("keep-alive")
		.contentTypeHeader("application/x-www-form-urlencoded")
		.userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0")

	val headers_1 = Map("Accept" -> "application/json, text/plain, */*")

	val uri1 = "http://domainname.com"

	val scn = scenario("LoginSimulation")
		.exec(http("request_3c")
		.get(uri1 + "/rest/auth/product/oauthLogin?code=98334ceb2e1f3e98aad3382b1fe71e33"))

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
```

I get the following error:
```
[ERROR] [01/19/2015 18:08:38.551] [GatlingSystem-akka.actor.default-dispatcher-3] [akka://GatlingSystem/user/asyncHandler] String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646)
	at io.gatling.http.cookie.CookieJar$.cookieDomain(CookieJar.scala:44)
	at io.gatling.http.cookie.CookieJar$$anonfun$1.apply(CookieJar.scala:106)
	at io.gatling.http.cookie.CookieJar$$anonfun$1.apply(CookieJar.scala:104)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at io.gatling.http.cookie.CookieJar.add(CookieJar.scala:103)
	at io.gatling.http.cookie.CookieJar.add(CookieJar.scala:98)
	at io.gatling.http.cookie.CookieHandling$.storeCookies(CookieHandling.scala:46)
	at io.gatling.http.ahc.AsyncHandlerActor$$anonfun$1.apply(AsyncHandlerActor.scala:309)
	at io.gatling.http.ahc.AsyncHandlerActor$$anonfun$1.apply(AsyncHandlerActor.scala:309)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at io.gatling.http.ahc.AsyncHandlerActor.redirect$1(AsyncHandlerActor.scala:263)
	at io.gatling.http.ahc.AsyncHandlerActor.io$gatling$http$ahc$AsyncHandlerActor$$processResponse(AsyncHandlerActor.scala:315)
	at io.gatling.http.ahc.AsyncHandlerActor$$anonfun$receive$1.applyOrElse(AsyncHandlerActor.scala:97)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

18:08:38.559 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.559 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.559 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.560 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on unknown message None, dropping
18:08:38.570 [ERROR] i.g.h.a.AsyncHandlerActor - AsyncHandlerActor crashed on message Some(OnCompleted(HttpTx(Session(LoginAsPupilSimulation,8090926743097525160-0,Map(),1421687318247,0,OK,List(),<function1>),HttpRequest(request_3c,http://domainname.com/rest/auth/product/oauthLogin?code=98334ceb2e1f3e98aad3382b1fe71e33	GET	headers:	Connection:keep-alive	Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8	Content-Type:application/x-www-form-urlencoded	Accept-Language:en-GB,en;q=0.5	Accept-Encoding:gzip, deflate	User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0,HttpRequestConfig(List(HttpCheck(CheckBase(<function1>,<function1>,<function1>,None),Status,None)),None,None,None,false,None,true,true,HttpProtocol(List(http://domainname.com),Some(http://gatling.io),HttpProtocolEnginePart(true,false,6,None,None),HttpProtocolRequestPart(Map(Connection -> <function1>, Accept -> <function1>, Content-Type -> <function1>, Accept-Language -> <function1>, Accept-Encoding -> <function1>, User-Agent -> <function1>),None,true,true,false,None,false,None),HttpProtocolResponsePart(true,None,false,true,None,List(),None,false,None),HttpProtocolWsPart(List(),false,None),HttpProtocolProxyPart(None,List())),List())),<function1>,Actor[akka://GatlingSystem/user/userEnd#845927357],true,0,<function1>),HttpResponse(http://domainname.com/rest/auth/product/oauthLogin?code=98334ceb2e1f3e98aad3382b1fe71e33	GET	headers:	Connection:keep-alive	Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8	Content-Type:application/x-www-form-urlencoded	Accept-Language:en-GB,en;q=0.5	Accept-Encoding:gzip, deflate	User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0,Some(com.ning.http.client.providers.netty.request.NettyRequest@e0bae43),Some(com.ning.http.client.providers.netty.response.NettyResponseStatus@43715497),"Date=Mon, 19 Jan 2015 17:08:35 GMT"; "Location=/#/dashboard"; "Server=nginx/1.4.6 (Ubuntu)"; "Set-Cookie=sessionid=Njg3MjRhNDQtYjFlNC00MDFhLTk1MTUtZmU3MTZlYzBkYTQ4;Domain=;Path=/, xsrf-token=MTQ1NzI0NTkyMGY5ZmQyYjM4NjEyODVjOTNjODc0OGY4M2U5ZTMxYQ==;Domain=;Path=/, userrole=c3R1ZGVudA==;Domain=;Path=/"; "x-powered-by=yoke"; "Content-Length=0"; "Connection=keep-alive",NoResponseBody,Map(),0,UTF-8,1421687318296,1421687318398,1421687318517,1421687318517))), forwarding user to the next action
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646) ~[na:1.8.0_25]
	at io.gatling.http.cookie.CookieJar$.cookieDomain(CookieJar.scala:44) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.cookie.CookieJar$$anonfun$1.apply(CookieJar.scala:106) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.cookie.CookieJar$$anonfun$1.apply(CookieJar.scala:104) ~[gatling-http-2.1.3.jar:2.1.3]
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124) ~[scala-library-2.11.5.jar:na]
	at scala.collection.immutable.List.foldLeft(List.scala:84) ~[scala-library-2.11.5.jar:na]
	at io.gatling.http.cookie.CookieJar.add(CookieJar.scala:103) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.cookie.CookieJar.add(CookieJar.scala:98) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.cookie.CookieHandling$.storeCookies(CookieHandling.scala:46) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.ahc.AsyncHandlerActor$$anonfun$1.apply(AsyncHandlerActor.scala:309) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.ahc.AsyncHandlerActor$$anonfun$1.apply(AsyncHandlerActor.scala:309) ~[gatling-http-2.1.3.jar:2.1.3]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55) ~[scala-library-2.11.5.jar:na]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55) ~[scala-library-2.11.5.jar:na]
	at io.gatling.http.ahc.AsyncHandlerActor.redirect$1(AsyncHandlerActor.scala:263) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.ahc.AsyncHandlerActor.io$gatling$http$ahc$AsyncHandlerActor$$processResponse(AsyncHandlerActor.scala:315) ~[gatling-http-2.1.3.jar:2.1.3]
	at io.gatling.http.ahc.AsyncHandlerActor$$anonfun$receive$1.applyOrElse(AsyncHandlerActor.scala:97) ~[gatling-http-2.1.3.jar:2.1.3]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.8.jar:na]
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:22) ~[gatling-core-2.1.3.jar:2.1.3]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.8.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.8.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.11-2.3.8.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.11-2.3.8.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.11-2.3.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.5.jar:na]
```

Anyone able to help me with this? Thanks a lot in advance!

**Comment by slandelle** [comment]
Your cookie is invalid, a Set-Cookie header Domain attribute shouldn't be empty, see [RFC6265](http://tools.ietf.org/html/rfc6265#section-5.2.3).

The correct behavior should be that Gatling ignores this cookie, instead of crashing a `StringIndexOutOfBoundsException`.

Yet, your application doesn't properly craft Set-Cookie headers. Do you craft them manually? Or do you use a specific framework? FYI, you're the first one to ever meet this issue.

**Comment by FVANtom** [comment]
Thanks for the quick response Stephane. It was indeed caused by a bug in our cookie creation classes. Either way the StringIndexOutOfBoundsException shouldn't be thrown in Gatling like you said. Maybe it is a good idea though to add a debug logging message saying those cookies are ignored because of invalid domain. It might save someone a lot of time in the future :)

I've fixed our code as well and all works fine now. Thanks a lot for the excellent tool and support.

**Comment by slandelle** [comment]
Actually, I was wrong: see http://tools.ietf.org/html/rfc6265#section-4.1.2.3.
If the Domain is missing, the user agent will return the cookie only to the origin server (i.e. only for the exact hostname). Will fix!

**Comment by slandelle** [comment]
See https://github.com/AsyncHttpClient/async-http-client/issues/806

**Comment by slandelle** [comment]
Fix, thanks for reporting!
