### ISSUE TITLE
Run from compiled jar

### ISSUE THREAD

**Issue by Elufimov** [gatling/gatling#2782]
Hi!
Right now I came across a task of creating full bundle of ours load tests. I apply sbt-assembly and gets normal zip file with:
bin/
....run.bat
....run.sh
conf/
....gatling.conf
lib/
...all dependencies main artifact and test artifact.
run.bat and run.sh i took from off gatling bundle http://gatling.io/#/download and comment compile section. When i  run `sh run.sh -s MySimulation` i get
```
GATLING_HOME is set to /somePath
Exception in thread "main" java.nio.file.NoSuchFileException: /somePath/target/test-classes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at io.gatling.core.util.PathHelper$RichPath$.deepListAux$1(PathHelper.scala:99)
        at io.gatling.core.util.PathHelper$RichPath$.deepList$extension(PathHelper.scala:105)
        at io.gatling.core.util.PathHelper$RichPath$.deepFiles$extension(PathHelper.scala)
        at io.gatling.app.classloader.SimulationClassLoader.simulationClasses(SimulationClassLoader.scala:55)
        at io.gatling.app.Gatling.loadSimulations(Gatling.scala:92)
        at io.gatling.app.Gatling.start(Gatling.scala:70)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:59)
        at io.gatling.app.Gatling$.main(Gatling.scala:44)
        at io.gatling.app.Gatling.main(Gatling.scala)
```
As i see gatling try obtain simulation from target/test-classes which was to be created by zinc.  I solve this problem by adding custom task to build 

``` scala
val aggregateSimulationClassFiles = taskKey[Seq[File]]("All simulation *.class files.")

aggregateSimulationClassFiles := {
  val dir = (classDirectory in Test).value
  ((dir ** "*.class") filter { !_.isDirectory }).get
}

mappings in Universal ++= aggregateSimulationClassFiles.value.map { file =>
  file -> file.getAbsolutePath.replace(baseDirectory.value.absolutePath, "")
}
```
And now everything is fine. But i wondering is any other way to do this?

**Comment by slandelle** [comment]
This is not an issue related to supported deployments.
Please use the Google Groups.
