### ISSUE TITLE
Fix PaceSpec

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2818]
```
[info] PaceSpec:
[info] pace
[info] - should run actions with a minimum wait time *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (2 seconds) during expectMsgClass waiting for class io.gatling.core.session.Session
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:423)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass(TestKit.scala:419)
[info]   at akka.testkit.TestKit.expectMsgClass(TestKit.scala:718)
[info]   at io.gatling.core.action.PaceSpec$$anonfun$1.apply$mcV$sp(PaceSpec.scala:37)
[info]   at io.gatling.core.action.PaceSpec$$anonfun$1.apply(PaceSpec.scala:27)
[info]   at io.gatling.core.action.PaceSpec$$anonfun$1.apply(PaceSpec.scala:27)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] - should run actions immediately if the minimum time has expired *** FAILED ***
[info]   1442840771738 was not equal to 1442840769587 (PaceSpec.scala:58)
```

**Comment by pdalpra** [comment]
Really seems to be a timing issue on CI...
A workaround could be to set a higher [time factor](http://doc.akka.io/docs/akka/snapshot/scala/testing.html#Accounting_for_Slow_Test_Systems), but that's only a small hack :/

**Comment by slandelle** [comment]
Let's do that, then...

**Comment by pdalpra** [comment]
This won't fix it as you'll need to change the `akka.test.timefactor` configuration key (which defaults to one).
Durations are already dilated in `expectMsg(...)` and `expectNoMsg(...)`.

**Comment by slandelle** [comment]
Should be fine, now.

**Comment by slandelle** [comment]
Thanks :)
