### ISSUE TITLE
Report NoSuchElementException when grouping in a randomSwitch

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2846]
2.2.0-SNAPSHOT 

The simulation compiles and runs when grouping on a randomSwitch
```scala
 val homepage = scenario("Homepage")
    .randomSwitch(
      50.0 -> group("Homepage, non-signed in") { Homepage.nonSignedIn },
      50.0 -> group("Homepage, signed in") { Homepage.signedIn }
    )
```

However the parsing of the report generates a java.util.NoSuchElementException:

```
Parsing log file(s) done
Generating reports...
[error] java.util.NoSuchElementException: key not found: List(Homepage)
[error]         at scala.collection.MapLike$class.default(MapLike.scala:228)
[error]         at scala.collection.AbstractMap.default(Map.scala:59)
[error]         at scala.collection.MapLike$class.apply(MapLike.scala:141)
[error]         at scala.collection.AbstractMap.apply(Map.scala:59)
[error]         at io.gatling.charts.report.StatsReportGenerator.io$gatling$charts$report$StatsReportGenerator$$addGroupsRec$1(StatsReportGenerator.scala:120)
[error]         at io.gatling.charts.report.StatsReportGenerator.io$gatling$charts$report$StatsReportGenerator$$addGroupsRec$1(StatsReportGenerator.scala:116)
[error]         at io.gatling.charts.report.StatsReportGenerator$$anonfun$generate$1$$anonfun$apply$1.apply(StatsReportGenerator.scala:130)
[error]         at io.gatling.charts.report.StatsReportGenerator$$anonfun$generate$1$$anonfun$apply$1.apply(StatsReportGenerator.scala:129)
[error]         at scala.Option.foreach(Option.scala:257)
[error]         at io.gatling.charts.report.StatsReportGenerator$$anonfun$generate$1.apply(StatsReportGenerator.scala:129)
[error]         at io.gatling.charts.report.StatsReportGenerator$$anonfun$generate$1.apply(StatsReportGenerator.scala:127)
[error]         at scala.collection.immutable.List.foreach(List.scala:381)
[error]         at io.gatling.charts.report.StatsReportGenerator.generate(StatsReportGenerator.scala:127)
[error]         at io.gatling.charts.report.ReportsGenerator.generateStats$1(ReportsGenerator.scala:38)
[error]         at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:62)
[error]         at io.gatling.app.LogFileProcessor.generateReports(RunResultProcessor.scala:63)
[error]         at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:42)
[error]         at io.gatling.app.Gatling.start(Gatling.scala:61)
[error]         at io.gatling.app.Gatling$.start(Gatling.scala:51)
[error]         at io.gatling.app.Gatling$.fromArgs(Gatling.scala:43)
[error]         at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
[error]         at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
[error]         at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[error]         at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] Simulation WeatherWatchersSim failed.
[info] Simulation(s) execution ended.
```

**Comment by slandelle** [comment]
Don't use a comma in group names, as it's used as a separator between nested groups in the log file.
As group names are dynamic, we can't afford the overhead of parsing them at runtime (over and over again).
I'll document it.
