### ISSUE TITLE
Core: Utf8ByteBuffersDecoder state is not properly reset between decode calls

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#2981]

**Comment by kmumahesh** [comment]
Hi Stephane,

I encountered "java.nio.charset.CharacterCodingException: null" today and stumbled across the conversation in google group where I've asked for the same clarification. I was using 2.2.0 release but tried 2.2.1 snapshot as well. I see that the error occurs only for requests fetching PNG files but not JS files (I just checked these two types only). I've given below a simple reproducer which I tested and got the below error. Please try and let me know if you are able to reproduce. And if possible a quick fix too please :) Not sure if this is significant, but my JDK version is 1.8.0_65 and been running gatling from Windows 7.

**Reproducer**
```
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class test extends Simulation {

	val httpProtocol = http
	        .baseURL("http://gatling.io")
		.disableAutoReferer
		.acceptHeader("image/webp,image/*,*/*;q=0.8")
		.acceptEncodingHeader("gzip, deflate, sdch")
		.acceptLanguageHeader("en-US,en;q=0.8")
		.userAgentHeader("Gatling (Linux) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36")
        //.contentTypeHeader("application/x-www-form-urlencoded;charset=UTF-8")
        .maxConnectionsPerHostLikeChrome

	val headers_12 = Map(
        //"Accept" -> "image/webp,image/*,*/*;q=0.8",
		"Connection" -> "keep-alive",
		"Referer" -> "http://gatling.io")

    val scn = scenario("test")
    .exec(http("request_12")
    .get("/images/logo-gilt.png")
	.headers(headers_12))
    
    setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}

```
**Error - On Console**
```
Simulation test completed in 0 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...
Exception in thread "main" java.lang.UnsupportedOperationException: There were no requests sent during the simulation, reports won't be generated
        at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:48)
        at io.gatling.app.LogFileProcessor.generateReports(RunResultProcessor.scala:64)
        at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:43)
        at io.gatling.app.Gatling.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.start(Gatling.scala:57)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
        at io.gatling.app.Gatling$.main(Gatling.scala:43)
        at io.gatling.app.Gatling.main(Gatling.scala)
```

**Error - In log file** (I'm using file appender in logback.conf)
```
23:38:10.313 [ERROR] i.g.h.a.ResponseProcessor - ResponseProcessor crashed on session=Session(test,1,Map(gatling.http.cache.dns -> io.gatling.http.resolver.ShuffleJdkNameResolver@2a6b2d9d),1463249290201,0,OK,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$157/961859592@50504422) request=request_12: http://gatling.io/images/logo-gilt.png	GET	headers:	Referer:http://gatling.io	Connection:keep-alive	Accept:image/webp,image/*,*/*;q=0.8	Accept-Language:en-US,en;q=0.8	Accept-Encoding:gzip, deflate, sdch	User-Agent:Gatling (Linux) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 resourceFetcher=None redirectCount=0, forwarding user to the next action
java.nio.charset.CharacterCodingException: null
	at io.gatling.http.util.Utf8ByteBuffersDecoder.write(ByteBuffersDecoder.scala:135)
	at io.gatling.http.util.Utf8ByteBuffersDecoder.io$gatling$http$util$Utf8ByteBuffersDecoder$$$anonfun$6(ByteBuffersDecoder.scala:147)
	at io.gatling.http.util.Utf8ByteBuffersDecoder.io$gatling$http$util$Utf8ByteBuffersDecoder$$$anonfun$6$adapted(ByteBuffersDecoder.scala:145)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.gatling.http.util.Utf8ByteBuffersDecoder.decode(ByteBuffersDecoder.scala:145)
	at io.gatling.http.util.ByteBuffersDecoder$.decode(ByteBuffersDecoder.scala:52)
	at io.gatling.http.util.BytesHelper$.byteArraysToString(BytesHelper.scala:61)
	at io.gatling.http.response.InputStreamResponseBody.liftedTree1$1(ResponseBody.scala:125)
	at io.gatling.http.response.InputStreamResponseBody.string$lzycompute(ResponseBody.scala:124)
	at io.gatling.http.response.InputStreamResponseBody.string(ResponseBody.scala:120)
	at io.gatling.http.util.package$HttpStringBuilder$.io$gatling$http$util$package$HttpStringBuilder$$$anonfun$7(package.scala:168)
	at scala.Option.foreach(Option.scala:257)
	at io.gatling.http.util.package$HttpStringBuilder$.appendResponse$extension(package.scala:159)
	at io.gatling.http.ahc.ResponseProcessor.dump$1(ResponseProcessor.scala:92)
	at io.gatling.http.ahc.ResponseProcessor.logRequest(ResponseProcessor.scala:101)
	at io.gatling.http.ahc.ResponseProcessor.logAndExecuteNext(ResponseProcessor.scala:168)
	at io.gatling.http.ahc.ResponseProcessor.checkAndProceed$1(ResponseProcessor.scala:291)
	at io.gatling.http.ahc.ResponseProcessor.processResponse(ResponseProcessor.scala:321)
	at io.gatling.http.ahc.ResponseProcessor.onCompleted(ResponseProcessor.scala:61)
	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:121)
	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:46)
	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
	at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```
