### ISSUE TITLE
SSL issue when closing connections

### ISSUE THREAD

**Issue by JMVM** [gatling/gatling#3009]
Hi there,

Running test, since our site is with HTTPS protocol, we are getting the next SSL issue when closing connections:

**25587 [New I/O worker #7] DEBUG o.j.netty.handler.ssl.SslHandler - Failed to clean up SSLEngine.
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
       at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_65]
       at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_65]
       at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_65]
       at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1561) ~[na:1.8.0_65]
       at org.jboss.netty.handler.ssl.SslHandler.closeEngine(SslHandler.java:592) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.handler.ssl.SslHandler.channelDisconnected(SslHandler.java:584) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:360) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.1.Final.jar:na]
       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.1.Final.jar:na]
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
25589 [New I/O worker #7] DEBUG c.n.h.c.p.netty.handler.Processor - Channel Closed: [id: 0x21f8243d**

However, using **Fiddler as proxy**, and configured or not in Gatling code, this issue is not happening.

So is this one a certification issue? Does it have impact to performance test (response times, etc.)? If not, can we consider as a kind of warning message?

Thanks

**Comment by slandelle** [comment]
It's only logged when debug level is enabled, and IIRC, is no longer logged in modern Netty versions which Gatling 2.2 uses. Just ignore them.
