### ISSUE TITLE
Cannot set gatling.data.writers from system property

### ISSUE THREAD

**Issue by vas78** [gatling/gatling#3055]
This seems to be similar to #1099, reproduced with 2.2.1: just start Gatling with "-Dgatling.data.writers=[console]"

```
Exception in thread "main" com.typesafe.config.ConfigException$WrongType: system properties: gatling.data.writers has type STRING rather than LIST
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:159)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:252)
        at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:323)
        at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:381)
        at io.gatling.core.config.GatlingConfiguration$.mapToGatlingConfig(GatlingConfiguration.scala:212)
        at io.gatling.core.config.GatlingConfiguration$.load(GatlingConfiguration.scala:98)
        at io.gatling.app.Gatling$.start(Gatling.scala:55)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
        at io.gatling.app.Gatling$.main(Gatling.scala:43)
        at io.gatling.app.Gatling.main(Gatling.scala)
```

**Comment by slandelle** [comment]
See https://github.com/typesafehub/config/issues/69 for passing a list from System props.

**Comment by vas78** [comment]
Got it, thanks!
For the sake of completeness, here`s the right way to do that: "-Dgatling.data.writers.0=console".
