### ISSUE TITLE
HTTP: Brotly-encoded responses cause CharacterCodingException

### ISSUE THREAD

**Issue by weirdan** [gatling/gatling#3070]
**Gatling version**: 2.2.2

**Reproducer**:
```scala
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._

class UtfSimulation extends Simulation {
	val httpProtocol = http
		.acceptHeader("application/json, text/javascript, */*; q=0.01")
		.acceptEncodingHeader("gzip, deflate, br")
		.acceptLanguageHeader("en-US,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0")

    val headers_1 = Map("Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
    val chain = exec(
      http("index").get("http://gatling.io/")
        .resources(
          http("google-font").get("http://fonts.googleapis.com/css?family=Lato:100,300,regular,700,900%7COpen+Sans:300%7CIndie+Flower:regular%7COswald:300,regular,700&subset=latin%2Clatin-ext")
        )
    )

	val scn = scenario("UtfSimulation").exec(chain)

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}
```
If `br` (which stands for [Brotly encoding](https://en.wikipedia.org/wiki/Brotli) ([github repo](https://github.com/google/brotli))) is removed from Accept-Encoding header everything works fine. If, however, if it **is** specified, the following exception is generated:
```
14:38:14.665 [DEBUG] i.g.h.f.ResourceFetcherActor - Fetching resource http://fonts.googleapis.com/css?family=Lato:100,300,regular,700,900%7COpen+Sans:300%7CIndie+Flower:regular%7COswald:300,regular,700&subset=latin%2Clatin-ext
14:38:14.666 [DEBUG] i.g.h.a.s.HttpTx$ - Sending request=google-font uri=http://fonts.googleapis.com/css?family=Lato:100,300,regular,700,900%7COpen+Sans:300%7CIndie+Flower:regular%7COswald:300,regular,700&subset=latin%2Clatin-ext: scenario=UtfSimulation, userId=1
14:38:14.718 [DEBUG] o.a.n.c.NettyConnectListener - Using non-cached Channel [id: 0x1a261cb7, L:/192.168.10.123:60234 - R:fonts.googleapis.com/173.194.222.95:80] for GET '/css?family=Lato:100,300,regular,700,900%7COpen+Sans:300%7CIndie+Flower:regular%7COswald:300,regular,700&subset=latin%2Clatin-ext'
14:38:14.770 [DEBUG] o.a.n.h.HttpHandler - 

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledUnsafeHeapByteBuf(freed))
GET /css?family=Lato:100,300,regular,700,900%7COpen+Sans:300%7CIndie+Flower:regular%7COswald:300,regular,700&subset=latin%2Clatin-ext HTTP/1.1
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Referer: http://gatling.io/
Host: fonts.googleapis.com

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Content-Type: text/css; charset=utf-8
Access-Control-Allow-Origin: *
Timing-Allow-Origin: *
Content-Encoding: br
Content-Length: 1132
Expires: Fri, 01 Jul 2016 11:38:14 GMT
Date: Fri, 01 Jul 2016 11:38:14 GMT
Cache-Control: private, max-age=86400
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE

14:38:14.771 [DEBUG] o.a.n.c.ChannelManager - Adding key: ChannelPoolKey(1,RemoteServerKey(http,fonts.googleapis.com,80)) for channel [id: 0x1a261cb7, L:/192.168.10.123:60234 - R:fonts.googleapis.com/173.194.222.95:80]
14:38:14.784 [ERROR] i.g.h.a.ResponseProcessor - ResponseProcessor crashed on session=Session(UtfSimulation,1,Map(gatling.http.cache.dns -> io.gatling.http.resolver.ShuffleJdkNameResolver@63d750c5, gatling.http.referer -> http://gatling.io/, gatling.http.cache.contentCache -> io.gatling.core.util.cache.Cache@763cda5c),1467373094327,0,OK,List(),<function1>) request=google-font: http://fonts.googleapis.com/css?family=Lato:100,300,regular,700,900%7COpen+Sans:300%7CIndie+Flower:regular%7COswald:300,regular,700&subset=latin%2Clatin-ext	GET	headers:	Accept:application/json, text/javascript, */*; q=0.01	Accept-Encoding:gzip, deflate, br	Accept-Language:en-US,en;q=0.5	User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0	Referer:http://gatling.io/ resourceFetcher=Some(Actor[akka://GatlingSystem/user/resourceFetcher-2#1462528391]) redirectCount=0, forwarding user to the next action
java.nio.charset.CharacterCodingException: null
	at io.gatling.http.util.Utf8ByteBuffersDecoder.write(ByteBuffersDecoder.scala:135)
	at io.gatling.http.util.Utf8ByteBuffersDecoder.io$gatling$http$util$Utf8ByteBuffersDecoder$$$anonfun$6(ByteBuffersDecoder.scala:147)
	at io.gatling.http.util.Utf8ByteBuffersDecoder$lambda$$decode$1.apply(ByteBuffersDecoder.scala:145)
	at io.gatling.http.util.Utf8ByteBuffersDecoder$lambda$$decode$1.apply(ByteBuffersDecoder.scala:145)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.gatling.http.util.Utf8ByteBuffersDecoder.decode(ByteBuffersDecoder.scala:145)
	at io.gatling.http.util.ByteBuffersDecoder$.decode(ByteBuffersDecoder.scala:52)
	at io.gatling.http.util.BytesHelper$.byteArraysToString(BytesHelper.scala:61)
	at io.gatling.http.response.InputStreamResponseBody.liftedTree1$1(ResponseBody.scala:125)
	at io.gatling.http.response.InputStreamResponseBody.string$lzycompute(ResponseBody.scala:124)
	at io.gatling.http.response.InputStreamResponseBody.string(ResponseBody.scala:120)
	at io.gatling.http.ahc.ResponseProcessor.executeNext(ResponseProcessor.scala:152)
	at io.gatling.http.ahc.ResponseProcessor.logAndExecuteNext(ResponseProcessor.scala:170)
	at io.gatling.http.ahc.ResponseProcessor.checkAndProceed$1(ResponseProcessor.scala:292)
	at io.gatling.http.ahc.ResponseProcessor.processResponse(ResponseProcessor.scala:322)
	at io.gatling.http.ahc.ResponseProcessor.onCompleted(ResponseProcessor.scala:61)
	at io.gatling.http.ahc.AsyncHandler.io$gatling$http$ahc$AsyncHandler$$$anonfun$1(AsyncHandler.scala:133)
	at io.gatling.http.ahc.AsyncHandler$lambda$$onCompleted$1.apply(AsyncHandler.scala:131)
	at io.gatling.http.ahc.AsyncHandler$lambda$$onCompleted$1.apply(AsyncHandler.scala:131)
	at io.gatling.http.ahc.AsyncHandler.withResponse(AsyncHandler.scala:124)
	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:131)
	at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:47)
	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
	at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by slandelle** [comment]
Netty doesn't support Brotly yet, only gzip and deflate.
I guess it's just bypassing the Inflater, so we end up trying to decode the compressed bytes.

We could possibly 

We could filter it out of the `Accept-Encoding` header at runtime.

**Comment by slandelle** [comment]
See https://github.com/AsyncHttpClient/async-http-client/issues/1202
