### ISSUE TITLE
Reports: ArrayIndexOutOfBoundsException in SessionDeltaBuffer.addEnd

### ISSUE THREAD

**Issue by swachter** [gatling/gatling#3073]
Used Gatling version: 2.2.0

The simulation is configured to run 2700 seconds:

```
setUp(
...
  )
      .maxDuration(2700)
```

After the simulation was finished 

```
================================================================================
2016-07-05 09:07:36                                        2700s elapsed
---- normal load scenario ------------------------------------------------------
...
```

the following message is output:

```
Simulation test.gatling.LongRunningSimulation completed in 2700 seconds
Parsing log file(s)...
```

and exception raised:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2700
	at io.gatling.charts.stats.buffers.SessionDeltaBuffer.addEnd(SessionDeltaPerSecBuffers.scala:45)
	at io.gatling.charts.stats.buffers.SessionDeltaPerSecBuffers$class.io$gatling$charts$stats$buffers$SessionDeltaPerSecBuffers$class$$$anonfun$10(SessionDeltaPerSecBuffers.scala:98)
	at io.gatling.charts.stats.buffers.SessionDeltaPerSecBuffers$class.io$gatling$charts$stats$buffers$SessionDeltaPerSecBuffers$class$$$anonfun$10$adapted(SessionDeltaPerSecBuffers.scala:97)
	at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
	at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:108)
	at io.gatling.charts.stats.buffers.SessionDeltaPerSecBuffers$class.endOrphanUserRecords(SessionDeltaPerSecBuffers.scala:97)
	at io.gatling.charts.stats.ResultsHolder.endOrphanUserRecords(ResultsHolder.scala:21)
	at io.gatling.charts.stats.LogFileReader.secondPass(LogFileReader.scala:158)
	at io.gatling.charts.stats.LogFileReader.io$gatling$charts$stats$LogFileReader$$$anonfun$11(LogFileReader.scala:165)
	at io.gatling.charts.stats.LogFileReader.parseInputFiles(LogFileReader.scala:63)
	at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:165)
	at io.gatling.app.LogFileProcessor.initLogFileReader(RunResultProcessor.scala:55)
	at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:37)
	at io.gatling.app.Gatling.start(Gatling.scala:66)
	at io.gatling.app.Gatling$.start(Gatling.scala:57)
	at io.gatling.app.Gatling$.fromMap(Gatling.scala:45)
	at Engine$.delayedEndpoint$Engine$1(Engine.scala:17)
	at Engine$delayedInit$body.apply(Engine.scala:5)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Engine$.main(Engine.scala:5)
	at Engine.main(Engine.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by slandelle** [comment]
Could you please provide your simulation.log file?

**Comment by danoliv** [comment]
I have the same problem with version 2.2.2 and 2.2.3-SNAPSHOT. 
Looking at the code:

**Comment by swachter** [comment]
GitHub rejected to upload the file. Therefore I copied its contents:
```
ASSERTION	AAIBAAMDAgBf
RUN	com.bosch.inst.bikesensor.test.gatling.LongRunningSimulation		longrunningsimulation	1466516305886	N/A	2.0
USER	normal	1	START	1466516306818	1466516306818
USER	overload	3	START	1466516306826	1466516306826
USER	overload	4	START	1466516306827	1466516306827
USER	overload	5	START	1466516306827	1466516306827
USER	overload	6	START	1466516306827	1466516306827
USER	overload	7	START	1466516306827	1466516306827
USER	overload	8	START	1466516306827	1466516306827
USER	overload	9	START	1466516306827	1466516306827
USER	overload	10	START	1466516306827	1466516306827
USER	overload	11	START	1466516306827	1466516306827
USER	overload	12	START	1466516306827	1466516306827
USER	overload	13	START	1466516306827	1466516306827
USER	overload	14	START	1466516306827	1466516306827
USER	overload	15	START	1466516306827	1466516306827
USER	overload	16	START	1466516306827	1466516306827
USER	overload	17	START	1466516306827	1466516306827
USER	overload	18	START	1466516306827	1466516306827
USER	overload	19	START	1466516306827	1466516306827
USER	overload	20	START	1466516306827	1466516306827
USER	overload	21	START	1466516306827	1466516306827
USER	overload	22	START	1466516306827	1466516306827
USER	overload	23	START	1466516306827	1466516306827
USER	overload	24	START	1466516306827	1466516306827
USER	overload	25	START	1466516306828	1466516306828
USER	overload	26	START	1466516306828	1466516306828
USER	overload	27	START	1466516306828	1466516306828
USER	overload	28	START	1466516306828	1466516306828
USER	overload	29	START	1466516306828	1466516306828
USER	overload	30	START	1466516306828	1466516306828
USER	overload	31	START	1466516306828	1466516306828
USER	overload	32	START	1466516306828	1466516306828
USER	overload	33	START	1466516306828	1466516306828
USER	overload	34	START	1466516306828	1466516306828
USER	overload	35	START	1466516306828	1466516306828
USER	overload	36	START	1466516306828	1466516306828
USER	overload	37	START	1466516306828	1466516306828
USER	overload	38	START	1466516306828	1466516306828
USER	overload	39	START	1466516306828	1466516306828
USER	overload	40	START	1466516306828	1466516306828
USER	overload	41	START	1466516306828	1466516306828
USER	overload	42	START	1466516306828	1466516306828
USER	overload	43	START	1466516306828	1466516306828
USER	overload	44	START	1466516306828	1466516306828
USER	overload	45	START	1466516306828	1466516306828
USER	overload	46	START	1466516306828	1466516306828
USER	overload	47	START	1466516306828	1466516306828
USER	overload	48	START	1466516306828	1466516306828
USER	overload	49	START	1466516306828	1466516306828
USER	overload	50	START	1466516306828	1466516306828
USER	overload	51	START	1466516306828	1466516306828
USER	overload	52	START	1466516306828	1466516306828
USER	overload	53	START	1466516306828	1466516306828
USER	overload	54	START	1466516306829	1466516306829
USER	overload	55	START	1466516306829	1466516306829
USER	overload	56	START	1466516306829	1466516306829
USER	overload	57	START	1466516306829	1466516306829
USER	overload	58	START	1466516306829	1466516306829
USER	overload	59	START	1466516306829	1466516306829
USER	overload	60	START	1466516306829	1466516306829
USER	overload	61	START	1466516306829	1466516306829
USER	overload	62	START	1466516306829	1466516306829
USER	overload	63	START	1466516306829	1466516306829
USER	overload	64	START	1466516306829	1466516306829
USER	overload	65	START	1466516306829	1466516306829
USER	overload	66	START	1466516306829	1466516306829
USER	overload	67	START	1466516306829	1466516306829
USER	overload	68	START	1466516306829	1466516306829
USER	overload	69	START	1466516306829	1466516306829
USER	overload	70	START	1466516306829	1466516306829
USER	overload	71	START	1466516306829	1466516306829
USER	overload	72	START	1466516306829	1466516306829
USER	overload	73	START	1466516306829	1466516306829
USER	overload	74	START	1466516306829	1466516306829
USER	overload	75	START	1466516306829	1466516306829
USER	overload	76	START	1466516306829	1466516306829
USER	overload	77	START	1466516306829	1466516306829
USER	overload	78	START	1466516306829	1466516306829
USER	overload	79	START	1466516306829	1466516306829
USER	overload	80	START	1466516306829	1466516306829
USER	overload	81	START	1466516306829	1466516306829
USER	overload	82	START	1466516306830	1466516306830
USER	overload	83	START	1466516306830	1466516306830
USER	overload	84	START	1466516306830	1466516306830
USER	overload	85	START	1466516306830	1466516306830
USER	overload	86	START	1466516306830	1466516306830
USER	overload	87	START	1466516306830	1466516306830
USER	overload	88	START	1466516306830	1466516306830
USER	overload	89	START	1466516306830	1466516306830
USER	overload	90	START	1466516306830	1466516306830
USER	overload	91	START	1466516306830	1466516306830
USER	overload	92	START	1466516306830	1466516306830
USER	overload	93	START	1466516306830	1466516306830
USER	overload	94	START	1466516306830	1466516306830
USER	overload	95	START	1466516306830	1466516306830
USER	overload	96	START	1466516306830	1466516306830
USER	overload	97	START	1466516306830	1466516306830
USER	overload	98	START	1466516306830	1466516306830
USER	overload	99	START	1466516306830	1466516306830
USER	overload	100	START	1466516306830	1466516306830
USER	overload	101	START	1466516306830	1466516306830
USER	overload	102	START	1466516306830	1466516306830
USER	overload	103	START	1466516306830	1466516306830
USER	overload	104	START	1466516306830	1466516306830
USER	overload	105	START	1466516306830	1466516306830
USER	overload	106	START	1466516306830	1466516306830
USER	overload	107	START	1466516306830	1466516306830
USER	overload	108	START	1466516306830	1466516306830
USER	overload	109	START	1466516306830	1466516306830
USER	overload	110	START	1466516306831	1466516306831
USER	overload	111	START	1466516306831	1466516306831
USER	overload	112	START	1466516306831	1466516306831
USER	overload	113	START	1466516306831	1466516306831
USER	overload	114	START	1466516306831	1466516306831
USER	overload	115	START	1466516306831	1466516306831
USER	overload	116	START	1466516306831	1466516306831
USER	overload	117	START	1466516306831	1466516306831
USER	overload	118	START	1466516306831	1466516306831
USER	overload	119	START	1466516306831	1466516306831
USER	overload	120	START	1466516306831	1466516306831
USER	overload	121	START	1466516306831	1466516306831
USER	overload	122	START	1466516306831	1466516306831
USER	overload	123	START	1466516306831	1466516306831
USER	overload	124	START	1466516306831	1466516306831
USER	overload	125	START	1466516306831	1466516306831
USER	overload	126	START	1466516306831	1466516306831
USER	overload	127	START	1466516306831	1466516306831
USER	bikes	128	START	1466516306831	1466516306831
USER	bikes	129	START	1466516306832	1466516306832
USER	bikes	130	START	1466516306832	1466516306832
USER	bikes	131	START	1466516306832	1466516306832
USER	bikes	132	START	1466516306832	1466516306832
USER	bikes	133	START	1466516306832	1466516306832
USER	bikes	134	START	1466516306832	1466516306832
USER	bikes	135	START	1466516306832	1466516306832
USER	bikes	136	START	1466516306832	1466516306832
USER	bikes	137	START	1466516306832	1466516306832
USER	bikes	138	START	1466516306832	1466516306832
USER	bikes	139	START	1466516306832	1466516306832
USER	bikes	140	START	1466516306832	1466516306832
USER	bikes	141	START	1466516306832	1466516306832
USER	bikes	142	START	1466516306832	1466516306832
USER	bikes	143	START	1466516306832	1466516306832
USER	bikes	144	START	1466516306832	1466516306832
USER	bikes	145	START	1466516306832	1466516306832
USER	bikes	146	START	1466516306832	1466516306832
USER	bikes	147	START	1466516306832	1466516306832
USER	bikes	148	START	1466516306832	1466516306832
USER	bikes	149	START	1466516306832	1466516306832
USER	bikes	150	START	1466516306833	1466516306833
USER	bikes	151	START	1466516306833	1466516306833
USER	bikes	152	START	1466516306833	1466516306833
REQUEST	normal	1		precommission	1466516306873	1466516307269	OK	 
REQUEST	normal	1		register first user	1466516307289	1466516308110	OK	 
USER	normal	2	START	1466516308842	1466516308842
REQUEST	normal	1		writeBuddyDetails	1466516309473	1466516309610	OK	 
```

**Comment by slandelle** [comment]
@swachter I just tried to generate the reports from your log file with the `-ro` option and it worked perfectly fine.

```
Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                          3 (OK=3      KO=0     )
> min response time                                    137 (OK=137    KO=-     )
> max response time                                    821 (OK=821    KO=-     )
> mean response time                                   451 (OK=451    KO=-     )
> std deviation                                        281 (OK=281    KO=-     )
> response time 50th percentile                        396 (OK=396    KO=-     )
> response time 75th percentile                        608 (OK=608    KO=-     )
> response time 95th percentile                        778 (OK=778    KO=-     )
> response time 99th percentile                        812 (OK=812    KO=-     )
> mean requests/sec                                      1 (OK=1      KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             2 ( 67%)
> 800 ms < t < 1200 ms                                   1 ( 33%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 0 (  0%)
================================================================================

Reports generated in 0s.
Please open the following file: /Users/slandelle/Downloads/gatling-charts-highcharts-bundle-2.2.2/results/broken/index.html
For all requests: percentage of successful requests is greater than 95 : true
```

<img width="898" alt="screen shot 2016-07-06 at 15 54 45" src="https://cloud.githubusercontent.com/assets/849197/16620255/0d4a0af4-4392-11e6-8329-da99a1d4955a.png">

If you have a reproducer, please send me an email.

**Comment by slandelle** [comment]
Fixed, thanks for reporting!
