### ISSUE TITLE
JSF Trinidad handling error

### ISSUE THREAD

**Issue by samindaadikari** [gatling/gatling#3077]
Herewith I attached my gatling scenario. Please check it and give your opinion on that.

Its getting below compilation error

GATLING_HOME is set to /opt/gatling
23:34:40.574 [ERROR] i.g.c.ZincCompiler$ - /opt/gatling/user-files/simulations/itmis_calendar1/RecordedSimulation.scala:97: not enough arguments for method jsfGet: (name: String, url: io.gatling.core.session.Expression[String])io.gatling.http.request.builder.HttpRequestBuilder.
Unspecified value parameter url.
23:34:40.578 [ERROR] i.g.c.ZincCompiler$ - 		.exec(jsfGet("request_0")
23:34:40.579 [ERROR] i.g.c.ZincCompiler$ - 		            ^
23:34:40.580 [ERROR] i.g.c.ZincCompiler$ - /opt/gatling/user-files/simulations/itmis_calendar1/RecordedSimulation.scala:112: not enough arguments for method jsfPost: (name: String, url: io.gatling.core.session.Expression[String])io.gatling.http.request.builder.HttpRequestBuilder.
Unspecified value parameter url.
23:34:40.580 [ERROR] i.g.c.ZincCompiler$ - 		.exec(jsfPost("request_6")
23:34:40.580 [ERROR] i.g.c.ZincCompiler$ - 		             ^
23:34:40.580 [ERROR] i.g.c.ZincCompiler$ - /opt/gatling/user-files/simulations/itmis_calendar1/RecordedSimulation.scala:260: not enough arguments for method jsfGet: (name: String, url: io.gatling.core.session.Expression[String])io.gatling.http.request.builder.HttpRequestBuilder.
Unspecified value parameter url.
23:34:40.580 [ERROR] i.g.c.ZincCompiler$ - 		.exec(jsfGet("request_65")
23:34:40.580 [ERROR] i.g.c.ZincCompiler$ - 		            ^
23:34:40.581 [ERROR] i.g.c.ZincCompiler$ - /opt/gatling/user-files/simulations/itmis_calendar1/RecordedSimulation.scala:315: not enough arguments for method jsfPost: (name: String, url: io.gatling.core.session.Expression[String])io.gatling.http.request.builder.HttpRequestBuilder.
Unspecified value parameter url.
23:34:40.581 [ERROR] i.g.c.ZincCompiler$ - 		.exec(jsfPost("request_89")
23:34:40.581 [ERROR] i.g.c.ZincCompiler$ - 		             ^
23:34:40.581 [ERROR] i.g.c.ZincCompiler$ - /opt/gatling/user-files/simulations/itmis_calendar1/RecordedSimulation.scala:382: not enough arguments for method jsfPost: (name: String, url: io.gatling.core.session.Expression[String])io.gatling.http.request.builder.HttpRequestBuilder.
Unspecified value parameter url.
23:34:40.581 [ERROR] i.g.c.ZincCompiler$ - 		.exec(jsfPost("request_112")
23:34:40.581 [ERROR] i.g.c.ZincCompiler$ - 		             ^
23:34:40.582 [ERROR] i.g.c.ZincCompiler$ - /opt/gatling/user-files/simulations/itmis_calendar1/RecordedSimulation.scala:416: not enough arguments for method jsfGet: (name: String, url: io.gatling.core.session.Expression[String])io.gatling.http.request.builder.HttpRequestBuilder.
Unspecified value parameter url.
23:34:40.582 [ERROR] i.g.c.ZincCompiler$ - 		.exec(jsfGet("request_119")
23:34:40.582 [ERROR] i.g.c.ZincCompiler$ - 		            ^
23:34:40.585 [ERROR] i.g.c.ZincCompiler$ - /opt/gatling/user-files/simulations/itmis_calendar1/RecordedSimulation.scala:440: not enough arguments for method jsfPost: (name: String, url: io.gatling.core.session.Expression[String])io.gatling.http.request.builder.HttpRequestBuilder.
Unspecified value parameter url.
23:34:40.585 [ERROR] i.g.c.ZincCompiler$ - 		.exec(jsfPost("request_129")
23:34:40.585 [ERROR] i.g.c.ZincCompiler$ - 		             ^
23:34:40.952 [ERROR] i.g.c.ZincCompiler$ - 7 errors found
23:34:40.955 [ERROR] i.g.c.ZincCompiler$ - Compilation crashed
sbt.compiler.CompileFailed: null
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:105)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:168)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:94)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:84)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:159)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:68)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:201)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:183)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:174)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:165)
	at io.gatling.compiler.ZincCompiler$$anonfun$7.apply(ZincCompiler.scala:154)
	at io.gatling.compiler.ZincCompiler$$anonfun$7.apply(ZincCompiler.scala:154)
	at scala.util.Try$.apply(Try.scala:161)
	at io.gatling.compiler.ZincCompiler$delayedInit$body.apply(ZincCompiler.scala:154)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at io.gatling.compiler.ZincCompiler$.main(ZincCompiler.scala:36)
	at io.gatling.compiler.ZincCompiler.main(ZincCompiler.scala)
Choose a simulation number:
     [0] computerdatabase.BasicSimulation
     [1] computerdatabase.advanced.AdvancedSimulationStep01
     [2] computerdatabase.advanced.AdvancedSimulationStep02
     [3] computerdatabase.advanced.AdvancedSimulationStep03
     [4] computerdatabase.advanced.AdvancedSimulationStep04
     [5] computerdatabase.advanced.AdvancedSimulationStep05

 
[RecordedSimulation.scala.txt](https://github.com/gatling/gatling/files/350636/RecordedSimulation.scala.txt)

**Comment by slandelle** [comment]
This is not a Gatling issue but a misusage. Please use the community mailing list.
