### ISSUE TITLE
Reports: getting ArrayIndexOutOfBoundsException: (negative big number) when trying to generate reports (-ro option)

### ISSUE THREAD

**Issue by holandaleo** [gatling/gatling#3084]
I have the attached log file that was generated during a 45 minutes execution. Execution went all well. File inside the "bug" folder.

Same test plan executed different time might generate log files that are parsed correcting during -ro execution. But the attached one is a sample of a defective log file generated.

I can't tell if the problem is with the log file generation or some bug on the code that parse the file.

Log file inside [simulation-ok.zip](https://github.com/gatling/gatling/files/369932/simulation-ok.zip) generates the report fine. The other one inside [simulation-broken.zip](https://github.com/gatling/gatling/files/369931/simulation-broken.zip) gives me this:

```
c:\dev\gatling-charts-highcharts-bundle-2.2.2\bin>gatling.bat -ro my_defective_simulation
GATLING_HOME is set to "C:\dev\gatling-charts-highcharts-bundle-2.2.2"
JAVA = ""C:\Program Files\Java\jdk1.8.0_51\bin\java.exe""
Parsing log file(s)...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -543822708
        at io.gatling.charts.stats.buffers.CountsBuffer.update(CountBuffer.scala:35)
        at io.gatling.charts.stats.buffers.ResponsesPerSecBuffers$class.updateResponsesPerSecBuffers(ResponsesPerSecBuff
ers.scala:32)
        at io.gatling.charts.stats.ResultsHolder.updateResponsesPerSecBuffers(ResultsHolder.scala:21)
        at io.gatling.charts.stats.ResultsHolder.addRequestRecord(ResultsHolder.scala:48)
        at io.gatling.charts.stats.LogFileReader.io$gatling$charts$stats$LogFileReader$$$anonfun$10(LogFileReader.scala:
150)
        at io.gatling.charts.stats.LogFileReader$lambda$$secondPass$1.apply(LogFileReader.scala:145)
        at io.gatling.charts.stats.LogFileReader$lambda$$secondPass$1.apply(LogFileReader.scala:145)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at io.gatling.charts.stats.LogFileReader.secondPass(LogFileReader.scala:145)
        at io.gatling.charts.stats.LogFileReader.io$gatling$charts$stats$LogFileReader$$$anonfun$11(LogFileReader.scala:
165)
        at io.gatling.charts.stats.LogFileReader$lambda$3.apply(LogFileReader.scala:165)
        at io.gatling.charts.stats.LogFileReader$lambda$3.apply(LogFileReader.scala:165)
        at io.gatling.charts.stats.LogFileReader.parseInputFiles(LogFileReader.scala:63)
        at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:165)
        at io.gatling.app.LogFileProcessor.initLogFileReader(RunResultProcessor.scala:55)
        at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:37)
        at io.gatling.app.Gatling.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.start(Gatling.scala:57)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
        at io.gatling.app.Gatling$.main(Gatling.scala:43)
        at io.gatling.app.Gatling.main(Gatling.scala)
```

**Comment by slandelle** [comment]
Thans for reporting.
Most likely caused by #3087
