### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedOperationException: There were no requests sent during the simulation, reports won't be generated

### ISSUE THREAD

**Issue by mmeier2** [gatling/gatling#3089]
I am currently trying to execute my exec functions with Session => Session  which is shown to be supported in the documentation

`  val execThis = exec(session => {
    http("this").get("/genres").headers(headers)
    session
  })`

However when I run this, gatling does not send the request 

> Exception in thread "main" java.lang.UnsupportedOperationException: There were no requests sent during the simulation, reports won't be generated
	at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:48)
	at io.gatling.app.LogFileProcessor.generateReports(RunResultProcessor.scala:64)
	at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:43)
	at io.gatling.app.Gatling.start(Gatling.scala:66)
	at io.gatling.app.Gatling$.start(Gatling.scala:57)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
	at io.gatling.app.Gatling$.main(Gatling.scala:43)
	at io.gatling.app.Gatling.main(Gatling.scala)

**Comment by slandelle** [comment]
First, please use our mailing list for questions, not our bug tracker.

Then, please properly read the documentation: http://gatling.io/docs/2.2.2/general/scenario.html

**Comment by dfosticupgrade** [comment]
> First, please use our mailing list for questions, not our bug tracker.
> 
> Then, please properly read the documentation: http://gatling.io/docs/2.2.2/general/scenario.html

third, better to not answer at all rather than answer like this
