### ISSUE TITLE
Gatling Metrics Showing Incorrect Values In Summary Report

### ISSUE THREAD

**Issue by Srisaibersys** [gatling/gatling#3122]
I am using Gatling Version 2.2.2 and facing below exception. My Test Cases are passing and I am getting proper JSON Response from Server.

I observe that in Summary Report all the values are same e.g., 

> min response time                                   2288 (OK=2288   KO=-    )
> max response time                                  2288 (OK=2288   KO=-    )
> mean response time                                2288 (OK=2288   KO=-    )
> std deviation                                            0 (OK=0      KO=-     )
> response time 50th percentile                 2288 (OK=2288   KO=-    )
> response time 75th percentile                 2288 (OK=2288   KO=-    )
> response time 95th percentile                 2288 (OK=2288   KO=-    )
> response time 99th percentile                 2288 (OK=2288   KO=-    )

```
dependencies {
    compile ('io.gatling:gatling-core:2.2.2')
    compile ('io.gatling:gatling-app:2.2.2')
    compile ('io.gatling.highcharts:gatling-charts-highcharts:2.2.2') 
}
```

```
Injector.scala Environment.Url selected: https://myurl.com
20:08:49.232 [INFO ] i.g.h.a.HttpEngine - Start warm up
20:08:50.277 [INFO ] i.g.h.a.HttpEngine - Couldn't execute warm up request http://gatling.io
java.util.concurrent.TimeoutException: Request timeout to gatling.io/192.30.252.153:80 after 1000ms
	... 6 common frames omitted
Wrapped by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to gatling.io/192.30.252.153:80 after 1000ms
	at org.asynchttpclient.netty.NettyResponseFuture.abort(NettyResponseFuture.java:239)
	at org.asynchttpclient.netty.request.NettyRequestSender.abort(NettyRequestSender.java:396)
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)
20:08:50.277 [INFO ] i.g.h.a.HttpEngine - Warm up done
Simulation videoauto.Injector started...
20:08:50.422 [DEBUG] i.g.h.a.s.HttpTx$ - Sending request=TC05_VideoMS_FB_Activate_DC1_404 uri=https://myurl.com: scenario=TC05_Video, userId=1
TC05_Video service Response :Some({"trackingId":"2324324532","accountNumber":"234324324","activationSource":"ACTIVATOR-WEB",.......(some data trimmed here),"asyncProcessReasons":{"asyncProcessReason":null},"error":[{"errorCode":"6011","errorMessage":"Unable to communicate with Device service - activateDeviceDC1"}],"activationRecordId":"2796337579234569"})

================================================================================
2016-08-31 20:08:53                                           4s elapsed
---- TC05_Video ------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done:1     
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=1      KO=0     )
> TC05_Video                                               (OK=1      KO=0     )

================================================================================

Simulation videoauto.Injector completed in 3 seconds
[ERROR] [08/31/2016 20:08:53.777] [GatlingSystem-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(GatlingSystem)] exception while executing timer task
java.lang.NullPointerException
	at io.gatling.core.akka.BaseActor.system(BaseActor.scala:25)
	at io.gatling.metrics.sender.TcpSender.askForConnection(TcpSender.scala:99)
	at io.gatling.metrics.sender.TcpSender$$anonfun$3.io$gatling$metrics$sender$TcpSender$$anonfun$3$$$anonfun$1(TcpSender.scala:54)
	at io.gatling.metrics.sender.TcpSender$$nestedInAnonfun$3$lambda$$applyOrElse$1.apply(TcpSender.scala:54)
	at io.gatling.metrics.sender.TcpSender$$nestedInAnonfun$3$lambda$$applyOrElse$1.apply(TcpSender.scala:54)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(LightArrayRevolverScheduler.scala:340)
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(LightArrayRevolverScheduler.scala:144)
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(LightArrayRevolverScheduler.scala:143)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at akka.actor.LightArrayRevolverScheduler.close(LightArrayRevolverScheduler.scala:142)
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:712)
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:646)
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:646)
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:646)
	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:662)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:840)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:840)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:436)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:435)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                          1 (OK=1      KO=0     )
> min response time                                   2288 (OK=2288   KO=-     )
> max response time                                   2288 (OK=2288   KO=-     )
> mean response time                                  2288 (OK=2288   KO=-     )
> std deviation                                          0 (OK=0      KO=-     )
> response time 50th percentile                       2288 (OK=2288   KO=-     )
> response time 75th percentile                       2288 (OK=2288   KO=-     )
> response time 95th percentile                       2288 (OK=2288   KO=-     )
> response time 99th percentile                       2288 (OK=2288   KO=-     )
> mean requests/sec                                   0.25 (OK=0.25   KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            1 (100%)
> failed                                                 0 (  0%)
================================================================================

```

**Comment by Srisaibersys** [comment]
Also the same issue we observed for checking NULL response values.

```
19:20:51.149 [INFO ] i.g.h.a.HttpEngine - Start warm up
19:20:51.859 [INFO ] i.g.h.a.HttpEngine - Warm up done
Simulation videoauto.Injector started...
19:20:52.019 [DEBUG] i.g.h.a.s.HttpTx$ - Sending request=TC01_Video uri=https://myurl.com: scenario=TC01_Video , userId=1
19:20:52.969 [WARN ] i.g.h.a.ResponseProcessor - Request 'TC01_Video' failed: jsonPath($..errorMessage).find(0).notExists, unexpectedly found null
19:20:52.979 [DEBUG] i.g.h.a.ResponseProcessor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
TC01_Video: KO jsonPath($..errorMessage).find(0).notExists, unexpectedly found null
=========================
Session:
Session(TC01_Video,1,Map(gatling.http.cache.dns -> io.gatling.http.resolver.ShuffleJdkNameResolver@15791566, accountNumber -> 12344321, trackingId -> 123213213, responseJSON -> {.....(some text removed here)....., "errorCode":null,"service":[{"rateCode":"BA","type":"VIDEO","rank":"0","activationStatus":"SUCCESS","errorMessage":null,"errorCode":null,"serviceStatus":null}]}],"asyncProcessReasons":{"asyncProcessReason":null},"error":[],"activationRecordId":"2796337579234569"}),1472692851985,0,KO,List(),<function1>)
=========================
HTTP request:
POST https://muurl.com
headers=
Keep-Alive: 300
Connection: close
Accept: application/json
Content-Type: application/json
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1) Gecko/20090624 Firefox/3.5
Content-Length: 816
Host: mt_host.com

=========================
HTTP response:
status=
200 OK
headers= 
Content-Type: application/json;charset=UTF-8
Date: Thu, 01 Sep 2016 01:20:52 GMT
Server: Apache-Coyote/1.1
X-Application-Context: my_host#0.0.1-3860a4a:qaauto,g1,cloud:0
X-Cf-Requestid: 71595704-ffc5-49ae-52e2-62b89545eb0c
Content-Length: 922
Connection: close

body=
{.....(some text removed here)....., "errorMessage":null,"errorCode":null,"service":[{"rateCode":"BA","type":"VIDEO","rank":"0","activationStatus":"SUCCESS","errorMessage":null,"errorCode":null,"serviceStatus":null}]}],"asyncProcessReasons":{"asyncProcessReason":null},"error":[],"activationRecordId":"2796337579234569"}
<<<<<<<<<<<<<<<<<<<<<<<<<
TC01_Video Response :Some({.....(some text removed here).....,"errorMessage":null,"errorCode":null,"service":[{"rateCode":"BA","type":"VIDEO","rank":"0","activationStatus":"SUCCESS","errorMessage":null,"errorCode":null,"serviceStatus":null}]}],"asyncProcessReasons":{"asyncProcessReason":null},"error":[],"activationRecordId":"2796337579234569"})

================================================================================
2016-08-31 19:20:53                                           3s elapsed
---- TC01_Video  -------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done:1     
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=1     )
> TC01_Video                                               (OK=0      KO=1     )
---- Errors --------------------------------------------------------------------
> jsonPath($..errorMessage).find(0).notExists, unexpectedly foun      1 (100.0%)
d null
================================================================================

Simulation videoauto.Injector completed in 2 seconds
[ERROR] [08/31/2016 19:20:54.001] [GatlingSystem-akka.actor.default-dispatcher-11] [TaskInvocation] null
java.lang.NullPointerException
	at io.gatling.core.akka.BaseActor.system(BaseActor.scala:25)
	at io.gatling.metrics.sender.TcpSender.askForConnection(TcpSender.scala:99)
	at io.gatling.metrics.sender.TcpSender$$anonfun$3.io$gatling$metrics$sender$TcpSender$$anonfun$3$$$anonfun$1(TcpSender.scala:54)
	at io.gatling.metrics.sender.TcpSender$$nestedInAnonfun$3$lambda$$applyOrElse$1.apply(TcpSender.scala:54)
	at io.gatling.metrics.sender.TcpSender$$nestedInAnonfun$3$lambda$$applyOrElse$1.apply(TcpSender.scala:54)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                          1 (OK=0      KO=1     )
> min response time                                    881 (OK=-      KO=881   )
> max response time                                    881 (OK=-      KO=881   )
> mean response time                                   881 (OK=-      KO=881   )
> std deviation                                          0 (OK=-      KO=0     )
> response time 50th percentile                        881 (OK=-      KO=881   )
> response time 75th percentile                        881 (OK=-      KO=881   )
> response time 95th percentile                        881 (OK=-      KO=881   )
> response time 99th percentile                        881 (OK=-      KO=881   )
> mean requests/sec                                    0.5 (OK=-      KO=0.5   )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 1 (100%)
---- Errors --------------------------------------------------------------------
> jsonPath($..errorMessage).find(0).notExists, unexpectedly foun      1 (100.0%)
d null
================================================================================
```

**Comment by slandelle** [comment]
* Stats are correct, you just injected one single request
* Your NPE probably happens because you're trying to use the Graphite datawriter and it's not properly configured or the remote Graphite/InfluxDB instance is not up.
