### ISSUE TITLE
Exception while the Generating Reports in gatling using jar in Command Prompt

### ISSUE THREAD

**Issue by Srisaibersys** [gatling/gatling#3141]
I was trying to run test cases using jar in command line, test cases were working fine but I am not able to generate reports and facing the below issue and we tried to enable trace log still no luck.

Here is the result location which I mapped with:

"--results-folder", "**${buildDir}//reports//gatling-results"**

```

Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <?> at index 56: scalaz/syntax/ApplicativeSyn
tax$ApplicativeIdV$$anonfun$?$2.class
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.gatling.commons.util.PathHelper$.string2path(PathHelper.scala:30)
        at io.gatling.commons.util.ScanHelper$$anonfun$$nestedInanonfun$3$1.isDefinedAt(ScanHelper.scala:91)
        at io.gatling.commons.util.ScanHelper$$anonfun$$nestedInanonfun$3$1.isDefinedAt(ScanHelper.scala:90)
        at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:535)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at io.gatling.commons.util.ScanHelper$.deepCopyPackageContent(ScanHelper.scala:108)
        at io.gatling.charts.report.ReportsGenerator.copyAssets$1(ReportsGenerator.scala:43)
        at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:58)
        at io.gatling.app.LogFileProcessor.generateReports(RunResultProcessor.scala:64)
        at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:43)
        at io.gatling.app.Gatling.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.start(Gatling.scala:57)
        at io.gatling.app.Gatling$.fromMap(Gatling.scala:45)
        at muylib.Engine$.delayedEndpoint$videoauto$Engine$1(Engine.scala:31)
        at mylib.Engine$delayedInit$body.apply(Engine.scala:10)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at mylib.Engine$.main(Engine.scala:10)
        at mylib.Engine.main(Engine.scala)
```

**Comment by slandelle** [comment]
It looks like you're wrapping Gatling to build your custom stuff.
You're on your own here.
