### ISSUE TITLE
Futures timed out after [5 seconds] when running from flood.io on a multi-node grid

### ISSUE THREAD

**Issue by rmanger** [gatling/gatling#3157]
Hi guys,

Having an issue when attempting to run an extreme high load / long rampup gatling test from flood.io.  The configuration I am attempting to run:

- Via the flood.io API, start up a flood grid with **2 nodes**.  (*The 2 nodes are essentially to double the traffic I am throwing at the test server*).  Wait for it to come into a "started" state
- Start up a gatling flood with the following configuration
   - Gatling version 2.2.3
   - Users/Threads = 5
   - RPS = 1000
   - Duration = 7200
   - Rampup = 7200

The test URL does not seem to matter as it does not get that far.  When attempting to start up the flood I get the below error in the logs.  

**Note**: Running against a single node appears to work, however this does not generate enough load, hence the reason for adding a second node.

Any ideas?

***Error***
```
Connecting to flood on: 172.31.38.31:9300
2016/10/04 14:12:31
Exception in thread "main" java.util.concurrent.Timeout Exception : Futures timed out after [5 seconds]
2016/10/04 14:12:31
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
2016/10/04 14:12:31
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
2016/10/04 14:12:31
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
2016/10/04 14:12:31
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
2016/10/04 14:12:31
at scala.concurrent.Await$.result(package.scala:190)
2016/10/04 14:12:31
at io.gatling.core.stats.DataWritersStatsEngine$.apply(StatsEngine.scala:102)
2016/10/04 14:12:31
at io.gatling.app.DefaultCoreComponentsFactory.coreComponents(CoreComponentsFactory.scala:52)
2016/10/04 14:12:31
at io.gatling.app.Gatling.runIfNecessary(Gatling.scala:75)
2016/10/04 14:12:31
at io.gatling.app.Gatling.start(Gatling.scala:65)
2016/10/04 14:12:31
at io.gatling.app.Gatling$.start(Gatling.scala:57)
2016/10/04 14:12:31
at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
2016/10/04 14:12:31
at io.gatling.app.Gatling$.main(Gatling.scala:43)
2016/10/04 14:12:31
at io.gatling.app.Gatling.main(Gatling.scala)
2016/10/04 14:12:31
at io.gatling.app.Gatling.run(Gatling.scala:100)
```

**Comment by slandelle** [comment]
Flood.io os a commercial product from a competitor. It's not an official Gatling product that we support. We have a similar, yet superior solution named FrontLine. If you're interested by a demo, please get in touch at contact@gatling.io

**Comment by rmanger** [comment]
Fair enough.  Thanks anyway.
