### ISSUE TITLE
group -crash report generation 

### ISSUE THREAD

**Issue by vojtechovsky** [gatling/gatling#3170]
# When using "group" and a groupname with comma is entered then it crashes the report generation

Reproducable on the version 2.2.2
OS: Windows 10
JDK: 1.8.0.91

# Steps:
1) create scenario
2) use groupname with comma = > ""006-Countries, Regions and Currencies"
val scn = scenario("Dwh Smoke Test")
				.group("000-Login") { exec(req1) }
				.group("006-Countries, Regions and Currencies") { exec(CountriesRegionsAndCurrencies.page) }

## Fix:
remove the comma

## Error:
Simulation dwh.Dwh01 completed in 3 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...
Exception in thread "main" java.util.NoSuchElementException: key not found: List(006-Countries)
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at io.gatling.charts.report.StatsReportGenerator.addGroupsRec$1(StatsReportGenerator.scala:130)
        at io.gatling.charts.report.StatsReportGenerator.addGroupsRec$1(StatsReportGenerator.scala:126)
        at io.gatling.charts.report.StatsReportGenerator.io$gatling$charts$report$StatsReportGenerator$$$anonfun$14(StatsReportGenerator.scala:140)
        at io.gatling.charts.report.StatsReportGenerator$lambda$$io$gatling$charts$report$StatsReportGenerator$$$nestedInAnonfun$13$1.apply(StatsReportGenerator.scala:139)
        at io.gatling.charts.report.StatsReportGenerator$lambda$$io$gatling$charts$report$StatsReportGenerator$$$nestedInAnonfun$13$1.apply(StatsReportGenerator.scala:139)
        at scala.Option.foreach(Option.scala:257)
        at io.gatling.charts.report.StatsReportGenerator.io$gatling$charts$report$StatsReportGenerator$$$anonfun$13(StatsReportGenerator.scala:139)
        at io.gatling.charts.report.StatsReportGenerator$lambda$$generate$1.apply(StatsReportGenerator.scala:137)
        at io.gatling.charts.report.StatsReportGenerator$lambda$$generate$1.apply(StatsReportGenerator.scala:137)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at io.gatling.charts.report.StatsReportGenerator.generate(StatsReportGenerator.scala:137)
        at io.gatling.charts.report.ReportsGenerator.generateStats$1(ReportsGenerator.scala:38)
        at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:62)
        at io.gatling.app.LogFileProcessor.generateReports(RunResultProcessor.scala:64)
        at io.gatling.app.LogFileProcessor.processRunResult(RunResultProcessor.scala:43)
        at io.gatling.app.Gatling.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.start(Gatling.scala:57)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
        at io.gatling.app.Gatling$.main(Gatling.scala:43)
        at io.gatling.app.Gatling.main(Gatling.scala)

**Comment by slandelle** [comment]
From [doc](http://gatling.io/docs/2.2.2/general/scenario.html#groups-definition):

> Beware that group names mustn’t contain commas.
