### ISSUE TITLE
Core: Exception is thrown on scenario completion by max duration

### ISSUE THREAD

**Issue by EugeneAbramchuk** [gatling/gatling#3232]
I set the max duration for my scenario at 300 seconds, by the end of the scenario I noticed an exception. It only occurred once so far, there must be some sort of an edge case.

Gatling version 2.2.3

```
Simulation *** completed in 300 seconds
11:21:24.573 [ERROR] i.g.h.a.ResponseProcessor - ResponseProcessor crashed on session=Session(*** session data ***) *** request data ***, forwarding user to the next action
java.lang.IllegalStateException: cannot create children while terminating or terminated
at akka.actor.dungeon.Children$class.makeChild(Children.scala:266)
at akka.actor.dungeon.Children$class.attachChild(Children.scala:46)
at akka.actor.ActorCell.attachChild(ActorCell.scala:374)
at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:579)
at io.gatling.http.ahc.ResponseProcessor.executeNext(ResponseProcessor.scala:143)
at io.gatling.http.ahc.ResponseProcessor.logAndExecuteNext(ResponseProcessor.scala:170)
at io.gatling.http.ahc.ResponseProcessor.checkAndProceed$1(ResponseProcessor.scala:293)
at io.gatling.http.ahc.ResponseProcessor.processResponse(ResponseProcessor.scala:323)
at io.gatling.http.ahc.ResponseProcessor.onCompleted(ResponseProcessor.scala:61)
at io.gatling.http.ahc.AsyncHandler.io$gatling$http$ahc$AsyncHandler$$$anonfun$1(AsyncHandler.scala:136)
at io.gatling.http.ahc.AsyncHandler.io$gatling$http$ahc$AsyncHandler$$$anonfun$1$adapted(AsyncHandler.scala:134)
at io.gatling.http.ahc.AsyncHandler.withResponse(AsyncHandler.scala:127)
at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:134)
at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:47)
at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:181)
at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:215)
at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:187)
at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:76)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
at java.lang.Thread.run(Thread.java:745)

```

**Comment by slandelle** [comment]
Thanks for reporting.

**Comment by EugeneAbramchuk** [comment]
More errors discovered with further executions, but I could not discover a 100% way to reproduce. These could be related to the one above.

```
Simulation *** completed in 10 seconds
19:15:48.958 [WARN ] i.n.c.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x890a9169]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:805)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:345)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:748)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:422)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:72)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:127)
	at org.asynchttpclient.netty.request.NettyChannelConnector.connect0(NettyChannelConnector.java:81)
	at org.asynchttpclient.netty.request.NettyChannelConnector.connect(NettyChannelConnector.java:69)
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:101)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:464)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:269)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:632)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:611)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:554)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:704)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
19:15:48.964 [ERROR] i.n.u.c.D.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:805)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:345)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:748)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1004)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:433)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:72)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:127)
	at org.asynchttpclient.netty.request.NettyChannelConnector.connect0(NettyChannelConnector.java:81)
	at org.asynchttpclient.netty.request.NettyChannelConnector.connect(NettyChannelConnector.java:69)
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:101)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:464)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:269)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:632)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:611)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:554)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:704)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

When I fiddled with the ramp up scenario a bit (by raising the upper user count boundary), the exception was gone, only the warnings remained, but this behaviour was not persistent and I could not reproduce it after several minutes.

```
Simulation *** completed in 10 seconds
19:22:35.577 [WARN ] i.n.u.c.SingleThreadEventExecutor - An event executor terminated with non-empty task queue (1)
19:22:35.577 [WARN ] i.n.u.c.SingleThreadEventExecutor - An event executor terminated with non-empty task queue (1)
Parsing log file(s)...
Parsing log file(s) done
Generating reports...
```

I tried obtaining a more detailed stack trace, but adding this line to the logback configuration did not yield a lower level log:

`	<logger name="io.netty.util.concurrent" level="TRACE" />`

**Comment by fviktor92** [comment]
I also often face errors with maxDuration simulation shutdown, which results in fragmented report (not all failures are in the report):

`Simulation io.gatling.highcharts.circeoload.simulations.cashloan.CashLoanSimulation completed in 2700 seconds
15:38:30.979 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:30.985 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:30.986 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:30.987 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-1141-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:30.987 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-636-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.006 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-1141-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.007 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.009 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.018 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.020 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.022 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.023 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-1141-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.025 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-1123-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.027 [ERROR] i.g.c.a.GroupEnd - GroupEnd called but head of stack List(ExitOnCompleteLoopBlock(applicationWindowsRefreshCounter), GroupBlock(List(Open Application, Refresh Application Window),1497878697597,107435,OK), GroupBlock(List(Open Application),1497878694295,109722,OK), TryMaxBlock(0b5c3f1f-b52d-425b-80d2-d23851796189,io.gatling.core.action.InnerTryMax@55a715d3,KO), ExitOnCompleteLoopBlock(a3f1c7e1-2e72-46df-ac8b-57a26cc536f8)) isn't a GroupBlock, please report.
15:38:31.029 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.031 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-1141-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.032 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.037 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.044 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.046 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-903-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.048 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-903-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.051 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-903-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.055 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-1141-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.057 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-781-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.058 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-903-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.059 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-903-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
15:38:31.060 [ERROR] i.g.c.a.InnerLoop - 'asLongAs-1141-inner' crashed with 'java.lang.IllegalStateException: cannot enqueue after timer shutdown', forwarding to the next one
Parsing log file(s)...
Parsing log file(s) done
Generating reports...`

**Comment by slandelle** [comment]
@fviktor92 see #3321

**Comment by slandelle** [comment]
I wasn't able to reproduce so far with Gatling 3 master.
