### ISSUE TITLE
Getting Pruning sources from previous analysis, due to incompatible CompileSetup.

### ISSUE THREAD

**Issue by Qptesting** [gatling/gatling#3244]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [ ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [x ] Check that you can reproduce your issue with latest Gatling version
  * [ ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [ x] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x ] Explain your use case, not the implementation you have in mind.

I have recorded a simple get request and getting below error when i try to execute the script.
using 64 bit machine
Gatling version  :  gatling-charts-highcharts-bundle-2.2.3

Error message : 
C:\perftools\gatling-charts-highcharts-bundle-2.2.3\user-files\simulations>gatli
ng -s http.scala
GATLING_HOME is set to "C:\perftools\gatling-charts-highcharts-bundle-2.2.3"
JAVA = "java"
16:24:38.839 [WARN ] i.g.c.ZincCompiler$ - Pruning sources from previous analysi
s, due to incompatible CompileSetup.
16:24:40.630 [ERROR] i.g.c.ZincCompiler$ - C:\perftools\gatling-charts-highchart
s-bundle-2.2.3\user-files\simulations\get.scala:31: ';' expected but ')' found.
16:24:40.631 [ERROR] i.g.c.ZincCompiler$ -                      .check(status.is
(200))))
16:24:40.632 [ERROR] i.g.c.ZincCompiler$ -
       ^
16:24:40.637 [ERROR] i.g.c.ZincCompiler$ - C:\perftools\gatling-charts-highchart
s-bundle-2.2.3\user-files\simulations\http.scala:30: ';' expected but ')' found.

16:24:40.638 [ERROR] i.g.c.ZincCompiler$ -                      .check(status.is
(200))))
16:24:40.638 [ERROR] i.g.c.ZincCompiler$ -
       ^
16:24:40.650 [ERROR] i.g.c.ZincCompiler$ - two errors found
16:24:40.653 [ERROR] i.g.c.ZincCompiler$ - Compilation crashed
sbt.compiler.CompileFailed: null
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:105)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.a
pply$mcV$sp(AggressiveCompile.scala:95)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.a
pply(AggressiveCompile.scala:95)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.a
pply(AggressiveCompile.scala:95)
        at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(
AggressiveCompile.scala:168)
        at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCo
mpile.scala:94)
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.sca
la:142)
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.sca
la:84)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:6
6)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:6
4)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
        at sbt.inc.Incremental$.compile(Incremental.scala:71)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
        at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:159)
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:68)
        at com.typesafe.zinc.Compiler.compile(Compiler.scala:201)
        at com.typesafe.zinc.Compiler.compile(Compiler.scala:183)
        at com.typesafe.zinc.Compiler.compile(Compiler.scala:174)
        at com.typesafe.zinc.Compiler.compile(Compiler.scala:165)
        at io.gatling.compiler.ZincCompiler$$anonfun$7.apply(ZincCompiler.scala:
153)
        at io.gatling.compiler.ZincCompiler$$anonfun$7.apply(ZincCompiler.scala:
153)
        at scala.util.Try$.apply(Try.scala:161)
        at io.gatling.compiler.ZincCompiler$delayedInit$body.apply(ZincCompiler.
scala:153)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:
12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(Traversab
leForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at io.gatling.compiler.ZincCompiler$.main(ZincCompiler.scala:36)
        at io.gatling.compiler.ZincCompiler.main(ZincCompiler.scala)
The requested class 'http.scala' can not be found in the classpath or does not e
xtends Simulation.
There is no simulation script. Please check that your scripts are in user-files/
simulations
Press any key to continue . . .

**Comment by slandelle** [comment]
`Pruning sources from previous analysis, due to incompatible CompileSetup` is a misleading warning, see #3245.

Your error is that your simulation doesn't compile because of some error in your code.
