### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by sakonachhoeurng** [gatling/gatling#3287]
I got errors while run on Jenkins with `Java version 8`
Here is the error.
Please help with this problem.
```
13:57:52 GATLING_HOME is set to /opt/gatlingException in thread "main" java.lang.UnsupportedClassVersionError: io/gatling/app/Gatling : Unsupported major.minor version 52.0
13:57:52 	at java.lang.ClassLoader.defineClass1(Native Method)
13:57:52 	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
13:57:52 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
13:57:52 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
13:57:52 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
13:57:52 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
13:57:52 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
13:57:52 	at java.security.AccessController.doPrivileged(Native Method)
13:57:52 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
13:57:52 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
13:57:52 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
13:57:52 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
13:57:52 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```
Thanks,
Sakona

**Comment by slandelle** [comment]
> I got errors while run on Jenkins with Java version 8

No, `Unsupported major.minor version 52.0` means the exact opposite: the JVM you're using for Gatling doesn't support Java 8.
Please check your configuration, eg your JAVA_HOME or your toolchain.
