### ISSUE TITLE
Verbose INFO logging when warm up fails

### ISSUE THREAD

**Issue by EugeneAbramchuk** [gatling/gatling#3331]
Gatling version 2.2.4

If Gatling fails to warm up from the first time, it throws an exception, which is unnecessary (it could be handled).

It would be cleaner if Gatling reported:

11:34:14.605 [INFO ] i.g.h.a.HttpEngine - Couldn't execute warm up request http://gatling.io after 1000 ms
11:34:14.xxx [INFO ] i.g.h.a.HttpEngine - Warm up done

```

11:34:14.605 [INFO ] i.g.h.a.HttpEngine - Couldn't execute warm up request http://gatling.io
java.util.concurrent.TimeoutException: Request timeout to not-connected after 1000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:625)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:700)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:428)
	at java.lang.Thread.run(Thread.java:745)
Wrapped by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to not-connected after 1000 ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:168)
	at io.gatling.http.ahc.HttpEngine.warmpUp(HttpEngine.scala:96)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.io$gatling$http$protocol$HttpProtocol$$anon$1$$$anonfun$1(HttpProtocol.scala:62)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:67)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.io$gatling$core$protocol$ProtocolComponentsRegistry$$$anonfun$4(Protocol.scala:69)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:69)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:25)
	at io.gatling.http.action.sync.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder$class.io$gatling$core$structure$StructureBuilder$class$$$anonfun$1(StructureBuilder.scala:34)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at io.gatling.core.structure.StructureBuilder$class.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:98)
	at io.gatling.core.scenario.SimulationParams.io$gatling$core$scenario$SimulationParams$$$anonfun$15(Simulation.scala:188)
	at scala.collection.immutable.List.map(List.scala:273)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:188)
	at io.gatling.app.Runner.run0(Runner.scala:95)
	at io.gatling.app.Runner.run(Runner.scala:64)
	at io.gatling.app.Gatling$.start(Gatling.scala:56)
	at io.gatling.app.Gatling$.fromMap(Gatling.scala:36)
...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
11:34:14.605 [INFO ] i.g.h.a.HttpEngine - Warm up done
```

**Comment by slandelle** [comment]
Well, you only see this stacktrace because you run with INFO logging enabled.
"unnecessary" is your opinion, it could make sense for other people to have a way to figure out way warm up failed.
A possible solution would be to only log the exception when DEBUG is enabled.
Are you interested in contributing?

**Comment by EugeneAbramchuk** [comment]
Sure, I'll submit a pull request.

Thanks for pointing out about the log level.

**Comment by EugeneAbramchuk** [comment]
@slandelle Sorry it took long, I fixed the issue, which branch should I submit the pull request to: 2.3 or master?

**Comment by slandelle** [comment]
master, please. I can then cherry-pick

**Comment by EugeneAbramchuk** [comment]
Submitted. This is my first PR so I'd appreciate a close inspection, albeit a minor change.
