### ISSUE TITLE
Support using another slf4j backend than logback

### ISSUE THREAD

**Issue by josetesan** [gatling/gatling#3340]
We are using gatling 2.2.5 as part of our maven build process, and as such, it does inheritance all the libraries our product uses : slf4j, log4j1.x, log4j2.x ( i know, i  know , but it's a legacy product can't be changed ).

The usage of logback inside gatling conflicts with these libraries, as there's a race condition between them, so we're giving an error :

```
SLF4J: Found binding in [jar:file:/D:/Users/OU83MP/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.2/log4j-slf4j-impl-2.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/Users/OU83MP/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/Users/OU83MP/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
15:08:00.845 [main] TRACE io.gatling.app.Gatling$ - Starting
15:08:00.942 [main] TRACE io.gatling.app.Gatling$ - Configuration loaded
15:08:01.251 [GatlingSystem-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
15:08:01.251 [main] TRACE io.gatling.app.Gatling$ - ActorSystem instantiated
15:08:01.266 [main] TRACE io.gatling.app.Gatling$ - Runner instantiated
15:08:01.358 [main] TRACE io.gatling.app.Runner - Running
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
        at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.ClassCastException: org.apache.logging.slf4j.Log4jLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext

```
If we exclude the logback dependency, we get a ClassNotFoundException.
If we exclude the slf4j/log4j2 dependencies,  problem still persists.

Would'nt it be better to use the slf4j-api inside gatling, and not impose the ( great ) logback impl ?

**Comment by alienscience** [comment]
We hit the same problem on a project that uses _log4j2_ but also uses the Gatling sbt plugin for performance testing. We hit the ClassNotFound exception:
```
sbt.ForkMain$ForkError: java.lang.NoClassDefFoundError: ch/qos/logback/classic/LoggerContext
        at io.gatling.app.Gatling$.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:43)
        at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
        at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: sbt.ForkMain$ForkError: java.lang.ClassNotFoundException: ch.qos.logback.classic.LoggerContext
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.gatling.app.Gatling$.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:43)
        at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
        at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The offending line is in Gatling.scala:
https://github.com/gatling/gatling/blob/4334984cf35540a490a2fa03feccdc7a145bedcf/gatling-app/src/main/scala/io/gatling/app/Gatling.scala#L26

**Comment by slandelle** [comment]
Gatling ships slf4j and comes with a configuration that sets `immediateFlush` to `false`.
This is a pretty standard optimization for prod configuration. Then, this means we could be missing unflushed events on shutdown. This was fixed as of #3255.

Contributions welcome, as long as they are not super ugly and they don't try to revert fix for #3255.

**Comment by slandelle** [comment]
Feature request has been idle for too long, closing for now.

Will reopen if someone chimes in with a contribution.

**Comment by sebastianvoss** [comment]
@slandelle, would you be happy with something like this? If so, I can submit a merge request. This should work with `logback` and `log4j2`:

```
//LoggerFactory.getILoggerFactory.asInstanceOf[LoggerContext].stop()
val factoryClass = LoggerFactory.getILoggerFactory.getClass
Try(factoryClass.getMethod("stop").invoke(factoryClass))
```

**Comment by slandelle** [comment]
@sebastianvoss , Yes, I'm fine with this change as it doesn't break anything for current users and doesn't bring any complexity.

But please understand that Gatling is a software, not a library, and it's supposed to be used as we developed and tested it.

Log4j2 is not supported, so if any problem should arise, well.. you're on your own.
Generally speaking, if you mix Gatling with your application sources, you might run into dependencies clashes, so it might be more sound to not mix but isolate classpaths.

**Comment by testphreak** [comment]
Hi @sebastianvoss, did you create a PR with the suggested change? This will help anyone wanting to use a logging implementation of their choice.

**Comment by testphreak** [comment]
Hi @sebastianvoss, it appears your fix has caused another issue after it was added in `3.0.1` to address the original `ClassNotFoundException`. Now it throws -
```
[1] - [WARN] 2018-11-23 03:03:37 io.gatling.app.Gatling$ - The LoggerFactory of your logging framework does not have a stop method. In case you run into buffering issues consider switching to logback or log4j2 which support flushing the buffer before shutdown.
java.lang.NoSuchMethodException: org.apache.logging.slf4j.Log4jLoggerFactory.stop()
	at java.lang.Class.getMethod(Class.java:1786)
	at io.gatling.app.Gatling$.start(Gatling.scala:85)
	at io.gatling.app.Gatling$.fromMap(Gatling.scala:41)
        ...
```
This is because as far as I can see in the `slf4j` or `log4j2` documentation there isn't a `stop` method as the exception says. Catching the `NoSuchMethodException` does not stop the log message from appearing.

These are the dependencies I am using inside my `Maven` load test project -
```
        <!-- Log4j2 Scala logging API -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api-scala_2.12</artifactId>
            <version>11.0</version>
        </dependency>

        <!-- Binding causes all SLF4J APIs to be routed to Log4j 2 -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.11.1</version>
        </dependency>
```
As far as I know that is all is needed to use `log4j2` logging implementation. Could you share your `log4j2` logging configuration? It will help me verify if I am providing the wrong configuration. I am guessing you applied the fix, as it worked for you.

At this point, I feel we should go with @slandelle's original workaround [here](https://github.com/gatling/gatling/commit/9b054bc7c3784006a1ccf636c638842fef8c9fad#commitcomment-22102395) for trapping the `ClassNotFoundException`. This would allow anybody to continue using `log4j2`. I've tried different options to catch and suppress the warning, but I can't seem to turn it off.

Either that or we simple turn this [line](https://github.com/gatling/gatling/blob/7f4db686d0e3f37d622302861a3109cf59d4b2e3/gatling-app/src/main/scala/io/gatling/app/Gatling.scala#L88) into an `INFO` event and not throw the exception back to the client.

**Comment by slandelle** [comment]
@testphreak This is "just" a WARN log that happens on shut down so I guess you can live with it. 

Then, I'm done with this topic. For some unknown sbt/native-packager reason, changing logback scope to runtime caused it to not be shipped in our zip bundle, so this release was screwed up and we had to revert and release 3.0.1.1.

There won't be any more change on our logging system. If you have some classpath classes with your application sources, just use different classpaths (non dependent module, profiles, etc).

**Comment by testphreak** [comment]
Hi @slandelle I am fine with `gatling` shipping with `Logback` like before. I was in fact suggesting that above. 

Could you please revert @sebastianvoss's change to this [line](https://github.com/gatling/gatling/blob/7f4db686d0e3f37d622302861a3109cf59d4b2e3/gatling-app/src/main/scala/io/gatling/app/Gatling.scala#L88) and catch the `ClassNotFoundException` instead? That would resolve this issue.

I can send a pull request if you prefer that with the change below.

```
finally {
    try {
      LoggerFactory.getILoggerFactory.asInstanceOf[LoggerContext].stop()
    } catch {
      case e: ClassNotFoundException => logger.info(e.getMessage)
    }
}
```
Catching the exception would really help the logs look clean. Thank you.
