### ISSUE TITLE
Migration von Gatling 2.2.5 to 2.3.0 breaks Maven command line invocation with " java.lang.ClassNotFoundException: scala.Product$class"

### ISSUE THREAD

**Issue by sgoeschl** [gatling/gatling#3391]
When I migrated to Gatling 2.3.0 (after updating my pom.xml accordingly) I got a strange error when starting the Gatling simulation from the command line

```
mvn -Dgatling.simulationClass=computerdatabase.tenant.smoketest.Test clean gatling:test
```

results in

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.NoClassDefFoundError: scala/Product$class
	at scopt.Opt$.<init>(options.scala:143)
	at scopt.Opt$.<clinit>(options.scala)
	at scopt.OptionParser.opt(options.scala:255)
	at scopt.OptionParser.help(options.scala:281)
	at io.gatling.core.cli.GatlingOptionParser.help(GatlingOptionParser.scala:22)
	at io.gatling.app.cli.ArgsParser$$anon$1.<init>(ArgsParser.scala:29)
	at io.gatling.app.cli.ArgsParser.<init>(ArgsParser.scala:27)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:42)
	at io.gatling.app.Gatling$.main(Gatling.scala:35)
	at io.gatling.app.Gatling.main(Gatling.scala)
	... 6 more
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

After some investigation it seems (sorry but my Scala know-how is very/rather limited) that the `gatling-charts-highcharts-bundle` I'm using is pulling in `com.github.scopt:scopt_2.10:jar:3.7.0` which is very likely compiled with Scala 2.10.x

```
[INFO] +- io.gatling.highcharts:gatling-charts-highcharts-bundle:zip:bundle:2.3.0:provided
[INFO] |  +- org.scala-lang:scala-compiler:jar:2.12.3:provided
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.12.3:provided
[INFO] |  |  \- org.scala-lang.modules:scala-xml_2.12:jar:1.0.6:provided
[INFO] |  +- org.scala-lang:scala-library:jar:2.12.3:compile
[INFO] |  \- io.gatling:gatling-compiler:jar:2.3.0:provided
[INFO] |     +- com.typesafe:config:jar:1.3.1:provided
[INFO] |     +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |     +- ch.qos.logback:logback-classic:jar:1.2.3:provided
[INFO] |     |  \- ch.qos.logback:logback-core:jar:1.2.3:provided
[INFO] |     +- com.typesafe.zinc:zinc:jar:0.3.15:provided
[INFO] |     |  +- com.typesafe.sbt:incremental-compiler:jar:0.13.15:provided
[INFO] |     |  |  \- com.typesafe.sbt:sbt-interface:jar:0.13.15:provided
[INFO] |     |  \- com.typesafe.sbt:compiler-interface:jar:sources:0.13.15:provided
[INFO] |     \- com.github.scopt:scopt_2.10:jar:3.7.0:provided
```

The following snippet actually fixes my issue

```
        <dependency>
            <!-- Stand-alone Gatling distributable -->
            <groupId>io.gatling.highcharts</groupId>
            <artifactId>gatling-charts-highcharts-bundle</artifactId>
            <version>${gatling.version}</version>
            <classifier>bundle</classifier>
            <scope>provided</scope>
            <type>zip</type>
            <exclusions>
                <exclusion>
                    <groupId>com.github.scopt</groupId>
                    <artifactId>scopt_2.10</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.scopt</groupId>
            <artifactId>scopt_2.12</artifactId>
            <version>3.7.0</version>
        </dependency>
```

Please note that I might be using a rather esoteric Maven setup in https://github.com/sgoeschl/gatling-blueprint-project

**Comment by slandelle** [comment]
Not a bug.

Zinc 0.3.15 is the one pulling Scopt for Scala 2.10 and this is expected: until very recently, the Scala incremental compiler was only compiled against an old Scala version.
We've gone under major changes in next Gatling 3 so we can use latest Zinc that's available for Scala 2.12.

What you're doing might or might not work out of the box with Gatling 3, but your usage is not something we support. The bundle is not intended to be used as a maven artifact.

**Comment by sgoeschl** [comment]
Ok, I try to get rid of the "gatling-charts-highcharts-bundle" dependency :-)

**Comment by sgoeschl** [comment]
Done - was actually a redundant declaration ;-)
