### ISSUE TITLE
HTTP: Websocket logging unexpected message causes report generation crash

### ISSUE THREAD

**Issue by Sejten** [gatling/gatling#3404]
Websocket logging unexpected message in WsActor.scala:114 causes request end time timestamp to be 0 

> REQUEST	TableGamesTest	1		gatling.http.webSocket	1513945246743	0	OK	

which causes crash in generating reports

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1513945244
	at io.gatling.charts.stats.buffers.CountsBuffer.update(CountBuffer.scala:36)
	at io.gatling.charts.stats.buffers.ResponsesPerSecBuffers.updateResponsesPerSecBuffers(ResponsesPerSecBuffers.scala:33)
	at io.gatling.charts.stats.buffers.ResponsesPerSecBuffers.updateResponsesPerSecBuffers$(ResponsesPerSecBuffers.scala:32)
	at io.gatling.charts.stats.ResultsHolder.updateResponsesPerSecBuffers(ResultsHolder.scala:22)
	at io.gatling.charts.stats.ResultsHolder.addRequestRecord(ResultsHolder.scala:50)
`

Gatling version: 3.0.0-snapshot

**Comment by slandelle** [comment]
WebSocket support is in the process of being revamped in Gatling 3, see [example](https://github.com/gatling/gatling/blob/master/gatling-http/src/test/scala/io/gatling/http/Ws2CompileTest.scala) here.
Could you please give it a try?

**Comment by Sejten** [comment]
[This is example test that causes crash](https://gist.github.com/Sejten/511ea812be6ef8c2bbb9caac984ebbff)

**Comment by slandelle** [comment]
Thanks!
