### ISSUE TITLE
Gatling hangs at compile time on oracle jdk/jre > 8u151

### ISSUE THREAD

**Issue by slnowak** [gatling/gatling#3411]
I'm not sure if this issue should be submited here or rather to gatling-maven-plugin project, I will however give it a try.

We've recently realised our gatling tests started hanging infinitely from time to time, during the compilation phase. This happened after upgrading java from 8u151 to 8u152 and further.

I have an example project that should reproduce the bug. This is a maven project with simple simulation (BasicSimulation from here https://gatling.io/docs/2.3/quickstart/).
It also uses maven-gatling-plugin. 
I run gatling simulation by executing `mvn clean test`. The process is then repeated multiple times.

To simulate multiple java environments, I assume you have docker installed on your host. Here's how to reproduce the issue:
1. Clone the following repo https://github.com/slnowak/gatling-bug.git
2. Checkout ` java8-u151 ` branch. 
3. Build docker image: `docker build -t  gatling:java8-u151 . `
4. Start the container `docker run  gatling:java8-u151 `. This will run `mvn clean test` 10 times within a container with installed oracle jre 8u151. After that, docker container exits with 0, which means the entire load testing process is done.
5. Checkout ` java8-u162 ` branch. 
6. Build docker image: `docker build -t  gatling:java8-u162 .`
7. Start the container `docker run  gatling:java8-u162 `. This will run `mvn clean test` 10 times within a container with installed oracle jre 8u162. This time however, the process will hang at some point with `23:29:33.033 [main][WARN ][ZincCompiler.scala:142] i.g.c.ZincCompiler$ - Pruning sources from previous analysis, due to incompatible CompileSetup.`
8. The process could be nondeterministic - I just had to run `docker run  gatling:java8-u162 ` twice to reproduce the issue, so please repeat if necessary

Gatling version: 2.2.5
Gatling maven plugin version: 2.2.14

**Comment by slandelle** [comment]
Thanks for reporting.

Frankly, the fact that issue only happens with 8u162 and not 8u151 and the thread dump make me believe this is a JVM issue.

```
"main" #1 prio=5 os_prio=31 tid=0x00007ff18b80a800 nid=0x1703 waiting for monitor entry [0x0000700000214000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Runtime.loadLibrary0(Runtime.java:862)
	- waiting to lock <0x00000006c02e2498> (a java.lang.Runtime)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:573)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:571)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:571)
	at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
	at sun.nio.fs.BsdFileSystem.<init>(BsdFileSystem.java:41)
	at sun.nio.fs.MacOSXFileSystem.<init>(MacOSXFileSystem.java:44)
	at sun.nio.fs.MacOSXFileSystemProvider.newFileSystem(MacOSXFileSystemProvider.java:45)
	at sun.nio.fs.MacOSXFileSystemProvider.newFileSystem(MacOSXFileSystemProvider.java:38)
	at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
	at sun.nio.fs.BsdFileSystemProvider.<init>(BsdFileSystemProvider.java:36)
	at sun.nio.fs.MacOSXFileSystemProvider.<init>(MacOSXFileSystemProvider.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:65)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
	at java.nio.file.Paths.get(Paths.java:84)
        at io.gatling.commons.util.PathHelper$.string2path(PathHelper.scala:33)
        at io.gatling.core.config.GatlingFiles$.<init>(GatlingFiles.scala:26)
```

**Comment by slandelle** [comment]
Here it is: http://mail.openjdk.java.net/pipermail/core-libs-dev/2018-January/050819.html

**Comment by slnowak** [comment]
@slandelle so we either hawe to downgrade jdk or wait for 2.3.1?

**Comment by slandelle** [comment]
Yes

**Comment by slnowak** [comment]
Is it fixed on master already?

**Comment by honnel** [comment]
Any plans for next release to solve this issue?

**Comment by slandelle** [comment]
Probably next week
