### ISSUE TITLE
HTTP Recorder: IllegalArgumentException if URI in Request consists of path and query, only

### ISSUE THREAD

**Issue by cschabl** [gatling/gatling#3441]
1. Start the HTTP recorder.

```
recorder.bat
GATLING_HOME is set to "C:\Tools\gatling-charts-highcharts-bundle-2.3.1"
JAVA = ""C:\Program Files\Java\jdk1.8.0_131\bin\java.exe""
13:06:20.423 [WARN ] i.n.b.ServerBootstrap - Unknown channel option 'TCP_NODELAY' for channel '[id: 0x1100ef2e]'
```

2. Configure listening port and outgoing proxy. Leave remaining options on their defaults.

3. Send the following GET-Request:

```
GET /foo/v1/customers?firstName=Fred&lastName=Flintstone&phoneNo=%2B12+345+678+448+56 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiI4MjVkNzI5Zi03ZGFkLTQwZmQtODE3MC1jMWNiMGM2MjVjM2EiLCJpYXQiOjE1MjE0NjM5NzEsInN1YiI6ImNzY2hhYmxpIiwiYXVkIjoiQW55IiwiaXNzIjoiSW50ZWdyYXRpb25UZXN0IiwiZXhwIjoxNTIxNDY3NTcxLCJncnAiOlsiQ3VzdG9tZXJEYXRhQWRtaW4iXX0.ndEO64oRspTcNpRH2xp7CoHw6MQwNvEwZtL85Zfv4ta3sdbOkZZOxy1KVRiRiLQv04nHQpk-LTHrjxsi9DdbYA
Accept: application/json
User-Agent: Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)
Host: 127.0.0.1
Connection: keep-alive
```
4. Exception by recorder:
```
 i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: /foo/v1/customers?firstName=Fred&lastName=Flintstone&phoneNo=%2B12+345+678+448+56 could not be parsed into a proper Uri, missing scheme
        at org.asynchttpclient.uri.Uri.create(Uri.java:40)
        at org.asynchttpclient.uri.Uri.create(Uri.java:32)
        at io.gatling.recorder.scenario.RequestElement.<init>(ScenarioElement.scala:117)
        at io.gatling.recorder.scenario.RequestElement$.apply(ScenarioElement.scala:101)
        at io.gatling.recorder.controller.RecorderController.receiveResponse(RecorderController.scala:112)
        at io.gatling.recorder.http.handler.remote.RemoteHandler.handleResponse$1(RemoteHandler.scala:77)
        at io.gatling.recorder.http.handler.remote.RemoteHandler.channelRead(RemoteHandler.scala:97)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by slandelle** [comment]
Are you recording over HTTP or HTTPS?
If the former, it seems that the client you're using to record doesn't properly handle proxies: it should be generating an absolute url instead of a relative one.

**Comment by cschabl** [comment]
HTTP. 
I've confused the recorder options Outgoing proxy: host, HTTP, HTTPS with the coordinates of the target service. Is it possible to produce a more specific exception, saying that the client probably has no HTTP proxy set?

Thanks for the quick reply.

**Comment by slandelle** [comment]
I guess this mistake should be handled upstream, no sure where. Contributions welcome :)

**Comment by luvarqpp** [comment]
Just some hint (at least in source code) would be helpful. Do you like idea of adding some sentence to exception? I would make PR.

**Comment by slandelle** [comment]
@luvarqpp How is the message not explicit enough?

```
java.lang.IllegalArgumentException: /foo/v1/customers?firstName=Fred&lastName=Flintstone&phoneNo=%2B12+345+678+448+56 could not be parsed into a proper Uri, missing scheme
```

**Comment by luvarqpp** [comment]
> @luvarqpp How is the message not explicit enough? Could you please elaborate on your pain points?
> 
> ```
> java.lang.IllegalArgumentException: /foo/v1/customers?firstName=Fred&lastName=Flintstone&phoneNo=%2B12+345+678+448+56
> could not be parsed into a proper Uri, missing scheme
> ```

I would like to include possible causes/solutions. At least info about that relative url was used instead of absolute one and perhaps info that absolute urls are mandatory when there is correct proxy communication used.

I know that solutions in exceptions are not always correct (can be more confusing than relevant sometimes), but it could sometimes save some "google query" for new newbies.

What do you think?

**Comment by slandelle** [comment]
What are you doing exactly? If you're using the Recorder with a browser, there's no way a browser would generate an invalid HTTP request. What kind of user-agent are you using?

**Comment by luvarqpp** [comment]
I was trying SoapUI client on SoapUI mock server. I have made direct http request from SoapUI to gatling recorder. It has triggered this exception. After I have found information that proxy servers should receive absolute urls, I have changed endpoint url back to SoapUI mock server (localhost:8088) and I have configured SoapUI to use http proxy (gatling recorder running on localhost:8000).

**Comment by slandelle** [comment]
Could you please provide the exact stacktrace you got?

**Comment by luvarqpp** [comment]
Here it is:
```
05:49:13.781 [WARN ] i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: http:///mockCiselnikAdapterServiceBinding/ciselnik-method could not be parsed into a proper Uri, missing host
	at io.gatling.http.client.uri.Uri.create(Uri.java:95)
	at io.gatling.http.client.uri.Uri.create(Uri.java:84)
	at io.gatling.recorder.http.flows.Remote$.fromAbsoluteUri(MitmActorFSM.scala:37)
	at io.gatling.recorder.http.ServerHandler.channelRead(ServerHandler.scala:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

SoapUI:
 * proxy in settings set to None
 * inside I have running mock server on port 8088
 * I was calling directly gatling recorder, address http://localhost:8000/mockCiselnikAdapterServiceBinding/ciselnik-method

Gatling recorder:
 * running on port 8000
 * started from `Recorder.scala` helper class from Intelij IDE

No request hit the mock server in SoapUI and in Intelij run console, given exception is the only log message printed.

I can provide also tcp dump if needed. Just say so.
