### ISSUE TITLE
 java.util.NoSuchElementException: head of empty list

### ISSUE THREAD

**Issue by ypwu1** [gatling/gatling#3454]
run test gatling-charts-highcharts-bundle-2.3.1 with Mac OS Sierra:

Parsing log file(s)...
Exception in thread "main" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:428)
	at scala.collection.immutable.Nil$.head(List.scala:425)
	at scala.collection.generic.TraversableForwarder.head(TraversableForwarder.scala:56)
	at scala.collection.generic.TraversableForwarder.head$(TraversableForwarder.scala:56)
	at scala.collection.mutable.ListBuffer.head(ListBuffer.scala:44)
	at io.gatling.charts.stats.LogFileReader.firstPass(LogFileReader.scala:122)
	at io.gatling.charts.stats.LogFileReader.$anonfun$x$4$1(LogFileReader.scala:125)
	at io.gatling.charts.stats.LogFileReader.parseInputFiles(LogFileReader.scala:63)
	at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:125)
	at io.gatling.app.RunResultProcessor.initLogFileReader(RunResultProcessor.scala:67)
	at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:49)
	at io.gatling.app.Gatling$.start(Gatling.scala:68)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
	at io.gatling.app.Gatling$.main(Gatling.scala:37)
	at io.gatling.app.Gatling.main(Gatling.scala)

**Comment by slandelle** [comment]
Could you please provide a way to reproduce your issue on our side?

**Comment by ypwu1** [comment]
@slandelle  just run the gatling test with official sample, the error should occur. No problem switch back to gatling-charts-highcharts-bundle-2.3.0

**Comment by slandelle** [comment]
I ran all 6 sample shipped in gatling-charts-highcharts-bundle-2.3.1 and didn't get any issue.

**Comment by ypwu1** [comment]
I run it today, seems it's back to normal now. not sure what causing this error yesterday. please close
