### ISSUE TITLE
ElParserException occurred on Java10.0.1

### ISSUE THREAD

**Issue by petitviolet** [gatling/gatling#3500]
Make sure these checkboxes are checked before submitting your issue. Thanks you!

We are using Galing 2.3.1 with SBT plugin 2.2.2 and Java 10.0.1

Java version detail is below.

```shell-session
$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

SBT plugin settings are below.

```scala
// /project/plugins.sbt
addSbtPlugin("io.gatling" % "gatling-sbt" % "2.2.2")

// /build.sbt
lazy val perfTest = (project in file("modules/perfTest"))
  .enablePlugins(GatlingPlugin)
  .settings(
    name := "perfTest",
    scalacOptions := Nil,
    libraryDependencies ++= {
      val gatlingVersion = "2.3.1"
      List(
        "io.gatling.highcharts" % "gatling-charts-highcharts" % gatlingVersion % Test,
        "io.gatling" % "gatling-test-framework" % gatlingVersion % Test
      )
    }
  )
```

All of reproduce codes are below.

```scala
package sample

import io.gatling.core.Predef._
import io.gatling.core.scenario.Simulation
import io.gatling.http.Predef._

import scala.concurrent.duration._

class MyScenario extends Simulation {
  val body = """{"id": 1}"""

  setUp(
    scenario(s"sample")
      .exec {
        http("sample")
          .post("/")
          .body(StringBody(body))
          .asJSON
      }
      .inject(
        constantUsersPerSec(10) during 10.seconds
      )
  ).assertions(global.successfulRequests.percent.is(100))

}
```

When we run this load test, and then we are given ElParserException.

```
$ sbt 'project perfTest' 'gatling:testOnly sample.MyScenario'
...
io.gatling.core.session.el.ElParserException: Failed to parse sample with error '[B cannot be cast to [C'
     at io.gatling.core.session.el.ElCompiler.parseEl(ElCompiler.scala:249)
     at io.gatling.core.session.el.ElCompiler$.parse(ElCompiler.scala:171)
     at io.gatling.core.session.el.ElCompiler$.compile(ElCompiler.scala:174)
     at io.gatling.core.session.el.package$El$.el$extension(package.scala:26)
     at io.gatling.core.ValidationImplicits.stringToExpression(ValidationImplicits.scala:48)
     at io.gatling.core.ValidationImplicits.stringToExpression$(ValidationImplicits.scala:48)
     at io.gatling.core.Predef$.stringToExpression(Predef.scala:22)
     at sample.MyScenario.<init>(MyScenario.scala:15)
     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
     at java.base/java.lang.Class.newInstance(Class.java:560)
     at io.gatling.app.Runner.run0(Runner.scala:79)
     at io.gatling.app.Runner.run(Runner.scala:64)
     at io.gatling.app.Gatling$.start(Gatling.scala:63)
     at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
     at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
     at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
     at sbt.ForkMain$Run$2.call(ForkMain.java:301)
     at sbt.ForkMain$Run$2.call(ForkMain.java:291)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
     at java.base/java.lang.Thread.run(Thread.java:844)
Simulation MyScenario failed.
```

When we run this load test on Java1.8.0, got succeeded.

**Comment by petitviolet** [comment]
Thanks for your reply and document!

**Comment by slandelle** [comment]
FYI, Java 11 support will land in Gatling 3.
Cheers
