### ISSUE TITLE
HTTP: virtual users get forked on connect timeout

### ISSUE THREAD

**Issue by niclasnilsson** [gatling/gatling#3546]
I run a very simple load test, just a scenario containing one simple GET request, and then run `constantUsersPerSec(5) during (15 minutes)`. The system under test doesn't respond well after a while and returns a lot of 500. At those times, gatling 3.0.0-RC2 ends up with a negative amount of active users and never finishes. It continues to write the status to stdout, but it never finishes and thereby doesn't produce a report.

```
---- Get customer --------------------------------------------------------------
[############################################################################]102%
          waiting: 0      / active: -122   / done: 4622
================================================================================
```
Some sort of bug I assume?

**Comment by niclasnilsson** [comment]
I can repeat it and it seems like the first time it hits negative is after a timeout:

```
16:33:15.826 [WARN ] i.g.h.e.GatlingHttpListener - Request 'getCustomersByCustomerId' failed for user 238
io.netty.channel.ConnectTimeoutException: connection timed out: [domain edited out]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
16:33:15.832 [ERROR] i.g.h.e.r.DefaultStatsProcessor - Request 'getCustomersByCustomerId' failed for user 238: i.n.c.ConnectTimeoutException: connection timed out: [domain edited out]

================================================================================
2018-09-28 16:33:15                                          90s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=264    KO=5     )
> getCustomersByCustomerId                                 (OK=264    KO=5     )
---- Errors --------------------------------------------------------------------
> i.n.c.ConnectTimeoutException: connection timed out: customer-      3 (60,00%)
[domain edited out]
> i.g.h.c.i.RequestTimeout$RequestTimeoutException: Request time      2 (40,00%)
out after 60000 ms

---- Get customer --------------------------------------------------------------
[###                                                                       ]  4%
          waiting: 5132   / active: -1     / done: 269
================================================================================
```

**Comment by slandelle** [comment]
Is there any chance your scenario involves redirects?

**Comment by slandelle** [comment]
I could reproduce on my side, investigating.

**Comment by slandelle** [comment]
Fixed, thanks a lot for reporting!

**Comment by niclasnilsson** [comment]
Thanks for fixing it!

**Comment by PallaviReddy1401** [comment]
how did we resolve this issue?
I'm seeing same error : > i.n.c.ConnectTimeoutException: connection timed out: [Client domain] during Load Test after 15min into the test.

**Comment by slandelle** [comment]
@PallaviReddy1401 Please don't hijack closed issues.
