### ISSUE TITLE
Gatling 3.0.0-RC3 - Unable to load the library 'netty_tcnative_osx_x86_64'

### ISSUE THREAD

**Issue by damianbl** [gatling/gatling#3556]
[desc]
Run Gatling 3.0.0-RC3, when the tests starts it throws exceptions.

[environment]

    OS: Mac OS Mojave
    Java:

```
Java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```
  SBT: 0.13.15

[reproduce]

- test

```
package performance

import io.gatling.core.Predef._
import io.gatling.core.structure.ScenarioBuilder
import io.gatling.http.Predef._
import io.gatling.http.protocol.HttpProtocolBuilder

class SearchScenario extends Simulation {
  val httpProtocol: HttpProtocolBuilder = http.baseUrl("https://www.google.com")

  val scn: ScenarioBuilder = scenario("Gatling3 test google")
    .exec(http("index page")
      .get("/")
      .check(status.is(200)))
    .exec(http("query 'Gatling the load test tool'")
      .get("/search?q=Gatling+the+load+test+tool&oq=Gatling+the+load+test+tool")
      .check(status.is(200))
    )

  setUp(
    scn.inject(
      atOnceUsers(1)
    )
  ).protocols(httpProtocol)
    .assertions(
      global.responseTime.mean.lte(3000)
    )
}
```

- run:
`sbt "gatling:testOnly performance.SearchScenario"`

[result]
```

10:58:14.071 [pool-1-thread-1] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_tcnative_osx_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:202)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:191)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:776)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452)
	at io.gatling.http.client.impl.DefaultHttpClient.<init>(DefaultHttpClient.java:239)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClient(HttpClientFactory.scala:101)
	at io.gatling.http.engine.HttpEngine$.apply(HttpEngine.scala:44)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:54)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$1(Protocol.scala:68)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.componentsFactory$1(Protocol.scala:68)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:70)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:72)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:72)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:26)
	at io.gatling.http.action.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:35)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:85)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:100)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:194)
	at scala.collection.immutable.List.map(List.scala:282)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:194)
	at io.gatling.app.Runner.run0(Runner.scala:92)
	at io.gatling.app.Runner.run(Runner.scala:61)
	at io.gatling.app.Gatling$.start(Gatling.scala:74)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:52)
	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:51)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by slandelle** [comment]
Those are DEBUG logs, not errors. Just ignore them (you're not even supposed to have DEBUG enabled on Netty in production).

FYI, Netty has a fallback mechanism. A few lined below this stacktrace, you should see something like `i.n.u.i.NativeLibraryLoader - Successfully loaded the library /var/folders/3m/b2yp9rr56s30thdsxrq7hy200000gn/T/libnetty_tcnative_osx_x86_644093229984461983342.dylib`.
