### ISSUE TITLE
Core: feeders instances should be handled as distinct even though they are equals

### ISSUE THREAD

**Issue by h0nIg** [gatling/gatling#3585]
* Regarding issues:
  * [x] Check that you can reproduce your issue with latest Gatling version
  * [x] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [x] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.

Gatling does ignore the uniqueness of my feeder list and stores it internally. Therefore the feeder will run out of entries but it should not. It looks like this is the problematic line which ignores the uniqueness: https://github.com/gatling/gatling/blob/b7617bb05e895558da9c71c70df13c6db34d8951/gatling-core/src/main/scala/io/gatling/core/action/builder/FeedBuilder.scala#L30

```scala
Exception in thread "main" java.lang.IllegalStateException: Feeder is now empty, stopping engine
	at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.applyOrElse(SingletonFeed.scala:61)
	at akka.actor.Actor$class.aroundReceive$$$capture(Actor.scala:517)
	at akka.actor.Actor$class.aroundReceive(Actor.scala)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:23)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

```
class MySimulation extends Simulation {
  val feeder = List(Map("test1" -> "val1"), Map("test2" -> "val2"))

  val scn1 = scenario("test1")
    .feed(feeder.toArray.queue)
    .exec({session:Session => println("GO TEST1 " + session.userId); session})

  val scn2 = scenario("test2")
    .feed(feeder.toArray.queue)
    .exec({session:Session => println("GO TEST2 " + session.userId); session})

  setUp(
    scn1.inject(atOnceUsers(feeder.size)),
    scn2.inject(atOnceUsers(feeder.size))
  ).protocols(....)
}
```

**Comment by slandelle** [comment]
Thanks for reporting!
