### ISSUE TITLE
HTTP: Gatling shouldn't resolve remote address when connecting through a proxy

### ISSUE THREAD

**Issue by scramados** [gatling/gatling#3597]
After upgrading to Gatling 3.0.0 doesn't seem to work with our proxy. I am trying to access our pre production environment, an external web page that can only be accessed from a small number of IP addresses (like our proxy). This did work in 2.3.1 but stopped working after i upgraded.

I have already tried to clear my DNS cache but this didn't resolve the issue.

StackTrace:
```
java.net.UnknownHostException: "https://customer-pre-production.company.com/Application/Logon"
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at io.gatling.http.resolver.ShuffleJdkNameResolver.doResolveAll(ShuffleJdkNameResolver.scala:33)
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81)
	at io.gatling.http.cache.DnsCacheSupport$$anon$1.resolveAll(DnsCacheSupport.scala:124)
	at io.gatling.http.client.impl.DefaultHttpClient.resolveRemoteAddresses(DefaultHttpClient.java:441)
	at io.gatling.http.client.impl.DefaultHttpClient.sendTx(DefaultHttpClient.java:338)
	at io.gatling.http.client.impl.DefaultHttpClient.lambda$sendRequest$0(DefaultHttpClient.java:247)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Http configuration:
 ```
 val httpProtocol: HttpProtocolBuilder = http
        .baseURL(Properties.intranetURL)
        .warmUp(Properties.intranetURL)
        .inferHtmlResources(BlackList(Properties.blackList), WhiteList())
        .proxy(Proxy("proxy.company.local", 3128).httpsPort(3128))
        .noProxyFor("test325.company.local", "test078.company.local", "localhost")
        .acceptHeader("application/json, text/javascript, */*; q=0.01")
        .maxConnectionsPerHostLikeIE7
        .acceptEncodingHeader("gzip, deflate")
        .acceptLanguageHeader("en-US,en;q=0.5")
        .userAgentHeader("Gatling/3.0.0")
```

**Comment by slandelle** [comment]
Thanks for reporting!

**Comment by scramados** [comment]
@slandelle Can you give any indication when version 3.0.1 will be released?

**Comment by slandelle** [comment]
Most likely second half of November

**Comment by scramados** [comment]
The error still occurs but with a slightly different stacktrace
```
java.net.UnknownHostException: customer-pre-production.company.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:170)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:156)
	at io.gatling.http.client.impl.DefaultHttpClient.openNewChannelRec(DefaultHttpClient.java:602)
	at io.gatling.http.client.impl.DefaultHttpClient.openNewChannel(DefaultHttpClient.java:576)
	at io.gatling.http.client.impl.DefaultHttpClient.sendTxWithNewChannel(DefaultHttpClient.java:480)
	at io.gatling.http.client.impl.DefaultHttpClient.lambda$sendTx$2(DefaultHttpClient.java:363)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenerWithStackOverFlowProtection(DefaultPromise.java:454)
	at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:413)
	at io.netty.util.concurrent.CompleteFuture.addListener(CompleteFuture.java:49)
	at io.gatling.http.client.impl.DefaultHttpClient.sendTx(DefaultHttpClient.java:345)
	at io.gatling.http.client.impl.DefaultHttpClient.lambda$sendRequest$0(DefaultHttpClient.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by slandelle** [comment]
@scramados Sorry, I can't reproduce and Gatling works as expected on my side. I suspect the problem is on your side as

```
at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:156)
at io.gatling.http.client.impl.DefaultHttpClient.openNewChannelRec(DefaultHttpClient.java:602)
```
means you're trying to open a connection directly to `customer-pre-production.company.com` instead of your proxy.

**Comment by scramados** [comment]
The same code works in version 2.3.1. The only changes made are the ones mentioned in the migration notes. 
When adding a breakpoint  to the mentioned code the proxyServer object is filled with the proper configuration.
It looks like it doesn't work for https because when i change the url from https to http i am able to reach the server and retrieve a 404 response.
My current proxy configuraiton is `Proxy("proxy2.dev.local", 3128).httpsPort(3128)`
@slandelle if necessary i could setup a call so i can share my screen

**Comment by slandelle** [comment]
Sadly, the issue is in Netty: https://github.com/netty/netty/issues/8589

**Comment by slandelle** [comment]
Note: what I actually fixed in 3.0.1 was proxy connection over plain HTTP. The issue is still there over HTTPS as the mechanism is different.

**Comment by slandelle** [comment]
@mailtoshrb compared to 3.0.1, 3.0.1.1 only contains one single: logback not shipped in the bundle.
The fix for this issue will be shipped in 3.0.2.
Then, your stacktrace shows you’re using Gatling 2, not Gatling 3. We no longer use org.asynchttpclient.

**Comment by mailtoshrb** [comment]
@slandelle Thanks for the update, we installed both old and new versions in the same server and somewhere it was referencing to old version so seen above exceptionsc(resolved it now). We have workaround for now for proxy redirection and will wait until gatling 3.0.2 release,  it would be great if you throw some light when this new version will be out?

**Comment by slandelle** [comment]
> it would be great if you throw some light when this new version will be out?

Most likely mid-December
