### ISSUE TITLE
Gatling 3.0.0 on RHEL7 - "Failed to load any of the given libraries: [netty_tcnative_linux_x86_32, netty_tcnative_linux_x86_32_fedora, netty_tcnative_x86_32, netty_tcnative]"

### ISSUE THREAD

**Issue by mattrosendin** [gatling/gatling#3611]
**Description**:

Running the basic simulation on a fresh install on RHEL 7 results in the below error. Worked fine on macOS.

**Environment**:

OS: Red Had Enterprise Linux 7
Gatling version: 3.0.0
Java version: Java(TM) SE Runtime Environment (build 1.8.0_191-b12)

**Error**:

```
[myuser@host gatling-charts-highcharts-bundle-3.0.0]$ ./bin/gatling.sh
GATLING_HOME is set to /home/myuser/gatling-charts-highcharts-bundle-3.0.0
Choose a simulation number:
     [0] computerdatabase.BasicSimulation
     [1] computerdatabase.advanced.AdvancedSimulationStep01
     [2] computerdatabase.advanced.AdvancedSimulationStep02
     [3] computerdatabase.advanced.AdvancedSimulationStep03
     [4] computerdatabase.advanced.AdvancedSimulationStep04
     [5] computerdatabase.advanced.AdvancedSimulationStep05
0
Select run description (optional)

18:07:50.529 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_32, netty_tcnative_linux_x86_32_fedora, netty_tcnative_x86_32, netty_tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	... 38 common frames omitted
	Suppressed: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_32.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32 in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32 in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 common frames omitted
	Wrapped by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_32
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 common frames omitted
	Suppressed: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_32_fedora.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32_fedora in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32_fedora in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 common frames omitted
	Wrapped by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_32_fedora
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 common frames omitted
	Suppressed: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_32.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_32 in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_32 in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 common frames omitted
	Wrapped by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_32
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 common frames omitted
	Suppressed: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 common frames omitted
	Wrapped by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 common frames omitted
Wrapped by: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:346)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:202)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:191)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:776)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452)
	at io.gatling.http.util.SslContextsFactory.newSslContexts(SslContexts.scala:96)
	at io.gatling.http.engine.DefaultHttpClientFactory.newSslContexts(HttpClientFactory.scala:86)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClientConfig(HttpClientFactory.scala:60)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClient(HttpClientFactory.scala:80)
	at io.gatling.http.engine.HttpEngine$.apply(HttpEngine.scala:47)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:54)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$1(Protocol.scala:68)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.componentsFactory$1(Protocol.scala:68)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:70)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:72)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:72)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:26)
	at io.gatling.http.action.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:35)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:85)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:100)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:194)
	at scala.collection.immutable.List.map(List.scala:282)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:194)
	at io.gatling.app.Runner.run0(Runner.scala:92)
	at io.gatling.app.Runner.run(Runner.scala:61)
	at io.gatling.app.Gatling$.start(Gatling.scala:74)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
	at io.gatling.app.Gatling$.main(Gatling.scala:39)
	at io.gatling.app.Gatling.main(Gatling.scala)
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:346)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:202)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:191)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:776)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452)
	at io.gatling.http.util.SslContextsFactory.newSslContexts(SslContexts.scala:96)
	at io.gatling.http.engine.DefaultHttpClientFactory.newSslContexts(HttpClientFactory.scala:86)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClientConfig(HttpClientFactory.scala:60)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClient(HttpClientFactory.scala:80)
	at io.gatling.http.engine.HttpEngine$.apply(HttpEngine.scala:47)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:54)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$1(Protocol.scala:68)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.componentsFactory$1(Protocol.scala:68)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:70)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:72)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:72)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:26)
	at io.gatling.http.action.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:35)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:85)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:100)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:194)
	at scala.collection.immutable.List.map(List.scala:282)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:194)
	at io.gatling.app.Runner.run0(Runner.scala:92)
	at io.gatling.app.Runner.run(Runner.scala:61)
	at io.gatling.app.Gatling$.start(Gatling.scala:74)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
	at io.gatling.app.Gatling$.main(Gatling.scala:39)
	at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_32, netty_tcnative_linux_x86_32_fedora, netty_tcnative_x86_32, netty_tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	... 38 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_32
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_32.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32 in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32 in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_32_fedora
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_32_fedora.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32_fedora in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_32_fedora in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_32
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_32.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_32 in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_32 in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 40 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 41 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
			at java.lang.ClassLoader.loadLibrary(Unknown Source)
			at java.lang.Runtime.loadLibrary0(Unknown Source)
			at java.lang.System.loadLibrary(Unknown Source)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 41 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
				at java.lang.ClassLoader.loadLibrary(Unknown Source)
				at java.lang.Runtime.loadLibrary0(Unknown Source)
				at java.lang.System.loadLibrary(Unknown Source)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
				at java.lang.reflect.Method.invoke(Unknown Source)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 42 more
```

**Comment by slandelle** [comment]
Wow, 32 bits, really???

We're going to try to fall back to using JDK's SSLEngine as the native libs we use are only compiled in 64 bits.
But frankly, you'd better use a 64 bits OS, we're in late 2018...

**Comment by slandelle** [comment]
Thanks for reporting!
