### ISSUE TITLE
Gatling does not start on MacOS

### ISSUE THREAD

**Issue by achikin** [gatling/gatling#3665]
Gatling does not start on MacOS.

### Steps to reproduce:
1. Download gatling from here https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.0.3/gatling-charts-highcharts-bundle-3.0.3-bundle.zip
2. Unpack
3. run `./bin/recorder.sh`
The following trace appears
```
~/src/gatling → ./bin/recorder.sh
GATLING_HOME is set to /Users/achikin/src/gatling
Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab6 0064 04a0 001e b200 c1b2 00c6 04bd
    0x0000010: 0002 5903 2a53 c000 c8b6 00cc b600 d0c0
    0x0000020: 00d2 b02a b600 38b8 0042 3c1b 04a4 0156
    0x0000030: 1b05 6c3d 2a1b 056c 2ab6 0038 b700 d43e
    0x0000040: 2ab6 0038 021d 787e 3604 2ab6 0038 0210
    0x0000050: 201d 647c 7e36 05bb 0019 59b2 00c6 2ab6
    0x0000060: 003a c000 c8b6 00d8 b700 db1c b600 df3a
    0x0000070: 0619 06c6 001a 1906 b600 e3c0 008b 3a07
    0x0000080: 1906 b600 e6c0 008b 3a08 a700 0dbb 00e8
    0x0000090: 5919 06b7 00eb bf19 073a 0919 083a 0abb
    0x00000a0: 0002 5915 0419 09bb 0019 59b2 00c6 1909
    0x00000b0: c000 c8b6 00d8 b700 db03 b800 f13a 0e3a
    0x00000c0: 0d03 190d b900 f501 0019 0e3a 1136 1036
    0x00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    0x00000e0: 150f b900 f802 00c0 0005 3a17 1911 1917
    0x00000f0: b800 fc3a 1136 1036 0fa7 ffd8 1911 b801
    0x0000100: 00b7 0069 3a0b bb00 0259 1505 190a bb00
    0x0000110: 1959 b200 c619 0ac0 00c8 b600 d8b7 00db
    0x0000120: 03b8 00f1 3a13 3a12 0319 12b9 00f5 0100
    0x0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0x0000140: 1404 6015 1519 1215 14b9 00f8 0200 c000
    0x0000150: 053a 1819 1619 18b8 0103 3a16 3615 3614
    0x0000160: a7ff d819 16b8 0100 b700 693a 0cbb 0105
    0x0000170: 5919 0bbb 0105 5919 0cb2 010a b701 0db7
    0x0000180: 010d b02a b600 3a03 32b6 010f b0
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118]},{})
    append_frame(@151,Object[#139],Object[#139])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Top,Top,Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#139]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Top,Top,Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#139]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Object[#2],Top,Object[#25],Object[#62],Integer,Integer,Object[#116],Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#139]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Object[#2],Top,Object[#25],Object[#62],Integer,Integer,Object[#116],Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#139]})
    full_frame(@387,{Object[#2],Integer},{})

	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:185)
	at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:220)
	at scala.collection.immutable.HashMap.updated(HashMap.scala:62)
	at scala.collection.immutable.Map$Map4.updated(Map.scala:227)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:228)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:200)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:32)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:28)
	at scala.collection.TraversableOnce.$anonfun$toMap$1(TraversableOnce.scala:320)
	at scala.collection.TraversableOnce$$Lambda$79/1888442711.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:319)
	at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:317)
	at scala.collection.AbstractTraversable.toMap(Traversable.scala:108)
	at scala.concurrent.duration.Duration$.<init>(Duration.scala:92)
	at scala.concurrent.duration.Duration$.<clinit>(Duration.scala)
	at scala.concurrent.duration.package$DurationInt$.durationIn$extension(package.scala:56)
	at scala.concurrent.duration.package$DurationInt.durationIn(package.scala:56)
	at scala.concurrent.duration.DurationConversions.milliseconds(DurationConversions.scala:32)
	at scala.concurrent.duration.DurationConversions.milliseconds$(DurationConversions.scala:32)
	at scala.concurrent.duration.package$DurationInt.milliseconds(package.scala:55)
	at scala.concurrent.duration.DurationConversions.millis(DurationConversions.scala:33)
	at scala.concurrent.duration.DurationConversions.millis$(DurationConversions.scala:33)
	at scala.concurrent.duration.package$DurationInt.millis(package.scala:55)
	at io.gatling.core.config.GatlingConfiguration$.mapToGatlingConfig(GatlingConfiguration.scala:182)
	at io.gatling.core.config.GatlingConfiguration$.load(GatlingConfiguration.scala:105)
	at io.gatling.recorder.config.RecorderConfiguration$.<init>(RecorderConfiguration.scala:53)
	at io.gatling.recorder.config.RecorderConfiguration$.<clinit>(RecorderConfiguration.scala)
	at io.gatling.recorder.GatlingRecorder$.initRecorder(GatlingRecorder.scala:39)
	at io.gatling.recorder.GatlingRecorder$.$anonfun$fromArgs$1(GatlingRecorder.scala:32)
	at io.gatling.recorder.GatlingRecorder$$$Lambda$64/1635756693.apply(Unknown Source)
	at scala.Option.map(Option.scala:163)
	at io.gatling.recorder.GatlingRecorder$.fromArgs(GatlingRecorder.scala:32)
	at io.gatling.recorder.GatlingRecorder$.main(GatlingRecorder.scala:28)
	at io.gatling.recorder.GatlingRecorder.main(GatlingRecorder.scala)
```
### Java version
```
~/src/gatling → java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
```
### MacOS version
![image](https://user-images.githubusercontent.com/611419/52204679-e50b5f80-2885-11e9-9525-c4f5ee632475.png)

**Comment by slandelle** [comment]
Your jdk is super old and is most likely buggy. Please upgrade jdk.

**Comment by achikin** [comment]
@slandelle 
![image](https://user-images.githubusercontent.com/611419/52207813-9cf13a80-288f-11e9-8e82-e4b428e93d51.png)
