### ISSUE TITLE
Recorder: IllegalArgumentException "missing scheme"

### ISSUE THREAD

**Issue by stoerr** [gatling/gatling#3686]
When recording just a click on https://gatling.io/ and saving the simulation, I get an IllegalArgumentException.

Steps to reproduce:
- download version 3.0.3, open bin/recorder.sh and start recording with default settings
- switch proxy of Chrome browser to gatling (I used the SwitchyOmega plugin)
- open https://gatling.io/ in browser
- hit "stop & save"

Expected Result: there should be a RecordedSimulation

Actual Result: the RecordedSimulation is not saved, and in the output there is the follwoing exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: gatling.io could not be parsed into a proper Uri, missing scheme
	at io.gatling.http.client.ahc.uri.Uri.create(Uri.java:92)
	at io.gatling.http.client.ahc.uri.Uri.create(Uri.java:84)
	at io.gatling.recorder.scenario.template.SimulationTemplate$.$anonfun$render$7(SimulationTemplate.scala:110)
	at io.gatling.recorder.scenario.template.SimulationTemplate$.$anonfun$render$7$adapted(SimulationTemplate.scala:110)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:250)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:248)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:262)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:262)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at io.gatling.recorder.scenario.template.SimulationTemplate$.render(SimulationTemplate.scala:110)
	at io.gatling.recorder.scenario.ScenarioExporter$.renderScenarioAndDumpBodies(ScenarioExporter.scala:173)
	at io.gatling.recorder.scenario.ScenarioExporter$.saveScenario(ScenarioExporter.scala:78)
	at io.gatling.recorder.controller.RecorderController.stopRecording(RecorderController.scala:78)
	at io.gatling.recorder.ui.RecorderFrontEnd.stopRecording(RecorderFrontEnd.scala:66)
	at io.gatling.recorder.ui.swing.frame.RunningFrame.$anonfun$stopButton$1(RunningFrame.scala:50)
	at scala.swing.Action$$anon$1.apply(Action.scala:59)
	at scala.swing.Action$$anon$2.actionPerformed(Action.scala:77)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by slandelle** [comment]
Thanks for reporting. I’ll have a look as this is not the expected Exception.

> Expected Result: there should be a RecordedSimulation

No, that’s not the expected result. You should get blocked by your browser with a security error. Real websites with valid certs can’t be recorded with default settings, you must use the CA mode. Please read the recorder’s documentation page.

**Comment by stoerr** [comment]
I was using "self-signed certificate" mode, which provokes a warning in Chrome, but that can be ignored. Then the requests show up nicely in the recorder with all information - it's just the saving that breaks.

**Comment by stoerr** [comment]
@slandelle I don't agree that I should get blocked with a security error. Gatling isn't just for load testing public sites, which can be expected to have a valid certificate, but it'll be used to check testing systems, which usually don't have a valid certificate. OK, the CA mode solves that, too, at the expense of more configuration. But since it's possible to access the site also in Self-signed certificate after accepting a warning, why should the Gatling Recorder block it? So, maybe you should have some mercy with those who don't want to mess with the browsers keystore. In quite a lot of corporate environments you can't even do this, since you don't have administrative rights for your computer.

**Comment by k-spit** [comment]
Problem still exists

`Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: gatling.io could not be parsed into a proper Uri, missing scheme
	at io.gatling.http.client.ahc.uri.Uri.create(Uri.java:92)
	at io.gatling.http.client.ahc.uri.Uri.create(Uri.java:84)
	at io.gatling.recorder.scenario.template.SimulationTemplate$.$anonfun$render$7(SimulationTemplate.scala:110)
	at io.gatling.recorder.scenario.template.SimulationTemplate$.$anonfun$render$7$adapted(SimulationTemplate.scala:110)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:250)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:248)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:262)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:262)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at io.gatling.recorder.scenario.template.SimulationTemplate$.render(SimulationTemplate.scala:110)
	at io.gatling.recorder.scenario.ScenarioExporter$.renderScenarioAndDumpBodies(ScenarioExporter.scala:173)
	at io.gatling.recorder.scenario.ScenarioExporter$.saveScenario(ScenarioExporter.scala:78)
	at io.gatling.recorder.controller.RecorderController.stopRecording(RecorderController.scala:78)
	at io.gatling.recorder.ui.RecorderFrontEnd.stopRecording(RecorderFrontEnd.scala:66)
	at io.gatling.recorder.ui.swing.frame.RunningFrame.$anonfun$stopButton$1(RunningFrame.scala:50)
	at scala.swing.Action$$anon$1.apply(Action.scala:59)
	at scala.swing.Action$$anon$2.actionPerformed(Action.scala:77)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by slandelle** [comment]
@k-spit 3.1.0 hasn't been released yet, so except if you've built master from sources, you don't have the fix.
