### ISSUE TITLE
Assertions broke since 3.1.0.1

### ISSUE THREAD

**Issue by jgaalen** [gatling/gatling#3713]
Assertions fail with the following error when generating the report:

```Parsing log file(s)...
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.IllegalArgumentException: Unknown object coding: 3
	at boopickle.UnpickleState.codingError(Pickler.scala:551)
```

Example code from the example gatling demo:
```
  setUp(scn.inject(atOnceUsers(1)).protocols(httpProtocol)).assertions(
    global.responseTime.max.lt(50),
    global.successfulRequests.percent.gt(95)
  )
```

**Comment by slandelle** [comment]
Thanks for reporting, we're going to release 3.1.1.
