### ISSUE TITLE
Parsing log file: IllegalArgumentException when unpickle

### ISSUE THREAD

**Issue by fhiegel** [gatling/gatling#3714]
Hello,
I don't have any problem when I use Gatling **3.0.3:**
```
Simulation MySimulation completed in 4 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...
```

I'm meeting this issue every time I run my simulation on Gatling **3.1.0** and **3.1.0.1**: 
```java
Simulation MySimulation completed in 4 seconds
Parsing log file(s)...
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
        at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.IllegalArgumentException: Unknown object coding: 2
        at boopickle.UnpickleState.codingError(Pickler.scala:551)
        at io.gatling.charts.stats.LogFileReader$Pickler$macro$1$1$TraitPickler$macro$51$1$Pickler$macro$52$1$.unpickle(LogFileReader.scala:108)
        at io.gatling.charts.stats.LogFileReader$Pickler$macro$1$1$TraitPickler$macro$51$1$Pickler$macro$52$1$.unpickle(LogFileReader.scala:108)
        at boopickle.CompositePickler.unpickle(CompositePicklers.scala:40)
        at boopickle.UnpickleState.unpickle(Pickler.scala:586)
        at io.gatling.charts.stats.LogFileReader$Pickler$macro$1$1$.unpickle(LogFileReader.scala:108)
        at io.gatling.charts.stats.LogFileReader$Pickler$macro$1$1$.unpickle(LogFileReader.scala:108)
        at boopickle.UnpickleImpl$UnpickledCurry.fromBytes(Default.scala:99)
        at io.gatling.charts.stats.LogFileReader.$anonfun$firstPass$1(LogFileReader.scala:108)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at io.gatling.charts.stats.LogFileReader.firstPass(LogFileReader.scala:86)
        at io.gatling.charts.stats.LogFileReader.$anonfun$x$4$1(LogFileReader.scala:125)
        at io.gatling.charts.stats.LogFileReader.parseInputFiles(LogFileReader.scala:63)
        at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:125)
        at io.gatling.app.RunResultProcessor.initLogFileReader(RunResultProcessor.scala:50)
        at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:32)
        at io.gatling.app.Gatling$.start(Gatling.scala:81)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:46)
        at io.gatling.app.Gatling$.main(Gatling.scala:38)
        at io.gatling.app.Gatling.main(Gatling.scala)
        ... 6 more
```

I'm using: 
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\opt\apache-maven-3.6.0
Java version: 10.0.2, vendor: Azul Systems, Inc., 
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

Maven command line :
```
mvn clean -Pgatling gatling:test -Dgatling.simulationClass=MySimulation
```

POM File :
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>my.group</groupId>
    <version>0.0.0.3</version>
    <artifactId>amazing-app</artifactId>

    <properties>
        <encoding>UTF-8</encoding>
        <scala.version>2.12.8</scala.version>
        <scala-maven-plugin.version>4.0.1</scala-maven-plugin.version>

        <gatling.version>3.0.3</gatling.version>
        <gatling-maven-plugin.version>3.0.2</gatling-maven-plugin.version>

        <apache.httpclient.version>4.5.8</apache.httpclient.version>
        <apache-logging.version>1.2</apache-logging.version>

        <lift-json.version>3.3.0</lift-json.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.gatling</groupId>
            <artifactId>gatling-app</artifactId>
            <version>${gatling.version}</version>
        </dependency>
        <dependency>
            <groupId>io.gatling</groupId>
            <artifactId>gatling-recorder</artifactId>
            <version>${gatling.version}</version>
        </dependency>
        <dependency>
            <groupId>io.gatling.highcharts</groupId>
            <artifactId>gatling-charts-highcharts</artifactId>
            <version>${gatling.version}</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>
        <dependency>
            <groupId>net.liftweb</groupId>
            <artifactId>lift-json_2.12</artifactId>
            <version>${lift-json.version}</version>
        </dependency>

        <!-- Apache and dependencies-->
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>${apache.httpclient.version}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>gatling</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>net.alchim31.maven</groupId>
                        <artifactId>scala-maven-plugin</artifactId>
                        <version>${scala-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>testCompile</goal>
                                </goals>
                                <configuration>
                                    <args>
                                        <arg>-target:jvm-10</arg>
                                        <arg>-deprecation</arg>
                                        <arg>-feature</arg>
                                        <arg>-unchecked</arg>
                                        <arg>-language:implicitConversions</arg>
                                        <arg>-language:postfixOps</arg>
                                    </args>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>io.gatling</groupId>
                        <artifactId>gatling-maven-plugin</artifactId>
                        <version>${gatling-maven-plugin.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

**Comment by slandelle** [comment]
Dup of #3713. Please upgrade to 3.1.1.
