### ISSUE TITLE
JMS: Shipping JMS 1.1 jar breaks JMS 2.0 clients

### ISSUE THREAD

**Issue by nosknut** [gatling/gatling#3742]
Calling  javax.jms.JMSContext.createContext()
 throws 
java.lang.NoSuchMethodError: javax.jms.Connection.createSession()Ljavax/jms/Session;
at com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createContext(JmsConnectionFactoryImpl.java:469)

**Comment by slandelle** [comment]
@nosknut Thanks for reporting. I've updated the issue title.

**Comment by slandelle** [comment]
@nosknut Could you please provide the full stacktrace?

**Comment by nosknut** [comment]
That is the full stack trace. The rest is of my own code

**Comment by nosknut** [comment]
I have broken out the code and this snippet creates the same stacktrace:
 ```

    final MQConnectionFactory factory = new MQConnectionFactory();
    factory.setTransportType(WMQConstants.WMQ_CM_CLIENT);
    factory.setConnectionNameList("localhost(1414)");
    factory.setQueueManager("qmanager");
    factory.setChannel("qchannel");
    factory.setStringProperty(WMQConstants.USERID, "userid");
    factory.createContext();
```


java.lang.NoSuchMethodError: javax.jms.Connection.createSession()Ljavax/jms/Session;

	at com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createContext(JmsConnectionFactoryImpl.java:469)
	at com.evry.secana.mq.QueueTest.setUpQueues(QueueTest.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllMethods$8(ClassTestDescriptor.java:373)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllMethods(ClassTestDescriptor.java:372)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:74)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by nosknut** [comment]
I have a docker container running mq server. When i remove the gatling.io dependency the test passes and when i add the dependency the test fails

**Comment by nosknut** [comment]
This is urgent in my project. Is there a way i can implement the fix before your next update?

**Comment by slandelle** [comment]
Try excluding `org.apache.geronimo.specs:geronimo-jms_1.1_spec` from your dependencies.

**Comment by nosknut** [comment]
I dont have this in my pom and geronimo does not show up when typing org.apache. in my IDE

**Comment by nosknut** [comment]
My gatling version is 3.1.2

**Comment by slandelle** [comment]
This is a dependency that we pull. Check how [maven exclusions](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) work.

**Comment by nosknut** [comment]
That worked! THANK YOU!!!

**Comment by pallapothurameshbabu** [comment]
Hi, I am trying to publish messages to tibco topic using below code, which is throwing exception.
Could you please help me on this ?

import java.util.{Hashtable => JHashtable}
import io.gatling.core.Predef._
import io.gatling.jms.Predef._
import javax.jms._

import scala.concurrent.duration._
import javax.jms.ConnectionFactory
import javax.naming._

import scala.collection.mutable._
import com.fedex._
import javax.jms.Connection
import javax.jms.JMSException
import javax.naming.Context
import javax.naming.InitialContext
import javax.naming.NamingException
import java.util.Hashtable

import io.gatling.core.config.GatlingConfiguration

import scala.collection.mutable
//import io.gatling.core.config.Credentials
class TestJmsScala extends Simulation {


  val requestTopic = topic("XXXXXXXXXXXXXXXXXXXXXX")

  val jmsConfig = jms
    .connectionFactory(
      jmsJndiConnectionFactory
        .connectionFactoryName("CF")
        .url("url")
        .contextFactory("ctxf")
    ).credentials("user", "pwd")
	
  val scn = scenario("JMS DSL test").repeat(1) {
    exec(jms("req reply testing").requestReply
      .destination(requestTopic)
      .textMessage("hello from gatling jms dsl")
    )
  }
  setUp(scn.inject(rampUsersPerSec(1) to 10 during (1 minutes)))
    .protocols(jmsConfig)
  def checkBodyTextCorrect(m: Message) = {
    m match {
      case tm: TextMessage => tm.getText == "HELLO FROM GATLING JMS DSL"
      case _               => false
    }
  }
}


Exception :

javax.jms.InvalidDestinationException: Not allowed to create destination
        at com.tibco.tibjms.Tibjmsx.buildException(Tibjmsx.java:577)
        at com.tibco.tibjms.TibjmsxSessionImp._createProducer(TibjmsxSessionImp.java:1075)
        at com.tibco.tibjms.TibjmsxSessionImp.createProducer(TibjmsxSessionImp.java:5068)

**Comment by slandelle** [comment]
@pallapothurameshbabu Please don't highjack existing non related issues.
