### ISSUE TITLE
Gatling failed

### ISSUE THREAD

**Issue by rpayyan1** [gatling/gatling#3759]
We use Gatling version - 2.3.1 and last year my team ran a performance test using Gatling from Jenkins Job without any issue. 
A few days back we have tried to run the same code and it failed with the following error, please help-

gatling-http-thread-1-1, WRITE: TLSv1.2 Handshake, length = 153
03:48:22.035 [gatling-http-thread-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 32768
03:48:22.035 [gatling-http-thread-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
03:48:22.035 [gatling-http-thread-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
03:48:22.035 [gatling-http-thread-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
gatling-http-thread-1-1, READ: TLSv1.2 Alert, length = 2
gatling-http-thread-1-1, RECV TLSv1.2 ALERT:  fatal, handshake_failure
gatling-http-thread-1-1, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
gatling-http-thread-1-1, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
gatling-http-thread-1-1, called closeOutbound()
gatling-http-thread-1-1, closeOutboundInternal()
gatling-http-thread-1-1, SEND TLSv1.2 ALERT:  warning, description = close_notify
gatling-http-thread-1-1, WRITE: TLSv1.2 Alert, length = 2
03:48:22.207 [gatling-http-thread-1-1] DEBUG org.asynchttpclient.netty.channel.NettyConnectListener - Trying to recover from failing to connect channel [id: 0xbe38789b, L:0.0.0.0/0.0.0.0:54846 ! R:gatling.io/35.180.13.133:443] with a retry value of true 
03:48:22.208 [gatling-http-thread-1-1] DEBUG org.asynchttpclient.netty.channel.NettyConnectListener - Failed to recover from connect exception: javax.net.ssl.SSLException: Received fatal alert: handshake_failure with channel [id: 0xbe38789b, L:0.0.0.0/0.0.0.0:54846 ! R:gatling.io/35.180.13.133:443]
03:48:22.211 [main] DEBUG io.gatling.http.ahc.HttpEngine - Couldn't execute warm up request https://gatling.io
java.util.concurrent.ExecutionException: java.net.ConnectException: Received fatal alert: handshake_failure
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:172)
	at io.gatling.http.ahc.HttpEngine.warmpUp(HttpEngine.scala:99)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.$anonfun$newComponents$1(HttpProtocol.scala:62)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:67)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:69)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:69)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:25)
	at io.gatling.http.action.sync.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:34)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:32)
	at io.gatling.core.structure.ChainBuilder.build(ChainBuilder.scala:30)
	at io.gatling.core.action.builder.RandomSwitchBuilder.$anonfun$build$1(RandomSwitchBuilder.scala:60)
	at scala.collection.immutable.List.map(List.scala:283)
	at io.gatling.core.action.builder.RandomSwitchBuilder.build(RandomSwitchBuilder.scala:58)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:34)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:32)
	at io.gatling.core.structure.ChainBuilder.build(ChainBuilder.scala:30)
	at io.gatling.core.action.builder.RandomSwitchBuilder.$anonfun$build$1(RandomSwitchBuilder.scala:60)
	at scala.collection.immutable.List.map(List.scala:283)
	at io.gatling.core.action.builder.RandomSwitchBuilder.build(RandomSwitchBuilder.scala:58)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:34)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:32)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:98)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:188)
	at scala.collection.immutable.List.map(List.scala:283)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:188)
	at io.gatling.app.Runner.run0(Runner.scala:95)
	at io.gatling.app.Runner.run(Runner.scala:64)
	at io.gatling.app.Gatling$.start(Gatling.scala:63)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
	at io.gatling.app.Gatling$.main(Gatling.scala:37)
	at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.net.ConnectException: Received fatal alert: handshake_failure

**Comment by slandelle** [comment]
Gatling 2 has reached end of life last year.
Please upgrade to latest 3.1.3.

**Comment by sake92** [comment]
In my case we had an expired SSL certificate... sigh 😥
