### ISSUE TITLE
Gatling doesn't release file descriptor for simulation.log

### ISSUE THREAD

**Issue by Crack** [gatling/gatling#3781]
I'm running Gatling as part of my CI test suite, using its rich DSL to run some functional tests. After tests are run I'm renaming output directory for each simulation by stripping timestamp (runUuid?), to ensure that logs are put in a directory with predictable path, and that repeat runs on developer machine generate logs that can be quickly found on disk.

It boils down to running multiple `Gatling.fromMap(props)` from a single JVM, to save time on JVM startup and run all simulations as fast as possible.

This worked fine with Gatling 2.x, but after upgrading to 3.2.0 I found out that file handle for simulation.log acquired in `LogFileDataWriter.onInit` isn't closed even after Gatling's actor system shits down, making file move on Windows impossible.

File Leak Detector log:
```
#68 E:\...\nginx-tests\target\reports\ManagementEndpointTests-20190811200927938\simulation.log by thread:GatlingSystem-akka.actor.default-dispatcher-5 on Sun Aug 11 22:09:32 CEST 2019
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:244)
	at io.gatling.core.stats.writer.BufferedFileChannelWriter$.apply(LogFileDataWriter.scala:40)
	at io.gatling.core.stats.writer.LogFileDataWriter.onInit(LogFileDataWriter.scala:276)
	at io.gatling.core.stats.writer.LogFileDataWriter.onInit(LogFileDataWriter.scala:270)
	at io.gatling.core.stats.writer.DataWriter$$anonfun$1.applyOrElse(DataWriter.scala:47)
	at io.gatling.core.stats.writer.DataWriter$$anonfun$1.applyOrElse(DataWriter.scala:43)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.actor.FSM.processEvent(FSM.scala:707)
	at akka.actor.FSM.processEvent$(FSM.scala:704)
	at io.gatling.core.stats.writer.DataWriter.processEvent(DataWriter.scala:29)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:701)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:695)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Looks like you create an instance of `RandomAccessFile` in `BufferedFileChannelWriter` that is never closed - Gatling just acquires a channel and ignores its file descriptor.

**Comment by slandelle** [comment]
Thanks for reporting

**Comment by slandelle** [comment]
Actually, the fd did not leak in the first place. The file was closed on ActorSystem termination, see https://github.com/gatling/gatling/blob/333f246d2b085f5c13c4ce1b9c4966930b8ccf33/gatling-core/src/main/scala/io/gatling/core/stats/writer/LogFileDataWriter.scala#L280

You most likely got in this situation because you're hacking Gatling internals.
