### ISSUE TITLE
Uncaught error from thread [GatlingSystem-akka.actor.default-dispatcher-4]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[GatlingSystem] java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by ajijshaikh** [gatling/gatling#3788]
Getting above issue when i run -  mvn test-compile gatling:test - [on](url) attached project please help asap

https://drive.google.com/file/d/1KluHkti0KlseNrwdADK-I2iaMmAdKg8c/view?usp=sharing

**Comment by ajijshaikh** [comment]
Error Stack -


WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.mycompany:myproject >-----------------------
[INFO] Building myproject 1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ myproject ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ajij/Desktop/myproject/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ myproject ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ myproject ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ myproject ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- gatling-maven-plugin:3.0.2:test (default-cli) @ myproject ---
16:51:52.048 [main] INFO  io.gatling.compiler.ZincCompiler$ - Compiling 1 Scala source to /home/ajij/Desktop/myproject/target/test-classes ...
16:51:59.048 [main] INFO  io.gatling.compiler.ZincCompiler$ - Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/ajij/.m2/repository/com/google/protobuf/protobuf-java/3.3.1/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
16:52:03.208 [main] INFO  i.g.c.config.GatlingConfiguration$ - Gatling will try to use 'gatling.conf' as custom config file.
16:52:04.559 [GatlingSystem-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
16:52:06.212 [GatlingSystem-akka.actor.default-dispatcher-3] INFO  i.g.c.stats.writer.ConsoleDataWriter - Initializing
16:52:06.213 [GatlingSystem-akka.actor.default-dispatcher-2] INFO  i.g.c.stats.writer.LogFileDataWriter - Initializing
16:52:06.263 [GatlingSystem-akka.actor.default-dispatcher-3] INFO  i.g.c.stats.writer.ConsoleDataWriter - Initialized
16:52:06.332 [GatlingSystem-akka.actor.default-dispatcher-2] INFO  i.g.c.stats.writer.LogFileDataWriter - Initialized
Simulation examples.users.UserSimulation started...
16:52:06.679 [GatlingSystem-akka.actor.default-dispatcher-5] INFO  i.g.core.controller.inject.Injector - StoppedInjecting
Uncaught error from thread [GatlingSystem-akka.actor.default-dispatcher-4]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[GatlingSystem]
java.lang.ExceptionInInitializerError
        at examples.users.UserSimulation.$anonfun$UserNameExtractor$1(UserSimulation.scala:11)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:173)
        at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.$anonfun$applyOrElse$3(SingletonFeed.scala:42)
        at io.gatling.commons.validation.package$.safely(package.scala:34)
        at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.pollRecord$1(SingletonFeed.scala:42)
        at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.feedRecords$1(SingletonFeed.scala:48)
        at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.$anonfun$applyOrElse$11(SingletonFeed.scala:59)
        at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.$anonfun$applyOrElse$11$adapted(SingletonFeed.scala:59)
        at io.gatling.commons.validation.Success.flatMap(Validation.scala:43)
        at io.gatling.commons.validation.Validation.flatMap$mcI$sp(Validation.scala:30)
        at io.gatling.commons.validation.Validation.flatMap$mcI$sp$(Validation.scala:30)
        at io.gatling.commons.validation.Success.flatMap$mcI$sp(Validation.scala:41)
        at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.applyOrElse(SingletonFeed.scala:59)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:24)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
        at com.intuit.karate.Resource.<init>(Resource.java:57)
        at com.intuit.karate.core.FeatureParser.parse(FeatureParser.java:75)
        at com.intuit.karate.Runner.runFeature(Runner.java:181)
        at examples.users.DataExtractor.<clinit>(DataExtractor.java:8)
        ... 25 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.593 s
[INFO] Finished at: 2019-08-24T16:52:06+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:3.0.2:test (default-cli) on project myproject: Gatling failed.: Process exited with an error: 255 (Exit value: 255) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by slandelle** [comment]
karate-gatling is not genuine Gatling. It hacks our internals to implement its own runner. Your problem happens in their layer and we can’t do anything here.
I advise you stick to real Gatling for load testing.
