### ISSUE TITLE
registerPebbleExtensions does not work.

### ISSUE THREAD

**Issue by sporieg** [gatling/gatling#3800]
The implementation of io.gatling.core.body.PebbleExtensions.register seems to check the parameter not the object's variable.

I wrote a simple spec, and ran just that to confirm:

```scala
package io.gatling.core.body

import io.gatling.{BaseSpec, ValidationValues}
import com.mitchellbosecke.pebble.extension.AbstractExtension

object TestExtension extends AbstractExtension {
}
class PebbleExtensionsSpec  extends BaseSpec with ValidationValues {
  "PebbleExtensions" should "should allow registration" in {
    PebbleExtensions.register(Seq(TestExtension)) //java.lang.UnsupportedOperationException: Pebble extensions have already been registered
  }
}
```

```shell
sbt
project gatling-core
testOnly io.gatling.core.body.PebbleExtensionsSpec
```

Which output:

```shell
sbt:gatling-core> testOnly io.gatling.core.body.PebbleExtensionsSpec
[warn] Credentials file /home/gsporie/.sbt/.credentials does not exist
[warn] Credentials file /home/gsporie/.sbt/.credentials does not exist
[warn] Credentials file /home/gsporie/.sbt/.credentials does not exist
[info] PebbleExtensionsSpec:
[info] PebbleExtensions
[info] - should should allow registration *** FAILED ***
[info]   java.lang.UnsupportedOperationException: Pebble extensions have already been registered
[info]   at io.gatling.core.body.PebbleExtensions$.register(Pebble.scala:41)
[info]   at io.gatling.core.body.PebbleExtensionsSpec.$anonfun$new$1(PebbleExtensionsSpec.scala:28)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$5.apply(FlatSpecLike.scala:1682)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   ...
[info] ScalaTest
[info] Run completed in 2 seconds, 25 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	io.gatling.core.body.PebbleExtensionsSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Sep 24, 2019 4:15:36 PM

```

This should be simple to fix, change the check to `this.extensions.nonEmpty` from `extensions.nonEmpty`

```scala
private[gatling] object PebbleExtensions {

  private[body] var extensions: Seq[Extension] = Nil

  def register(extensions: Seq[Extension]): Unit = {
    if (this.extensions.nonEmpty) {
      throw new UnsupportedOperationException("Pebble extensions have already been registered")
    }
    this.extensions = extensions
  }
}
```

**Comment by slandelle** [comment]
Thanks for reporting!
