### ISSUE TITLE
Code: java.lang.NullPointerException: null at io.gatling.app.Selection$Selector.askRunDescription(Selection.scala:134)

### ISSUE THREAD

**Issue by SevenLM361** [gatling/gatling#3849]
Can you help me,  How can I resolve this?
GATLING_HOME is set to /Users/sevenlm/workspace/gatling/gatling-charts-highcharts-bundle-3.3.1 BasicSimulation is the only simulation, executing it. Select run description (optional)
17:31:10.545 [ERROR] i.g.a.Gatling$ - Run crashed java.lang.NullPointerException: null	
at io.gatling.app.Selection$Selector.askRunDescription(Selection.scala:134)	
at io.gatling.app.Selection$Selector.$anonfun$selection$5(Selection.scala:60)	
at scala.Option.getOrElse(Option.scala:189)	
at io.gatling.app.Selection$Selector.selection(Selection.scala:60)	
at io.gatling.app.Selection$.apply(Selection.scala:36)	
at io.gatling.app.Runner.run0(Runner.scala:73)	
at io.gatling.app.Runner.run(Runner.scala:60)	
at io.gatling.app.Gatling$.start(Gatling.scala:80)	
at io.gatling.app.Gatling$.fromArgs(Gatling.scala:46)	
at io.gatling.app.Gatling$.main(Gatling.scala:38)	
at io.gatling.app.Gatling.main(Gatling.scala)

**Comment by slandelle** [comment]
No idea what you do. 
What you you do after the `Select run description (optional)` prompt?
Are you hacking stdin?

**Comment by slandelle** [comment]
No update from user for more than one month. Closing.
