### ISSUE TITLE
ClassNotFoundException: sbt.util.ShowLines

### ISSUE THREAD

**Issue by gee4vee** [gatling/gatling#3889]
I'm getting the following build failure. Not sure if I'm missing something to get things to compile.

```
[INFO] --- gatling-maven-plugin:3.0.5:test (default) @ ***---
[WARNING] Missing POM for org.scala-sbt:compiler-interface:jar:1.3.1
[WARNING] Missing POM for org.scala-sbt:util-logging_2.12:jar:1.3.0
[WARNING] Missing POM for org.scala-sbt:zinc-classpath_2.12:jar:1.3.1
[WARNING] Missing POM for org.scala-sbt:compiler-interface:jar:1.3.1
java.lang.NoClassDefFoundError: sbt/util/ShowLines
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3139)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3280)
	at java.base/java.lang.Class.getMethod0(Class.java:3266)
	at java.base/java.lang.Class.getMethod(Class.java:2063)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:43)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.ClassNotFoundException: sbt.util.ShowLines
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

My redacted pom.xml:

```
<?xml version="1.0"?>
<project 
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <modelVersion>4.0.0</modelVersion>

    <groupId>***</groupId>
    <artifactId>****</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <gatling.version>3.3.1</gatling.version>
        <gatling-plugin.version>3.0.5</gatling-plugin.version>
        <maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
        <!-- <scala-maven-plugin.version>4.3.1</scala-maven-plugin.version> -->
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.gatling.highcharts</groupId>
            <artifactId>gatling-charts-highcharts</artifactId>
            <version>${gatling.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <testSourceDirectory>simulations</testSourceDirectory>
        <plugins>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>bash</executable>
                    <arguments>
                        <argument>run.sh</argument>
                        <argument>${env.NS}</argument> <!-- will be empty if running with services -->
                    </arguments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-maven-plugin</artifactId>
                <version>${gatling-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- the name of the single Simulation class to run -->
                    <simulationClass>${env.SIMULATION}</simulationClass>
                    <runMultipleSimulations>false</runMultipleSimulations>                   <!-- if the plugin should run multiple simulations sequentially -->
                    <includes>                                                               <!-- include filters, see dedicated section below -->
                        <include></include>
                    </includes>
                    <excludes>                                                               <!-- exclude filters, see dedicated section below -->
                        <exclude></exclude>
                    </excludes>
                    <reportsOnly></reportsOnly>                                              <!-- to only trigger generating HTML reports from the log file contained in folder parameter -->
                    <runDescription>****</runDescription>             <!-- short text that will be displayed in the HTML reports -->
                    <failOnError>true</failOnError>                                          <!-- report failure in case of assertion failure, typically to fail CI pipeline -->
                    <continueOnAssertionFailure>false</continueOnAssertionFailure>           <!-- keep on executing multiple simulations even if one fails -->
                    <useOldJenkinsJUnitSupport>true</useOldJenkinsJUnitSupport>             <!-- report results to Jenkins JUnit support (workaround until we manage to get Gatling support into Jenkins) -->
                    <!-- pass extra parameters to the Gatling JVM -->
                    <jvmArgs>
                        <jvmArg>-DIAM=${env.IAM}</jvmArg>
                        <jvmArg>-DStarterkitsDir=${env.STARTERKITS_DIR}</jvmArg>
                        <jvmArg>-DServicesDir=${env.SERVICES_DIR}</jvmArg>
                        <jvmArg>-DGROUP=${env.RESOURCE_GROUP}</jvmArg>
                        <jvmArg>-DGORG=${env.ORG_GUID}</jvmArg>
                        <jvmArg>-DSPACE=${env.SPACE_GUID}</jvmArg>
                        <jvmArg>-DURL=${env.URL}</jvmArg>
                        <jvmArg>-DUsers=${env.USERS}</jvmArg>
                        <jvmArg>-DDuration=${env.DURATION}</jvmArg>
                    </jvmArgs>
                    <overrideJvmArgs>false</overrideJvmArgs>                                 <!-- if above option should override the defaults instead of replacing them -->
                    <propagateSystemProperties>true</propagateSystemProperties>              <!-- if System properties from the maven JVM should be propagated to the Gatling forked one -->
                    <!-- pass extra parameters to the Compiler JVM -->
                    <compilerJvmArgs>
                    </compilerJvmArgs>
                    <!-- if above option should override the defaults instead of replacing them -->
                    <overrideCompilerJvmArgs>false</overrideCompilerJvmArgs>    
                    <!-- extra options to be passed to scalac -->             
                    <!-- <extraScalacOptions>                                                     
                        <extraScalacOption></extraScalacOption>
                    </extraScalacOptions> -->
                    <disableCompiler>false</disableCompiler>                                 <!-- if compiler should be disabled, typically because another plugin has already compiled sources -->
                    <simulationsFolder>${project.basedir}/simulations</simulationsFolder> <!-- where the simulations to be compiled are located -->
                    <resourcesFolder>${project.basedir}</resourcesFolder> <!-- where the test resources are located -->
                    <resultsFolder>${project.basedir}/target/gatling</resultsFolder>         <!-- where the simulation log and the HTML reports will be generated -->
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by slandelle** [comment]
Looks like a corrupted jar in your local maven cache. Or something wrong with your pom.
But https://github.com/gatling/gatling-maven-plugin-demo works our of the box with Java 11 or Java 14.
Problem is on your side.

**Comment by gee4vee** [comment]
Since no one here was willing to help a bit more, posting this in case others have the same issue: I changed my pom.xml to use the `scala-maven-plugin` to do the compilation and setting `disableCompiler` in the `gatling-maven-plugin` configuration to `true`.

Before, I was letting `gatling-maven-plugin` do the compilation. It seems to me something is wrong in `gatling-maven-plugin` since it couldn't compile, but I guess we'll never know.

**Comment by slandelle** [comment]
> Since no one here was willing to help a bit more

This is a bug tracker, to be used for software bugs and feature requests.
If you want help with your own set up, please use the [community mailing list](https://groups.google.com/forum/#!forum/gatling).

As I already said, your problem is most likely one jar is corrupted in your local maven repository.

A quick search on the internet would give you that the jar containing the class `sbt.util.ShowLines` (from your stacktrace) is `org.scala-sbt/util-logging_2.12`.

The fact that scala-maven-plugin worked most likely means they don't use the same version and you have 2 different version of this jar in your local maven cache: one corrupted that gatling-maven-plugin is trying to use but can't unzip and one fine that scala-maven-plugin uses successfully.

Again, please investigate the content of your local maven cache.

**Comment by gee4vee** [comment]
You’re assuming I didn’t. I deleted the scala-sbt and scala-lang  folders in my local maven cache. Still had the same issue afterwards. 

If they don’t use the same version, that sounds problematic at the very least. My gut tells me I should be able to use either method of compilation successfully out of the box.

**Comment by slandelle** [comment]
You posted a [question on SoF ](https://stackoverflow.com/questions/61490337/java-lang-noclassdeffounderror-com-trueaccord-scalapb-generatedenum-with-gatlin) stating that now your issue is with `com.trueaccord.scalapb.GeneratedEnum` which is in a different jar, neither in `org.scala-sbt` not `org.scala-lang` organisations. You have multiple corrupted jars. Cleaning the `scala-sbt` fixed the first corrupted jar and helped you get rid of the `ClassNotFoundException` about `sbt.util.ShowLines` and now you hit a second one. 

> If they don’t use the same version, that sounds problematic at the very least. My gut tells me I should be able to use either method of compilation successfully out of the box.

No.
`scala-maven-plugin:4.3.1` depends on `zinc:1.3.2` while `gatling:3.3.1` depends on `zinc:1.3.1`. Different versions, different jars.
Maven installed some corrupted jars when installing `zinc:1.3.1` dependencies and valid jars when installing `zinc:1.3.2` ones.
