### ISSUE TITLE
Gatling - To Compress request data of large json payloads in to GZIP format

### ISSUE THREAD

**Issue by ManikandarajThirumeni** [gatling/gatling#3987]
Hi All,

Using the below code in Gatling for converting JSON Request Data to GZIP Format and the below Failure is observed,

Similar issue was tracked using the below ticket,

https://github.com/gatling/gatling/issues/2863

Can you please help in fixing this issue.

            http("Post AP Configs")
              .post("/Path")
              .headers(header_1)
              .body(StringBody("${configData}")).asJSON
              .processRequestBody(gzipBody)
              .check(bodyString.saveAs("BODY"))
              .check(status.is(201))

Exception in thread "main" java.lang.UnsupportedOperationException: requestCompressor doesn't support <function1>
	at io.gatling.http.request.BodyProcessors$$anonfun$1.apply(BodyProcessors.scala:35)
	at io.gatling.http.request.BodyProcessors$$anonfun$1.apply(BodyProcessors.scala:28)
	at scala.Option.map(Option.scala:146)
	at io.gatling.http.request.builder.HttpRequestBuilder.processRequestBody(HttpRequestBuilder.scala:89)
	at com.interdigital.ap.simulation.ScenarioActions$$anonfun$2.apply(ScenarioActions.scala:83)
	at com.interdigital.ap.simulation.ScenarioActions$$anonfun$2.apply(ScenarioActions.scala:64)
	at com.interdigital.ap.simulation.BatchBasedSimulation.bPAPC(BatchBasedSimulation.scala:51)
	at com.interdigital.ap.simulation.BatchBasedSimulation.<init>(BatchBasedSimulation.scala:105)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.gatling.core.runner.Runner.run(Runner.scala:36)
	at io.gatling.app.Gatling$$anonfun$runSimulationIfNecessary$1.apply(Gatling.scala:138)
	at io.gatling.app.Gatling$$anonfun$runSimulationIfNecessary$1.apply(Gatling.scala:123)
	at scala.Option.getOrElse(Option.scala:121)
	at io.gatling.app.Gatling.runSimulationIfNecessary(Gatling.scala:123)
	at io.gatling.app.Gatling.start(Gatling.scala:73)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:59)
	at io.gatling.app.Gatling$.main(Gatling.scala:44)
	at io.gatling.app.Gatling.main(Gatling.scala)

Thanks,
Manikandaraj

**Comment by slandelle** [comment]
Which version of Gatling do you use?

**Comment by ManikandarajThirumeni** [comment]
> Which version of Gatling do you use?

Hi Slandelle,

Thanks for sharing your comments. The Gatling Version used in 2.17.

If Upgrade is required for fixing this issue, can you please share the detailed Steps for our reference.

Regards,
Manikandaraj

**Comment by slandelle** [comment]
Gatling 2.1.7 was released more than 5 years ago! Yes, obviously you have to upgrade, the latest version is 3.4.1.

You can have a look at the migration guides: https://gatling.io/docs/current/migration_guides/
