### ISSUE TITLE
Bundle: gatling.sh exits with 0 code when compilation fails

### ISSUE THREAD

**Issue by tomers** [gatling/gatling#4005]
I run `gatling.sh` from a script. I encountered multiple occasions where Gatling failed, but the exit code was 0.

Expected behavior: exit code should be non-zero
Observed behavior: exit code 0

```
gatling.sh ....

        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at io.gatling.compiler.ZincCompiler$.main(ZincCompiler.scala:40)
        at io.gatling.compiler.ZincCompiler.main(ZincCompiler.scala)
There is no simulation script. Please check that your scripts are in user-files/simulations

$ echo $?
0
```

**Comment by slandelle** [comment]
Contributions welcome!
