### ISSUE TITLE
ERROR i.g.c.stats.writer.LogFileDataWriter - DataWriter failed to initialize

### ISSUE THREAD

**Issue by debayandesarkar** [gatling/gatling#4051]
karate-gatling version 0.9.6
OS: macOS Catalina 10.15.2
Hi,
I am trying to run some Karate feature tests as Gatling test. The Karate features tests are executing successfully. However, while trying to run the gatling test using  **./gradlew gatlingRun --debug** , getting the below exception. I have also tried with root user and the project folder and sub-folders have read-write permission enabled for everyone. Please refer attached log file , build.gradle and scala class used to run the gatling test. Request your help in troubleshooting this issue further as I didn't get any reference to this issue on the community mailing list or google search.

2021-02-17T00:54:00.232-0800 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/bin/java''
2021-02-17T00:54:01.262-0800 [QUIET] [system.out] 00:54:01.258 [main] INFO  i.g.c.config.GatlingConfiguration$ - Gatling will try to use 'gatling.conf' as custom config file.
2021-02-17T00:54:01.774-0800 [QUIET] [system.out] 00:54:01.773 [GatlingSystem-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2021-02-17T00:54:02.460-0800 [QUIET] [system.out] 00:54:02.459 [GatlingSystem-akka.actor.default-dispatcher-4] INFO  i.g.c.stats.writer.LogFileDataWriter - Initializing
2021-02-17T00:54:02.460-0800 [QUIET] [system.out] 00:54:02.459 [GatlingSystem-akka.actor.default-dispatcher-3] INFO  i.g.c.stats.writer.ConsoleDataWriter - Initializing
2021-02-17T00:54:02.466-0800 [QUIET] [system.out] 00:54:02.466 [GatlingSystem-akka.actor.default-dispatcher-4] ERROR i.g.c.stats.writer.LogFileDataWriter - DataWriter failed to initialize
2021-02-17T00:54:02.466-0800 [QUIET] [system.out] java.nio.file.FileSystemException: /pay-integration-tests: Read-only file system
2021-02-17T00:54:02.466-0800 [QUIET] [system.out]       at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
.
.
.
.
2021-02-17T00:54:02.470-0800 [QUIET] [system.out]       at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2021-02-17T00:54:02.470-0800 [QUIET] [system.out] 00:54:02.468 [GatlingSystem-akka.actor.default-dispatcher-3] INFO  i.g.c.stats.writer.ConsoleDataWriter - Initialized
2021-02-17T00:54:02.471-0800 [QUIET] [system.out] 00:54:02.471 [main] ERROR io.gatling.app.Gatling$ - Run crashed
2021-02-17T00:54:02.471-0800 [QUIET] [system.out] java.lang.Exception: DataWriters didn't initialize properly

Regards
Debayan De [Sarkar]

[Gatling_Log.txt](https://github.com/gatling/gatling/files/5994550/Gatling_Log.txt)
[build.gradle.txt](https://github.com/gatling/gatling/files/5994562/build.gradle.txt)
[performanceTestSimulation_ScalaClass.txt](https://github.com/gatling/gatling/files/5994581/performanceTestSimulation_ScalaClass.txt) --Rename to performanceTestSimulation.scala

Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/g/gatling) instead.
Issue not found in the Community mailing list or Google Search.

* Regarding issues:
  * [x] Check that you can reproduce your issue with latest Gatling version
  Using karate-gatling version 0.9.6
  
  * [x] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  Not found
  * [x] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [x] Explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment]
karate-gatling has nothing to do with Gatling. Consider run load tests with genuine Gatling.
