### ISSUE TITLE
Unable to generate Gatling report || NumberFormatException while parsing log files.

### ISSUE THREAD

**Issue by krisnik** [gatling/gatling#4081]
While collating multiple log files to generate final Gatling report, intermittently we are running into `NumberFormatException`. 

The frequency of this error increase along with the duration of the load test. 

Gatling version used - 3.5.0 

Command used to generate report `java -cp ../target/application.jar io.gatling.app.Gatling -ro .`

Sample log below. 

```
2021-05-05T12:34:37.4769688Z 12:34:37.476 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass
2021-05-05T12:34:37.7427166Z 12:34:37.742 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 100000 lines
2021-05-05T12:34:37.8286759Z 12:34:37.824 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 200000 lines
2021-05-05T12:34:37.8886881Z 12:34:37.888 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 300000 lines
2021-05-05T12:34:37.9528989Z 12:34:37.952 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 400000 lines
2021-05-05T12:34:38.0228187Z 12:34:38.022 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 500000 lines
2021-05-05T12:34:38.0842992Z 12:34:38.083 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 600000 lines
2021-05-05T12:34:38.1465041Z 12:34:38.145 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 700000 lines
2021-05-05T12:34:38.2145581Z 12:34:38.213 [main] INFO  i.gatling.charts.stats.LogFileReader - First pass, read 800000 lines
2021-05-05T12:34:38.2408425Z 12:34:38.233 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832227: REQUESRecordReadWriteScenario	470	START	1620207748697	1620207748697
2021-05-05T12:34:38.2409731Z 12:34:38.233 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832348: REQUESRecordRCreateOrUpdateRecords	1620207798667	1620207799859	OK	 
2021-05-05T12:34:38.2411027Z 12:34:38.233 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832469: REQUERecordReadWriteScenario	597	START	1620207840696	1620207840696
2021-05-05T12:34:38.2412242Z 12:34:38.233 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832590: REQUESTRecordReadWriteScenario	644	START	1620207874206	1620207874206
2021-05-05T12:34:38.2413451Z 12:34:38.234 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832713: REQUESRecordReadWriteScenario	695	START	1620207910706	1620207910706
2021-05-05T12:34:38.2414664Z 12:34:38.234 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832714: REQUERecordReadWriteScenario	696	START	1620207911697	1620207911697
2021-05-05T12:34:38.2415847Z 12:34:38.234 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832836: REQUEST	CreateOrUpdateRecords	1620207946015	1620207946821	OK	 
2021-05-05T12:34:38.2417049Z 12:34:38.234 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 832958: REQUESRecordReadWriteScenario	795	START	1620207982706	1620207982706
2021-05-05T12:34:38.2418237Z 12:34:38.234 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 833080: RERecordReadWriteScenario	843	START	1620208017705	1620208017705
2021-05-05T12:34:38.2419415Z 12:34:38.234 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 833204: REQUECreateOrUpdateRecords	1620208045666	1620208046616	OK	 
2021-05-05T12:34:38.2420590Z 12:34:38.235 [main] DEBUG i.gatling.charts.stats.LogFileReader - Record broken on line 833325: REQUEST	2CreateOrUpdateRecords	1620208067185	1620208074366	OK	 
2021-05-05T12:34:38.2421375Z Exception in thread "main" java.lang.NumberFormatException: For input string: "OK"
2021-05-05T12:34:38.2422058Z 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2021-05-05T12:34:38.2422657Z 	at java.base/java.lang.Long.parseLong(Long.java:692)
2021-05-05T12:34:38.2423355Z 	at java.base/java.lang.Long.parseLong(Long.java:817)
2021-05-05T12:34:38.2424190Z 	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
2021-05-05T12:34:38.2424837Z 	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
2021-05-05T12:34:38.2425650Z 	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
2021-05-05T12:34:38.2426300Z 	at io.gatling.charts.stats.LogFileReader.$anonfun$firstPass$1(LogFileReader.scala:96)
2021-05-05T12:34:38.2426915Z 	at scala.collection.Iterator.foreach(Iterator.scala:941)
2021-05-05T12:34:38.2427464Z 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
2021-05-05T12:34:38.2428051Z 	at scala.collection.Iterator$ConcatIterator.foreach(Iterator.scala:179)
2021-05-05T12:34:38.2428671Z 	at io.gatling.charts.stats.LogFileReader.firstPass(LogFileReader.scala:86)
2021-05-05T12:34:38.2429310Z 	at io.gatling.charts.stats.LogFileReader.$anonfun$x$4$1(LogFileReader.scala:131)
2021-05-05T12:34:38.2429972Z 	at io.gatling.charts.stats.LogFileReader.parseInputFiles(LogFileReader.scala:65)
2021-05-05T12:34:38.2430777Z 	at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:131)
2021-05-05T12:34:38.2431458Z 	at io.gatling.app.RunResultProcessor.initLogFileReader(RunResultProcessor.scala:52)
2021-05-05T12:34:38.2432182Z 	at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:34)
2021-05-05T12:34:38.2432808Z 	at io.gatling.app.Gatling$.start(Gatling.scala:88)
2021-05-05T12:34:38.2433394Z 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:46)
2021-05-05T12:34:38.2433963Z 	at io.gatling.app.Gatling$.main(Gatling.scala:38)
2021-05-05T12:34:38.2434479Z 	at io.gatling.app.Gatling.main(Gatling.scala)
```

Please let me know if you need more details.

**Comment by slandelle** [comment]
The version of Gatling used to run the test and generate the log file and the one used to generate the reports from the log file are not aligned.

**Comment by krisnik** [comment]
@slandelle I have only defined this dependency in my pom.xml

Could you please elaborate on what am I missing here? 

```xml
            <dependency>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-app</artifactId>
                <version>3.5.1</version>
            </dependency>
            <dependency>
                <groupId>io.gatling.highcharts</groupId>
                <artifactId>gatling-charts-highcharts</artifactId>
                <version>3.5.1</version>
            </dependency>

```

**Comment by slandelle** [comment]
This is what you have locally for trying to generate the reports.
But at least one of your injectors is using an older version.
