### ISSUE TITLE
Charts: ArrayIndexOutOfBoundsException when test is killed right after some users just started

### ISSUE THREAD

**Issue by slandelle** [gatling/gatling#4137]
We currently don't account for `USER START` records when computing the run duration.
So when the log file ends with `USER START` records, the second pass crashes with an Exception such as:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 179 out of bounds for length 179
    at io.gatling.charts.stats.buffers.SessionDeltaBuffer.addStart(SessionDeltaPerSecBuffers.scala:37)
    at io.gatling.charts.stats.buffers.SessionDeltaPerSecBuffers.addSessionBuffers(SessionDeltaPerSecBuffers.scala:95)
    at io.gatling.charts.stats.buffers.SessionDeltaPerSecBuffers.addSessionBuffers$(SessionDeltaPerSecBuffers.scala:91)
    at io.gatling.charts.stats.ResultsHolder.addSessionBuffers(ResultsHolder.scala:26)
    at io.gatling.charts.stats.ResultsHolder.addUserRecord(ResultsHolder.scala:40)
    at io.gatling.charts.stats.LogFileReader.$anonfun$secondPass$1(LogFileReader.scala:173)
    at io.gatling.charts.stats.LogFileReader.$anonfun$secondPass$1$adapted(LogFileReader.scala:166)
    at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1288)
    at io.gatling.charts.stats.LogFileReader.secondPass(LogFileReader.scala:166)
    at io.gatling.charts.stats.LogFileReader.$anonfun$resultsHolder$1(LogFileReader.scala:186)
    at io.gatling.charts.stats.LogFileReader.parseInputFiles(LogFileReader.scala:65)
    at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:186)
    at io.gatling.app.RunResultProcessor.initLogFileReader(RunResultProcessor.scala:52)
    at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:34)
    at io.gatling.app.Gatling$.start(Gatling.scala:93)
    at io.gatling.app.Gatling$.fromMap(Gatling.scala:40)
    at Engine$.delayedEndpoint$Engine$1(Engine.scala:11)
    at Engine$delayedInit$body.apply(Engine.scala:4)
    at scala.Function0.apply$mcV$sp(Function0.scala:39)
    at scala.Function0.apply$mcV$sp$(Function0.scala:39)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
    at scala.App.$anonfun$main$1(App.scala:76)
    at scala.App.$anonfun$main$1$adapted(App.scala:76)
    at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
    at scala.App.main(App.scala:76)
    at scala.App.main$(App.scala:74)
    at Engine$.main(Engine.scala:4)
    at Engine.main(Engine.scala)
```

**Comment by slandelle** [comment]
Until fix is released in 3.7.0, the workaround is to remove those dandling USER START records before generating the reports.
