### ISSUE TITLE
Core: Java and Kotlin count and findAll checks with comparison criterion crash java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by NikolayMetchev** [gatling/gatling#4207]
Using the following scenario defined with Kotlin:

```
private val downloadCSVTrades = http("download csv trades")
        .get("/trades")
        .headers(sessionTokenHeader + mapOf(HttpHeaders.ContentType to ContentType.Text.CSV.toString()))
        .check(
            regex("""\R""").count().gt(2500), // This is the root cause of the problem 
            status().shouldBe(HttpStatusCode.OK.value),
            responseTimeInMillis()
                .lt(getTradeResponseTimeout.toMillis().toInt())
                .saveAs(getTradesAsCsvMetric),
            bodyString().saveAs("downloadedCsv")
        )
````

Results in the following exception:
```
2022-02-07T12:07:09,854+00:00 [main] ERROR io.gatling.app.Gatling$ - Run crashed
java.lang.IllegalArgumentException: No ordering for class class net.jodah.typetools.TypeResolver$Unknown
        at io.gatling.javaapi.core.internal.Comparisons$.ordering(Comparisons.scala:62) ~[gatling-core-java-3.7.4.jar:3.7.4]
        at io.gatling.javaapi.core.internal.Comparisons.ordering(Comparisons.scala) ~[gatling-core-java-3.7.4.jar:3.7.4]
        at io.gatling.javaapi.core.CheckBuilder$Validate$Default.gte(CheckBuilder.java:1077) ~[gatling-core-java-3.7.4.jar:3.7.4]
        at paxos.loadtest.scenarios.DownloadCsvsSimulation.<init>(DownloadCsvsSimulation.kt:32) ~[gatling/:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at io.gatling.app.SimulationClass$Java.params(SimulationClass.scala:35) ~[gatling-app-3.7.4.jar:3.7.4]
        at io.gatling.app.Runner.run0(Runner.scala:62) ~[gatling-app-3.7.4.jar:3.7.4]
        at io.gatling.app.Runner.run(Runner.scala:49) ~[gatling-app-3.7.4.jar:3.7.4]
        at io.gatling.app.Gatling$.start(Gatling.scala:87) [gatling-app-3.7.4.jar:3.7.4]
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49) [gatling-app-3.7.4.jar:3.7.4]
        at io.gatling.app.Gatling$.main(Gatling.scala:38) [gatling-app-3.7.4.jar:3.7.4]
        at io.gatling.app.Gatling.main(Gatling.scala) [gatling-app-3.7.4.jar:3.7.4]

```

If you use shouldBe instead of gte then the exception does not occur.

**Comment by slandelle** [comment]
Thanks for reporting!
