### ISSUE TITLE
Memory leak during log parsing for simulation.log with no END time.

### ISSUE THREAD

**Issue by akshayamaldhure** [gatling/gatling#4209]
This is observed with gradle gatling plugin 3.5.1 version. I cannot try to reproduce this issue with the latest 3.7.4 version since the gatling-grpc library isn't compatible with the same.

My build.gradle looks like this:

```
plugins {
    id "io.gatling.gradle" version "3.5.1"
    id "scala"
    id "com.google.protobuf" version "0.8.14"
    id "application"
}

group 'my-tests'

gatling {
    // WARNING: options below only work when logback config file isn't provided
    logLevel = 'WARN' // logback root level
    logHttp = 'NONE'
    // set to 'ALL' for all HTTP traffic in TRACE, 'FAILURES' for failed HTTP traffic in DEBUG
    jvmArgs = ['-server',
               '-Xms512M',
               '-Xmx8024M',
               "-Dlogback.configurationFile=${logbackGatlingConfig()}"
    ]
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

repositories {
    mavenCentral()
}

gatlingRun {
    outputs.upToDateWhen { false }
}

dependencies {
    gatlingImplementation project(":core")
    implementation 'com.google.protobuf:protobuf-java:3.14.0'
    implementation 'io.grpc:grpc-netty-shaded:1.34.1'
    implementation 'io.grpc:grpc-protobuf:1.34.1'
    implementation 'io.grpc:grpc-stub:1.34.1'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    gatling 'com.github.phisgr:gatling-javapb:1.1.1'
    gatling 'com.github.phisgr:gatling-grpc:0.11.1'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.14.0'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.34.1'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
    generatedFilesBaseDir = "$projectDir/src/generated"
}

def logbackGatlingConfig() {
    return sourceSets.gatling.resources.find { it.name == 'logback-gatling.xml' }
}

clean {
    delete "$projectDir/src/generated"
}

task wrapper(type: Wrapper){
    gradleVersion = '6.8.3'
}
```

My simulation code looks like this:
```
package simulation

import com.github.phisgr.gatling.grpc.Predef._
import io.gatling.core.Predef._

import com.protos.{Proto1, Proto2, Proto3}

import scala.concurrent.duration._

class MySimulation extends Simulation {

  val grpcConf = grpc(managedChannelBuilder("my-grpc-host", some_invalid_port_number))

  val myFeeder = csv("feeders/my_feeder.csv").circular

  val myScenario =
    scenario("My scenario")
      .repeat(1) {
        feed(myFeeder)
          .exec(
            grpc("My gRPC method")
              .rpc(Proto1.getMyMethod)
              .payload(session => Proto2
                .newBuilder().setValue("value")
                .build())
              .check(extract { r: Proto3 => r.getSomeField.some } saveAs "someField")
          )
          .exec { session => {
            Console.println("Some field value from response: " + session("someField").as[String])
            session
          }
          }
          .pause(500)
      }


  setUp(myScenario.inject(
    rampUsers(1) during (2.seconds)))
    .maxDuration(10.seconds)
    .protocols(grpcConf)

}
```

My feeder CSV (my_feeder.csv) looks like this:
```
Col1,Col2,Col3
val1,2,3
val2,3,4
```

Below is the complete log (simulation logs + exception traces):
```
================================================================================
2022-02-07 18:57:40                                           5s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=0     )


---- Fetch value ---------------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 1      / done: 0     
================================================================================


================================================================================
2022-02-07 18:57:45                                          10s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=0     )


---- Fetch value ---------------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 1      / done: 0     
================================================================================

Simulation simulation.MySimulation completed in 10 seconds
Feb 07, 2022 6:57:45 PM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<6>: (url_here:9090)] Uncaught exception in the SynchronizationContext. Panic!
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at io.netty.util.concurrent.SingleThreadEventExecutor.lazyExecute(SingleThreadEventExecutor.java:823)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:263)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:177)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:50)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:32)
	at io.grpc.SynchronizationContext.schedule(SynchronizationContext.java:152)
	at io.grpc.internal.InternalSubchannel.scheduleBackoff(InternalSubchannel.java:294)
	at io.grpc.internal.InternalSubchannel.access$2500(InternalSubchannel.java:65)
	at io.grpc.internal.InternalSubchannel$TransportListener$2.run(InternalSubchannel.java:594)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportShutdown(InternalSubchannel.java:574)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyGracefulShutdown(ClientTransportLifecycleManager.java:55)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:59)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyTerminated(ClientTransportLifecycleManager.java:80)
	at io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:309)
	at io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:303)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.failWrites(WriteBufferingAndExceptionHandler.java:236)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.access$100(WriteBufferingAndExceptionHandler.java:43)
	at io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:145)
	at io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:141)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:502)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:342)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:769)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Feb 07, 2022 6:57:45 PM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<6>: (url_here:9090)] Uncaught exception in the SynchronizationContext. Panic!
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at io.netty.util.concurrent.SingleThreadEventExecutor.lazyExecute(SingleThreadEventExecutor.java:823)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:263)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:177)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:50)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:32)
	at io.grpc.SynchronizationContext.schedule(SynchronizationContext.java:152)
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.internalShutdown(ManagedChannelImpl.java:1683)
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.access$7000(ManagedChannelImpl.java:1520)
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl$3.run(ManagedChannelImpl.java:1642)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportShutdown(InternalSubchannel.java:574)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyGracefulShutdown(ClientTransportLifecycleManager.java:55)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:59)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyTerminated(ClientTransportLifecycleManager.java:80)
	at io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:309)
	at io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:303)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.failWrites(WriteBufferingAndExceptionHandler.java:236)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.access$100(WriteBufferingAndExceptionHandler.java:43)
	at io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:145)
	at io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:141)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:502)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:342)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:769)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Feb 07, 2022 6:57:45 PM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<6>: (url_here:9090)] Uncaught exception in the SynchronizationContext. Panic!
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at io.netty.util.concurrent.SingleThreadEventExecutor.lazyExecute(SingleThreadEventExecutor.java:823)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:263)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:177)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:50)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:32)
	at io.grpc.internal.Rescheduler.reschedule(Rescheduler.java:63)
	at io.grpc.internal.ManagedChannelImpl.rescheduleIdleTimer(ManagedChannelImpl.java:410)
	at io.grpc.internal.ManagedChannelImpl.access$7300(ManagedChannelImpl.java:105)
	at io.grpc.internal.ManagedChannelImpl$IdleModeStateAggregator.handleNotInUse(ManagedChannelImpl.java:1799)
	at io.grpc.internal.InUseStateAggregator.updateObjectInUse(InUseStateAggregator.java:45)
	at io.grpc.internal.ManagedChannelImpl$DelayedTransportListener.transportInUse(ManagedChannelImpl.java:1769)
	at io.grpc.internal.DelayedClientTransport$2.run(DelayedClientTransport.java:114)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportShutdown(InternalSubchannel.java:574)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyGracefulShutdown(ClientTransportLifecycleManager.java:55)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:59)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyTerminated(ClientTransportLifecycleManager.java:80)
	at io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:309)
	at io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:303)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.failWrites(WriteBufferingAndExceptionHandler.java:236)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.access$100(WriteBufferingAndExceptionHandler.java:43)
	at io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:145)
	at io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:141)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:502)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:342)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:769)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Parsing log file(s)...
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Integer.valueOf(Integer.java:832)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.scala:17)
	at scala.collection.immutable.Range.map(Range.scala:59)
	at io.gatling.charts.stats.StatsHelper$.buckets(StatsHelper.scala:22)
	at io.gatling.charts.stats.LogFileReader.<init>(LogFileReader.scala:151)
	at io.gatling.app.RunResultProcessor.initLogFileReader(RunResultProcessor.scala:52)
	at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:34)
	at io.gatling.app.Gatling$.start(Gatling.scala:89)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
	at io.gatling.app.Gatling$.main(Gatling.scala:37)
	at io.gatling.app.Gatling.main(Gatling.scala)
```

The generated simulation.log file looks like this:
```
RUN	simulation.MySimulation	mysimulation	1644299710910	 	3.5.1
USER	My gRPC method	START	1644299741582
```

Since these logs do not contain the `END` time, there looks like a memory leak in `StatsHelper.scala`.

**Comment by slandelle** [comment]
With 3.7, such empty simulation.log generates an `ArithmeticException`, which is way less severe than an `OutOfMemoryError`.

I'm closing this issue as it's invalid for up-to-date Gatling versions.
I'll open a new one to fail early with a proper Exception.
