### ISSUE TITLE
HTTP: StringBodyPart NPE in 3.8.2

### ISSUE THREAD

**Issue by sagar-kalburgi-ripcord** [gatling/gatling#4287]
Tl;dr
- Upgraded from 3.7.6 to 3.8.2
- Httpuploading a JPG does not appear to generate the "Content-Length" header
- As a result POST Multipartformdata does not appear to succeed
- fully working when downgrading back to 3.7.6

Code: 

```
    public static HttpRequestActionBuilder UploadContent(String metadata, String filePath){
        return http("UploadContent")
                .post(URL_TO_SERVER)
                .header("Authorization", BEARER_TOKEN)
                .header("Content-Type", "multipart/form-data")
                .header("Connection", "keep-alive")
                .header("Accept", "*/*")
                .bodyPart(StringBodyPart("metadata", metadata))
                .bodyPart(RawFileBodyPart("file", filePath))
                .asMultipartForm();
    }
```

Exception in 3.8.2 when log level set to DEBUG:

```
java.lang.NullPointerException: null
        at java.base/java.lang.String.getBytes(String.java:963)
        at io.gatling.http.client.body.multipart.impl.StringPartImpl.<init>(StringPartImpl.java:29)
        at io.gatling.http.client.body.multipart.StringPart.toImpl(StringPart.java:49)
        at io.gatling.http.client.body.multipart.MultipartFormDataRequestBody.toChunkedInput(MultipartFormDataRequestBody.java:53)
        at io.gatling.http.client.body.multipart.MultipartFormDataRequestBody.build(MultipartFormDataRequestBody.java:62)
        at io.gatling.http.client.impl.request.WritableRequestBuilder.buildRequestWithBody(WritableRequestBuilder.java:67)
        at io.gatling.http.client.impl.request.WritableRequestBuilder.buildRequest(WritableRequestBuilder.java:113)
        at io.gatling.http.client.impl.HttpAppHandler.write(HttpAppHandler.java:112)

```

Upon examining the request it appears that it does not generate 
Header from 3.7.6: 

```
headers:
        Connection: keep-alive
        Authorization: {TOKEN HERE}
        Accept: */*
        host: {HOST HERE}
        content-type: multipart/form-data; boundary=wWbN8J-afqPrmMPIu1ykRW_XsJ7fbYyUk5-
        content-length: 3193874
body:MultipartFormDataRequestBody{boundary=[119, 87, 98, 78, 56, 74, 45, 97, 102, 113, 80, 114, 109, 77, 80, 73, 117, 49, 121, 107, 82, 87, 95, 88, 115, 74, 55, 102, 98, 89, 121, 85, 107, 53, 45], contentType='multipart/form-data; boundary=wWbN8J-afqPrmMPIu1ykRW_XsJ7fbYyUk5-', content=Part{name='metadata', charset=UTF-8, transferEncoding='null', contentId='null', dispositionType='null', contentType='null', customHeaders=, content={
  "customheaders" : "working" 
}}
```

Header from 3.8.2: 

```
headers:
        Connection: keep-alive
        Authorization: {TOKEN HERE}
        Accept: */*
        host: {HOST HERE}
        content-type: multipart/form-data; boundary=DWpzoA3CKc-AOSRgeEHJNhT0IdygFHC-U3f
body:MultipartFormDataRequestBody{boundary=[68, 87, 112, 122, 111, 65, 51, 67, 75, 99, 45, 65, 79, 83, 82, 103, 101, 69, 72, 74, 78, 104, 84, 48, 73, 100, 121, 103, 70, 72, 67, 45, 85, 51, 102], patchedContentType='multipart/form-data; boundary=DWpzoA3CKc-AOSRgeEHJNhT0IdygFHC-U3f', content=Part{name='metadata', charset=null, transferEncoding='null', contentId='null', dispositionType='null', contentType='null', customHeaders=, content={
  "customheaders" : "working" 
}}
```

**Comment by slandelle** [comment]
Thanks for reporting.

As a workaround, you can specify an explicit charset on your `StringBodyPart`:

```java
.bodyPart(StringBodyPart("metadata", metadata).charset("UTF-8"))
```
