### ISSUE TITLE
Core: redisFeeder on JAVA crashed with java.lang.NullPointerException (io.gatling.redis.feeder.RedisFeederBuilder.clientPool() is null)

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4293]
Gatling: 3.8.2 (gatling-charts-highcharts-bundle-3.8.2)
OS: Windows 10 Pro
JDK: jdk-17.0.4
Redis: 7.0.4 (Docker container)

When try to use `redisFeeder` in JAVA getting below Error:
```
Simulation RedisFeederSimulation started...
22:56:49.637 [ERROR] i.g.c.a.FeedActor - Feeder crashed
java.lang.NullPointerException: Cannot invoke "com.redis.RedisClientPool.withClient(scala.Function1)" because the return value of "io.gatling.redis.feeder.RedisFeederBuilder.clientPool()" is null
        at io.gatling.redis.feeder.RedisFeederBuilder.next$1(RedisFeederBuilder.scala:55)
        at io.gatling.redis.feeder.RedisFeederBuilder.$anonfun$apply$3(RedisFeederBuilder.scala:60)
        at scala.collection.Iterator$$anon$27.next(Iterator.scala:1128)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:630)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:635)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
        at io.gatling.core.action.FeedActor.$anonfun$pollSingleRecord$1(FeedActor.scala:47)
        at io.gatling.core.action.FeedActor.withErrorHandling(FeedActor.scala:38)
        at io.gatling.core.action.FeedActor.io$gatling$core$action$FeedActor$$pollSingleRecord(FeedActor.scala:47)
        at io.gatling.core.action.FeedActor$$anonfun$receive$1.applyOrElse(FeedActor.scala:76)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
        at akka.actor.ActorCell.invoke(ActorCell.scala:548)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
22:56:49.641 [ERROR] i.g.c.c.Controller - Simulation crashed
java.lang.IllegalStateException: Feeder crashed: j.l.NullPointerException: Cannot invoke "com.redis.RedisClientPool.withClient(scala.Function1)" because the return value of "io.gatling.redis.feeder.RedisFeederBuilder.clientPool()" is null
        at io.gatling.core.action.FeedActor$$anonfun$receive$1.applyOrElse(FeedActor.scala:81)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
        at akka.actor.ActorCell.invoke(ActorCell.scala:548)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Simulation - JAVA:
```import io.gatling.javaapi.core.ScenarioBuilder;
import io.gatling.javaapi.core.Simulation;
import io.gatling.javaapi.http.HttpProtocolBuilder;
import io.gatling.javaapi.redis.RedisClientPool;
import io.gatling.javaapi.redis.RedisFeederBuilder;

import static io.gatling.javaapi.core.CoreDsl.atOnceUsers;
import static io.gatling.javaapi.core.CoreDsl.scenario;
import static io.gatling.javaapi.http.HttpDsl.http;
import static io.gatling.javaapi.redis.RedisDsl.redisFeeder;

public class RedisFeederSimulation extends Simulation {

    HttpProtocolBuilder httpProtocol = http;
    RedisClientPool redisPool =
            new RedisClientPool("127.0.0.1", 6379);

    RedisFeederBuilder feeder = redisFeeder(redisPool, "mylist");

    ScenarioBuilder scn =
            scenario("Scenario Name")
                    .feed(feeder)
                    .exec(session -> {
                        System.out.println("GeMi_RedisValue: " +session.get("mylist").toString());
                        return session;
                    });

    {
        setUp(scn.injectOpen(atOnceUsers(1)).protocols(httpProtocol));
    }
}
```
Using the same `redisFeeder` in Scala everything is working. 

Simulation - SCALA:
```
import scala.concurrent.duration._
import io.gatling.core.Predef._
import io.gatling.core.feeder._
import io.gatling.http.Predef._
import io.gatling.redis.Predef._
import com.redis._

class RedisFeederSimulationScala extends Simulation {

  val httpProtocol = http


  val redisPool = new RedisClientPool("127.0.0.1", 6379)

  val feeder = redisFeeder(redisPool, "mylist")

  val scn = scenario("BasicSimulationScala")
    .feed(feeder)
    .exec { session =>
      println(session)
      println("GeMi_RedisValue: " + session("mylist").as[String])
      session
    }

  setUp(
    scn.inject(atOnceUsers(1))
  ).protocols(httpProtocol)
}
```

Scala Run:
![image](https://user-images.githubusercontent.com/30750006/181996155-4fca7d51-319b-4b66-ba55-c313f770342f.png)

Redis List:
![image](https://user-images.githubusercontent.com/30750006/181996183-f483a038-0ea5-4f14-9e66-58dc06c508b7.png)

**Comment by slandelle** [comment]
Thanks for reporting!
