### ISSUE TITLE
Version 3.8.4 - Error while generating report

### ISSUE THREAD

**Issue by pozdnyshevmax** [gatling/gatling#4348]
Hellow, 
When I change version from 3.8.3 to 3.8.4 in my pom file, I can't generate report after run. 

================================================================================
Simulation loadtest.entyty.player.PlayerSimulation completed in 101 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.gatling.plugin.util.MainWithArgsInFile.runMain(MainWithArgsInFile.java:53)
	at io.gatling.plugin.util.MainWithArgsInFile.main(MainWithArgsInFile.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at io.gatling.charts.report.ReportsGenerator.generateFor(ReportsGenerator.scala:51)
	at io.gatling.app.RunResultProcessor.generateReports(RunResultProcessor.scala:65)
	at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:40)
	at io.gatling.app.Gatling$.start(Gatling.scala:101)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:53)
	at io.gatling.app.Gatling$.main(Gatling.scala:41)
	at io.gatling.app.Gatling.main(Gatling.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 3 more
Caused by: java.lang.IllegalStateException: Couldn't find a ComponentLibrary implementation
	at io.gatling.charts.component.ComponentLibrary$.<clinit>(ComponentLibrary.scala:31)
	... 11 more

my pomfile gatling dependency - 
   <gatling.version>3.8.4</gatling.version>
   <gatling-maven-plugin.version>4.2.7</gatling-maven-plugin.version>

      <dependency>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-app</artifactId>
        <version>${gatling.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-recorder</artifactId>
        <version>${gatling.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-compiler</artifactId>
        <version>${gatling.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>io.gatling.highcharts</groupId>
        <artifactId>gatling-charts-highcharts</artifactId>
        <version>${gatling.version}</version>
        <scope>test</scope>
      </dependency>
    
     <plugin>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-maven-plugin</artifactId>
        <version>${gatling-maven-plugin.version}</version>
      </plugin>

**Comment by pozdnyshevmax** [comment]
how often this happens, I found a solution to the problem in my own almost immediately after I created a bug.

**Comment by slandelle** [comment]
Most likely your `gatling-charts-highcharts` jar in your local maven cache is corrupted and need to be deleted and re-downloaded.
