### ISSUE TITLE
Java quickstart code crashes with `java.lang.NoSuchMethodException: xxx.<init>()`

### ISSUE THREAD

**Issue by ardc-shorn** [gatling/gatling#4403]
The code from https://gatling.io/docs/gatling/tutorials/quickstart/ does not declare the Java class as public.
When run with `gatlingRun` task from Gradle, the simulation crashes with:
```
> Task :api-svc:load-test:gatlingRun
13:40:34.322 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.NoSuchMethodException: raido.loadtest.BasicSimulation.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at io.gatling.app.SimulationClass$Java.params(SimulationClass.scala:35)
	at io.gatling.app.Runner.load(Runner.scala:72)
	at io.gatling.app.Runner.run(Runner.scala:57)
	at io.gatling.app.Gatling$.start(Gatling.scala:89)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:51)
	at io.gatling.app.Gatling$.main(Gatling.scala:39)
	at io.gatling.app.Gatling.main(Gatling.scala)
```

Add the `public` keyword and the simulation appears to run:
```
Simulation raido.loadtest.BasicSimulation completed in 5 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                          2 (OK=2      KO=0     )
> min response time                                    249 (OK=249    KO=-     )
> max response time                                    480 (OK=480    KO=-     )
> mean response time                                   365 (OK=365    KO=-     )
> std deviation                                        116 (OK=116    KO=-     )
> response time 50th percentile                        365 (OK=365    KO=-     )
> response time 75th percentile                        422 (OK=422    KO=-     )
> response time 95th percentile                        468 (OK=468    KO=-     )
> response time 99th percentile                        478 (OK=478    KO=-     )
> mean requests/sec                                  0.333 (OK=0.333  KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             2 (100%)
> 800 ms <= t < 1200 ms                                  0 (  0%)
> t >= 1200 ms                                           0 (  0%)
> failed                                                 0 (  0%)
================================================================================
```

My project (with added `public` keyword): https://github.com/au-research/raido/blob/f91f101cf332b65e253350a8163a89b513b76d8a/api-svc/load-test/src/gatling/java/raido/loadtest/BasicSimulation.java

**Comment by slandelle** [comment]
Thanks for reporting! I've just pushed the fix in the doc sources and publication is under way.
