### ISSUE TITLE
Java DSL - check fails with ClassCastException using "gte" (but not "is")

### ISSUE THREAD

**Issue by barryperez-sky** [gatling/gatling#4408]
Hi!

Currently I'm working on some migrating some scripts from Scala -> Java DSL.

Currently, we have some checks we need to run against Prometheus for metrics exposed by an application, where we extract a value (which is a string in the response json); convert that string to Double, and then check that the value is greater than or equal to an expected value.

**Sample in Scala DSL (works):**

            .check(jsonPath("$.data.result[0].value[1]").transform(string => string.toDouble).gte(expectedValue)

**Sample in Java DSL (works using "is"):**

            .check(jsonPath("$.data.result[0].value[1]").transform(string -> Double.valueOf(string)).is(0.0))

**Sample in Java DSL (does not work using "gte")**

            .check(jsonPath("$.data.result[0].value[1]").transform(string -> Double.valueOf(string)).gte(0.0))

The run crashes when it starts, with the following error:

16:25:59.720 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassCastException: class scala.math.Ordering$Double$ cannot be cast to class scala.math.Ordering (scala.math.Ordering$Double$ and scala.math.Ordering are in unnamed module of loader 'app')
	at io.gatling.javaapi.core.internal.Comparisons$.ordering(Comparisons.scala:57)
	at io.gatling.javaapi.core.internal.Comparisons.ordering(Comparisons.scala)
	at io.gatling.javaapi.core.CheckBuilder$Validate$Default.gte(CheckBuilder.java:1084)

Not sure if I'm doing something wrong but it seems there is something different between the implementation of .is() and .gte() here?

Please advise if this is enough info to know what's happened here, otherwise I will look to put together a self contained example - but would then need to figure out where to host a sample json snippet to be retrieved (or expose a simple server returning that json for testing purposes!)

Thanks!
Barry

**Comment by barryperez-sky** [comment]
Thanks @slandelle - that's a quick fix indeed!
