### ISSUE TITLE
HTTP: crashing after passing Map() as EL into formParamMap(formParamSeq)

### ISSUE THREAD

**Issue by Amerousful** [gatling/gatling#4413]
Version: 3.9.3

Error:  `Exception while handling HTTP/1.1 crash, please report to Gatling maintainers`

STR:
```
Iterator.continually(Map("map" -> Map()))

.formParamMap("#{map}")
```

Stacktrace:
```
19:29:31.184 [DEBUG] i.g.h.e.r.DefaultStatsProcessor - Request 'get request' failed for user 1: j.l.StringIndexOutOfBoundsException: String index out of range: -1
19:29:31.191 [ERROR] i.g.h.c.i.HttpAppHandler - Exception while handling HTTP/1.1 crash, please report to Gatling maintainers
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:275)
	at java.base/java.lang.StringBuilder.setLength(StringBuilder.java:85)
	at io.gatling.http.client.body.form.FormUrlEncodedRequestBody.encode(FormUrlEncodedRequestBody.java:64)
	at io.gatling.http.client.body.form.FormUrlEncodedRequestBody.toString(FormUrlEncodedRequestBody.java:114)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at io.gatling.http.client.Request.toString(Request.java:196)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1184)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1293)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1293)
	at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
	at io.gatling.http.response.HttpFailure.toString(Response.scala:35)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at io.gatling.http.engine.response.ResponseProcessor$.processFailure(ResponseProcessor.scala:126)
	at io.gatling.http.engine.response.DefaultResponseProcessor.onComplete(ResponseProcessor.scala:159)
	at io.gatling.http.engine.GatlingHttpListener.onThrowable(GatlingHttpListener.scala:234)
	at io.gatling.http.client.impl.HttpAppHandler.crash(HttpAppHandler.java:86)
	at io.gatling.http.client.impl.HttpAppHandler.exceptionCaught(HttpAppHandler.java:247)
	at io.gatling.http.client.impl.HttpAppHandler.write(HttpAppHandler.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
	at io.gatling.http.client.impl.DefaultHttpClient.sendTxWithChannel(DefaultHttpClient.java:484)
	at io.gatling.http.client.impl.DefaultHttpClient.lambda$null$7(DefaultHttpClient.java:610)
```

**Comment by slandelle** [comment]
Thanks for reporting.
It looks like an edge case when the params are empty, to be fixed in FormUrlEncodedRequestBody.
Interested in contributing a fix?

**Comment by Amerousful** [comment]
You're welcome!) 
Yep, it's an edge case. I accidentally caught it when I was working with this - https://github.com/gatling/gatling/pull/4412
Of course, I'll be really glad to contribute)

**Comment by Amerousful** [comment]
https://github.com/gatling/gatling/pull/4414
