### ISSUE TITLE
Gatling trying to access simulation.log folder with no file writer configuration

### ISSUE THREAD

**Issue by oddfrost** [gatling/gatling#4447]
Gatling version 3.9.5
Maven plugin 4.3.7

gatling.conf:
`
writers = [console, graphite] 
`
command to run:
`
mvn gatling:test -X -Dgatling.simulationClass=gatling.simulations.SomeSimulation 
`
also tried:
`
-Dgatling.noReports=true -Dgatling.resultsFolder=./target/gatling
`

Error:
```
Caused by: java.lang.IllegalArgumentException: requirement failed: simulation directory '<path to taget/gatling/simulation-folder-with-timestamp>' doesn't exist
        at scala.Predef$.require(Predef.scala:337)
        at io.gatling.core.config.GatlingFiles$.simulationLogDirectory(GatlingFiles.scala:39)
        at io.gatling.charts.stats.LogFileReader$.apply(LogFileReader.scala:44)
        at io.gatling.app.RunResultProcessor.initLogFileData(RunResultProcessor.scala:50)
        at io.gatling.app.RunResultProcessor.processRunResult(RunResultProcessor.scala:32)

```

**Comment by oddfrost** [comment]
As a result maven return code is 1 (error)

**Comment by slandelle** [comment]
Won't do. Please remember that our log file is an internal, not a user feature.

**Comment by slandelle** [comment]
Sorry, didn't read properly. Contributions welcome.

**Comment by slandelle** [comment]
I suspect there's a problem on your side.
This case is supposed to be handled see https://github.com/gatling/gatling/blob/main/gatling-app/src/main/scala/io/gatling/app/RunResultProcessor.scala#L57-L58

Also, I've tried to reproduce to no avail:
* cloned https://github.com/gatling/gatling-maven-plugin-demo-java
* changed `#writers = [console, file]` into `writers = [console]` in `gatling.conf`
=> works just fine

Declining for now.

Please chime in if you can come up with a reproducer.
