### ISSUE TITLE
DriverTimeoutException causes simulation to be broken

### ISSUE THREAD

**Issue by sikos** [gatling/gatling#4595]
Hello, 

We have created a simulation that was suppose to last 2h, but unfortunately it ended being in the broken `state`
```
[14:01:33,082]	Simulation info could be fetched from all instances. Proceeding with starting.
[14:01:33,086]	Injector pool1/vudckgatlinginj001.boursorama.fr successfully started. Still waiting for (pool1/vudckgatlinginj003.boursorama.fr, pool1/vudckgatlinginj002.boursorama.fr, pool1/vudckgatlinginj004.boursorama.fr)
[14:01:33,087]	Injector pool1/vudckgatlinginj004.boursorama.fr successfully started. Still waiting for (pool1/vudckgatlinginj003.boursorama.fr, pool1/vudckgatlinginj002.boursorama.fr)
[14:01:33,088]	Injector pool1/vudckgatlinginj002.boursorama.fr successfully started. Still waiting for (pool1/vudckgatlinginj003.boursorama.fr)
[14:01:33,088]	Injector pool1/vudckgatlinginj003.boursorama.fr successfully started.
[14:01:33,088]	All injectors could be started. Proceeding with Running.
[14:01:33,088]	Run ad3d6113-c678-4411-9ade-020470909f6f: starting injection
[15:19:00,215]	Persistence crashed: Run ad3d6113-c678-4411-9ade-020470909f6f: failed to persist stats: c.d.o.d.a.c.DriverTimeoutException: Query timed out after PT2S. Stopping.. Stopping
[15:19:01,196]	Failed to updateRunDuration: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

please note that the error appears at [15:19:00,215] while the simulation was running perfectly fine.
Is there anything we have to check to ensure simulation run smoothly ?

Using galing enterprise with 4 injector in docker.

Thank you for your time and consideration.

**Comment by slandelle** [comment]
Wrong place. People from our company will reach out privately.
